// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :one
INSERT INTO campaign.members (campaign_id, auth_subject, display_name, role, joined_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (campaign_id, auth_subject) DO UPDATE SET display_name = campaign.members.display_name
RETURNING id, campaign_id, auth_subject, display_name, role, joined_at
`

type AddMemberParams struct {
	CampaignID  uuid.UUID
	AuthSubject string
	DisplayName string
	Role        string
	Now         time.Time
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (CampaignMember, error) {
	row := q.db.QueryRow(ctx, addMember,
		arg.CampaignID,
		arg.AuthSubject,
		arg.DisplayName,
		arg.Role,
		arg.Now,
	)
	var i CampaignMember
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AuthSubject,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countDMs = `-- name: CountDMs :one
SELECT count(*)::int FROM campaign.members WHERE campaign_id = $1 AND role = 'dm'
`

func (q *Queries) CountDMs(ctx context.Context, campaignID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countDMs, campaignID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaign.campaigns (name, ruleset_pref, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, name, ruleset_pref, reaction_timeout_s, high_ground, rest_supplies, initiative_mode, share_initiative, creation_methods, starting_level, hold_level_ups, created_at
`

type CreateCampaignParams struct {
	Name        string
	RulesetPref string
	CreatedBy   string
	Now         time.Time
}

type CreateCampaignRow struct {
	ID               uuid.UUID
	Name             string
	RulesetPref      string
	ReactionTimeoutS int32
	HighGround       bool
	RestSupplies     bool
	InitiativeMode   string
	ShareInitiative  bool
	CreationMethods  []string
	StartingLevel    int32
	HoldLevelUps     bool
	CreatedAt        time.Time
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.RulesetPref,
		arg.CreatedBy,
		arg.Now,
	)
	var i CreateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RulesetPref,
		&i.ReactionTimeoutS,
		&i.HighGround,
		&i.RestSupplies,
		&i.InitiativeMode,
		&i.ShareInitiative,
		&i.CreationMethods,
		&i.StartingLevel,
		&i.HoldLevelUps,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO campaign.invites (campaign_id, token_hash, created_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, expires_at
`

type CreateInviteParams struct {
	CampaignID uuid.UUID
	TokenHash  []byte
	CreatedBy  uuid.UUID
	Now        time.Time
	ExpiresAt  time.Time
}

type CreateInviteRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.CampaignID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.Now,
		arg.ExpiresAt,
	)
	var i CreateInviteRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const findInvite = `-- name: FindInvite :one
SELECT i.id, i.campaign_id, c.name AS campaign_name, m.display_name AS created_by_name
FROM campaign.invites i
JOIN campaign.campaigns c ON c.id = i.campaign_id
JOIN campaign.members m ON m.id = i.created_by
WHERE i.token_hash = $1 AND i.revoked_at IS NULL AND i.expires_at > $2
`

type FindInviteParams struct {
	TokenHash []byte
	Now       time.Time
}

type FindInviteRow struct {
	ID            uuid.UUID
	CampaignID    uuid.UUID
	CampaignName  string
	CreatedByName string
}

func (q *Queries) FindInvite(ctx context.Context, arg FindInviteParams) (FindInviteRow, error) {
	row := q.db.QueryRow(ctx, findInvite, arg.TokenHash, arg.Now)
	var i FindInviteRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CampaignName,
		&i.CreatedByName,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, ruleset_pref, reaction_timeout_s, high_ground, rest_supplies, initiative_mode, share_initiative, creation_methods, starting_level, hold_level_ups, created_at FROM campaign.campaigns WHERE id = $1
`

type GetCampaignRow struct {
	ID               uuid.UUID
	Name             string
	RulesetPref      string
	ReactionTimeoutS int32
	HighGround       bool
	RestSupplies     bool
	InitiativeMode   string
	ShareInitiative  bool
	CreationMethods  []string
	StartingLevel    int32
	HoldLevelUps     bool
	CreatedAt        time.Time
}

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (GetCampaignRow, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i GetCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RulesetPref,
		&i.ReactionTimeoutS,
		&i.HighGround,
		&i.RestSupplies,
		&i.InitiativeMode,
		&i.ShareInitiative,
		&i.CreationMethods,
		&i.StartingLevel,
		&i.HoldLevelUps,
		&i.CreatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, campaign_id, auth_subject, display_name, role, joined_at
FROM campaign.members WHERE campaign_id = $1 AND id = $2
`

type GetMemberParams struct {
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (CampaignMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.CampaignID, arg.ID)
	var i CampaignMember
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AuthSubject,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, campaign_id, auth_subject, display_name, role, joined_at
FROM campaign.members WHERE campaign_id = $1 AND auth_subject = $2
`

type GetMembershipParams struct {
	CampaignID  uuid.UUID
	AuthSubject string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (CampaignMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.CampaignID, arg.AuthSubject)
	var i CampaignMember
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AuthSubject,
		&i.DisplayName,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listCampaignsForSubject = `-- name: ListCampaignsForSubject :many
SELECT c.id, c.name, c.ruleset_pref, c.reaction_timeout_s, c.high_ground, c.rest_supplies, c.initiative_mode, c.share_initiative, c.creation_methods, c.starting_level, c.hold_level_ups, c.created_at, m.role,
       (SELECT count(*) FROM campaign.members x WHERE x.campaign_id = c.id)::int AS member_count
FROM campaign.campaigns c
JOIN campaign.members m ON m.campaign_id = c.id AND m.auth_subject = $1
WHERE $2::timestamptz IS NULL
   OR (c.created_at, c.id) < ($2::timestamptz, $3::uuid)
ORDER BY c.created_at DESC, c.id DESC
LIMIT $4
`

type ListCampaignsForSubjectParams struct {
	Subject      string
	AfterCreated pgtype.Timestamptz
	AfterID      pgtype.UUID
	PageSize     int32
}

type ListCampaignsForSubjectRow struct {
	ID               uuid.UUID
	Name             string
	RulesetPref      string
	ReactionTimeoutS int32
	HighGround       bool
	RestSupplies     bool
	InitiativeMode   string
	ShareInitiative  bool
	CreationMethods  []string
	StartingLevel    int32
	HoldLevelUps     bool
	CreatedAt        time.Time
	Role             string
	MemberCount      int32
}

func (q *Queries) ListCampaignsForSubject(ctx context.Context, arg ListCampaignsForSubjectParams) ([]ListCampaignsForSubjectRow, error) {
	rows, err := q.db.Query(ctx, listCampaignsForSubject,
		arg.Subject,
		arg.AfterCreated,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignsForSubjectRow{}
	for rows.Next() {
		var i ListCampaignsForSubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RulesetPref,
			&i.ReactionTimeoutS,
			&i.HighGround,
			&i.RestSupplies,
			&i.InitiativeMode,
			&i.ShareInitiative,
			&i.CreationMethods,
			&i.StartingLevel,
			&i.HoldLevelUps,
			&i.CreatedAt,
			&i.Role,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT i.id, i.created_at, i.expires_at, m.display_name AS created_by_name
FROM campaign.invites i JOIN campaign.members m ON m.id = i.created_by
WHERE i.campaign_id = $1 AND i.revoked_at IS NULL AND i.expires_at > $2
ORDER BY i.created_at DESC, i.id DESC
`

type ListInvitesParams struct {
	CampaignID uuid.UUID
	Now        time.Time
}

type ListInvitesRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	ExpiresAt     time.Time
	CreatedByName string
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites, arg.CampaignID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, campaign_id, auth_subject, display_name, role, joined_at
FROM campaign.members WHERE campaign_id = $1 ORDER BY role, display_name, id
`

func (q *Queries) ListMembers(ctx context.Context, campaignID uuid.UUID) ([]CampaignMember, error) {
	rows, err := q.db.Query(ctx, listMembers, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignMember{}
	for rows.Next() {
		var i CampaignMember
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AuthSubject,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCampaign = `-- name: LockCampaign :exec
SELECT id FROM campaign.campaigns WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCampaign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockCampaign, id)
	return err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM campaign.members WHERE campaign_id = $1 AND id = $2
`

type RemoveMemberParams struct {
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.CampaignID, arg.ID)
	return err
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE campaign.invites SET revoked_at = $1::timestamptz
WHERE campaign_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	Now        time.Time
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.Now, arg.CampaignID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMemberRole = `-- name: SetMemberRole :exec
UPDATE campaign.members SET role = $1 WHERE campaign_id = $2 AND id = $3
`

type SetMemberRoleParams struct {
	Role       string
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error {
	_, err := q.db.Exec(ctx, setMemberRole, arg.Role, arg.CampaignID, arg.ID)
	return err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaign.campaigns
SET name = coalesce($1::text, name),
    ruleset_pref = coalesce($2::text, ruleset_pref),
    reaction_timeout_s = coalesce($3::integer, reaction_timeout_s),
    high_ground = coalesce($4::boolean, high_ground),
    rest_supplies = coalesce($5::boolean, rest_supplies),
    initiative_mode = coalesce($6::text, initiative_mode),
    share_initiative = coalesce($7::boolean, share_initiative),
    creation_methods = coalesce($8::text[], creation_methods),
    starting_level = coalesce($9::integer, starting_level),
    hold_level_ups = coalesce($10::boolean, hold_level_ups),
    updated_at = $11
WHERE id = $12
RETURNING id, name, ruleset_pref, reaction_timeout_s, high_ground, rest_supplies, initiative_mode, share_initiative, creation_methods, starting_level, hold_level_ups, created_at
`

type UpdateCampaignParams struct {
	Name             pgtype.Text
	RulesetPref      pgtype.Text
	ReactionTimeoutS pgtype.Int4
	HighGround       pgtype.Bool
	RestSupplies     pgtype.Bool
	InitiativeMode   pgtype.Text
	ShareInitiative  pgtype.Bool
	CreationMethods  []string
	StartingLevel    pgtype.Int4
	HoldLevelUps     pgtype.Bool
	Now              time.Time
	ID               uuid.UUID
}

type UpdateCampaignRow struct {
	ID               uuid.UUID
	Name             string
	RulesetPref      string
	ReactionTimeoutS int32
	HighGround       bool
	RestSupplies     bool
	InitiativeMode   string
	ShareInitiative  bool
	CreationMethods  []string
	StartingLevel    int32
	HoldLevelUps     bool
	CreatedAt        time.Time
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (UpdateCampaignRow, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.Name,
		arg.RulesetPref,
		arg.ReactionTimeoutS,
		arg.HighGround,
		arg.RestSupplies,
		arg.InitiativeMode,
		arg.ShareInitiative,
		arg.CreationMethods,
		arg.StartingLevel,
		arg.HoldLevelUps,
		arg.Now,
		arg.ID,
	)
	var i UpdateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RulesetPref,
		&i.ReactionTimeoutS,
		&i.HighGround,
		&i.RestSupplies,
		&i.InitiativeMode,
		&i.ShareInitiative,
		&i.CreationMethods,
		&i.StartingLevel,
		&i.HoldLevelUps,
		&i.CreatedAt,
	)
	return i, err
}
