// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compendium.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abilityIDBySlug = `-- name: AbilityIDBySlug :one
SELECT id FROM compendium.ability_scores WHERE slug = $1
`

func (q *Queries) AbilityIDBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, abilityIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addSpellClass = `-- name: AddSpellClass :exec
INSERT INTO compendium.spell_classes (spell_id, class_slug) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSpellClassParams struct {
	SpellID   int64
	ClassSlug string
}

func (q *Queries) AddSpellClass(ctx context.Context, arg AddSpellClassParams) error {
	_, err := q.db.Exec(ctx, addSpellClass, arg.SpellID, arg.ClassSlug)
	return err
}

const addSpellDamageType = `-- name: AddSpellDamageType :exec
INSERT INTO compendium.spell_damage_types (spell_id, damage_type_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddSpellDamageTypeParams struct {
	SpellID      int64
	DamageTypeID int64
}

func (q *Queries) AddSpellDamageType(ctx context.Context, arg AddSpellDamageTypeParams) error {
	_, err := q.db.Exec(ctx, addSpellDamageType, arg.SpellID, arg.DamageTypeID)
	return err
}

const addSpellScaling = `-- name: AddSpellScaling :exec
INSERT INTO compendium.spell_scaling (spell_id, kind, at_level, damage_roll) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddSpellScalingParams struct {
	SpellID    int64
	Kind       string
	AtLevel    int32
	DamageRoll string
}

func (q *Queries) AddSpellScaling(ctx context.Context, arg AddSpellScalingParams) error {
	_, err := q.db.Exec(ctx, addSpellScaling,
		arg.SpellID,
		arg.Kind,
		arg.AtLevel,
		arg.DamageRoll,
	)
	return err
}

const clearSpellChildren = `-- name: ClearSpellChildren :exec
WITH c AS (DELETE FROM compendium.spell_classes WHERE spell_classes.spell_id = $1),
     d AS (DELETE FROM compendium.spell_damage_types WHERE spell_damage_types.spell_id = $1)
DELETE FROM compendium.spell_scaling WHERE spell_scaling.spell_id = $1
`

func (q *Queries) ClearSpellChildren(ctx context.Context, spellID int64) error {
	_, err := q.db.Exec(ctx, clearSpellChildren, spellID)
	return err
}

const compendiumVersion = `-- name: CompendiumVersion :one
SELECT coalesce(max(id), 0)::bigint AS version FROM ops.compendium_imports
`

func (q *Queries) CompendiumVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, compendiumVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const conditionsForDocument = `-- name: ConditionsForDocument :many
SELECT c.slug, c.name, c.description FROM compendium.conditions c
JOIN compendium.documents d ON d.id = c.document_id
WHERE d.key = $1 ORDER BY c.name
`

type ConditionsForDocumentRow struct {
	Slug        string
	Name        string
	Description string
}

func (q *Queries) ConditionsForDocument(ctx context.Context, documentKey string) ([]ConditionsForDocumentRow, error) {
	rows, err := q.db.Query(ctx, conditionsForDocument, documentKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConditionsForDocumentRow{}
	for rows.Next() {
		var i ConditionsForDocumentRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpell = `-- name: GetSpell :one
SELECT s.id, s.slug, s.name, s.level, sch.slug AS school, d.key AS document_key, s.casting_time, s.range_text,
       s.range_feet, s.requires_verbal, s.requires_somatic, s.requires_material, s.material_text, s.ritual,
       s.concentration, s.duration, s.description, s.higher_level, ab.slug AS save_ability, s.attack_roll, s.damage_roll
FROM compendium.spells s
JOIN compendium.documents d ON d.id = s.document_id
JOIN compendium.magic_schools sch ON sch.id = s.school_id
LEFT JOIN compendium.ability_scores ab ON ab.id = s.save_ability_id
WHERE s.slug = $1 AND d.key LIKE 'srd-%' AND ($2::text IS NULL OR d.key = $2::text)
ORDER BY d.precedence DESC
LIMIT 1
`

type GetSpellParams struct {
	Slug    string
	Ruleset pgtype.Text
}

type GetSpellRow struct {
	ID               int64
	Slug             string
	Name             string
	Level            int32
	School           string
	DocumentKey      string
	CastingTime      string
	RangeText        string
	RangeFeet        pgtype.Int4
	RequiresVerbal   bool
	RequiresSomatic  bool
	RequiresMaterial bool
	MaterialText     pgtype.Text
	Ritual           bool
	Concentration    bool
	Duration         string
	Description      string
	HigherLevel      pgtype.Text
	SaveAbility      pgtype.Text
	AttackRoll       bool
	DamageRoll       pgtype.Text
}

func (q *Queries) GetSpell(ctx context.Context, arg GetSpellParams) (GetSpellRow, error) {
	row := q.db.QueryRow(ctx, getSpell, arg.Slug, arg.Ruleset)
	var i GetSpellRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Level,
		&i.School,
		&i.DocumentKey,
		&i.CastingTime,
		&i.RangeText,
		&i.RangeFeet,
		&i.RequiresVerbal,
		&i.RequiresSomatic,
		&i.RequiresMaterial,
		&i.MaterialText,
		&i.Ritual,
		&i.Concentration,
		&i.Duration,
		&i.Description,
		&i.HigherLevel,
		&i.SaveAbility,
		&i.AttackRoll,
		&i.DamageRoll,
	)
	return i, err
}

const latestSnapshotHash = `-- name: LatestSnapshotHash :one
SELECT coalesce((SELECT snapshot_hash FROM ops.compendium_imports ORDER BY id DESC LIMIT 1), '')::text AS snapshot_hash
`

func (q *Queries) LatestSnapshotHash(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, latestSnapshotHash)
	var snapshot_hash string
	err := row.Scan(&snapshot_hash)
	return snapshot_hash, err
}

const listSources = `-- name: ListSources :many
SELECT key, title, ruleset_year, license, attribution, url FROM compendium.documents WHERE key LIKE 'srd-%' ORDER BY precedence DESC, key
`

type ListSourcesRow struct {
	Key         string
	Title       string
	RulesetYear int32
	License     string
	Attribution string
	Url         string
}

func (q *Queries) ListSources(ctx context.Context) ([]ListSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourcesRow{}
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(
			&i.Key,
			&i.Title,
			&i.RulesetYear,
			&i.License,
			&i.Attribution,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpells = `-- name: ListSpells :many
WITH effective AS (
    SELECT DISTINCT ON (s.slug)
        s.id, s.slug, s.name, s.level, s.school_id, s.ritual, s.concentration, d.key AS document_key
    FROM compendium.spells s
    JOIN compendium.documents d ON d.id = s.document_id
    WHERE d.key LIKE 'srd-%' AND ($8::text IS NULL OR d.key = $8::text)
    ORDER BY s.slug, d.precedence DESC
)
SELECT e.slug, e.name, e.level, sch.slug AS school, e.ritual, e.concentration, e.document_key
FROM effective e
JOIN compendium.magic_schools sch ON sch.id = e.school_id
WHERE ($1::text IS NULL OR e.name ILIKE '%' || $1::text || '%')
  AND ($2::integer IS NULL OR e.level = $2::integer)
  AND ($3::text IS NULL OR sch.slug = $3::text)
  AND ($4::text IS NULL OR EXISTS (
        SELECT 1 FROM compendium.spell_classes sc WHERE sc.spell_id = e.id AND sc.class_slug = $4::text))
  AND ($5::text IS NULL OR (e.name, e.slug) > ($5::text, $6::text))
ORDER BY e.name, e.slug
LIMIT $7
`

type ListSpellsParams struct {
	Query     pgtype.Text
	Level     pgtype.Int4
	School    pgtype.Text
	ClassSlug pgtype.Text
	AfterName pgtype.Text
	AfterSlug pgtype.Text
	PageSize  int32
	Ruleset   pgtype.Text
}

type ListSpellsRow struct {
	Slug          string
	Name          string
	Level         int32
	School        string
	Ritual        bool
	Concentration bool
	DocumentKey   string
}

func (q *Queries) ListSpells(ctx context.Context, arg ListSpellsParams) ([]ListSpellsRow, error) {
	rows, err := q.db.Query(ctx, listSpells,
		arg.Query,
		arg.Level,
		arg.School,
		arg.ClassSlug,
		arg.AfterName,
		arg.AfterSlug,
		arg.PageSize,
		arg.Ruleset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpellsRow{}
	for rows.Next() {
		var i ListSpellsRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.Level,
			&i.School,
			&i.Ritual,
			&i.Concentration,
			&i.DocumentKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCompendiumImport = `-- name: RecordCompendiumImport :one
INSERT INTO ops.compendium_imports (snapshot_hash) VALUES ($1) RETURNING id
`

func (q *Queries) RecordCompendiumImport(ctx context.Context, snapshotHash string) (int64, error) {
	row := q.db.QueryRow(ctx, recordCompendiumImport, snapshotHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const spellClasses = `-- name: SpellClasses :many
SELECT class_slug FROM compendium.spell_classes WHERE spell_id = $1 ORDER BY class_slug
`

func (q *Queries) SpellClasses(ctx context.Context, spellID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, spellClasses, spellID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var class_slug string
		if err := rows.Scan(&class_slug); err != nil {
			return nil, err
		}
		items = append(items, class_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spellDamageTypes = `-- name: SpellDamageTypes :many
SELECT dt.slug FROM compendium.spell_damage_types sdt
JOIN compendium.damage_types dt ON dt.id = sdt.damage_type_id
WHERE sdt.spell_id = $1 ORDER BY dt.slug
`

func (q *Queries) SpellDamageTypes(ctx context.Context, spellID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, spellDamageTypes, spellID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var slug string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spellScaling = `-- name: SpellScaling :many
SELECT kind, at_level, damage_roll FROM compendium.spell_scaling WHERE spell_id = $1 ORDER BY kind, at_level
`

type SpellScalingRow struct {
	Kind       string
	AtLevel    int32
	DamageRoll string
}

func (q *Queries) SpellScaling(ctx context.Context, spellID int64) ([]SpellScalingRow, error) {
	rows, err := q.db.Query(ctx, spellScaling, spellID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpellScalingRow{}
	for rows.Next() {
		var i SpellScalingRow
		if err := rows.Scan(&i.Kind, &i.AtLevel, &i.DamageRoll); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCondition = `-- name: UpsertCondition :exec
INSERT INTO compendium.conditions (document_id, slug, name, description) VALUES ($1, $2, $3, $4)
ON CONFLICT (slug, document_id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description
`

type UpsertConditionParams struct {
	DocumentID  int64
	Slug        string
	Name        string
	Description string
}

func (q *Queries) UpsertCondition(ctx context.Context, arg UpsertConditionParams) error {
	_, err := q.db.Exec(ctx, upsertCondition,
		arg.DocumentID,
		arg.Slug,
		arg.Name,
		arg.Description,
	)
	return err
}

const upsertDamageType = `-- name: UpsertDamageType :one
INSERT INTO compendium.damage_types (slug, name) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertDamageTypeParams struct {
	Slug string
	Name string
}

func (q *Queries) UpsertDamageType(ctx context.Context, arg UpsertDamageTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDamageType, arg.Slug, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO compendium.documents (key, title, ruleset_year, precedence, license, attribution, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (key) DO UPDATE SET
    title = EXCLUDED.title, ruleset_year = EXCLUDED.ruleset_year, precedence = EXCLUDED.precedence,
    license = EXCLUDED.license, attribution = EXCLUDED.attribution, url = EXCLUDED.url
RETURNING id
`

type UpsertDocumentParams struct {
	Key         string
	Title       string
	RulesetYear int32
	Precedence  int32
	License     string
	Attribution string
	Url         string
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.Key,
		arg.Title,
		arg.RulesetYear,
		arg.Precedence,
		arg.License,
		arg.Attribution,
		arg.Url,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertMagicSchool = `-- name: UpsertMagicSchool :one
INSERT INTO compendium.magic_schools (slug, name) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type UpsertMagicSchoolParams struct {
	Slug string
	Name string
}

func (q *Queries) UpsertMagicSchool(ctx context.Context, arg UpsertMagicSchoolParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertMagicSchool, arg.Slug, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSpell = `-- name: UpsertSpell :one
INSERT INTO compendium.spells (
    document_id, slug, name, level, school_id, casting_time, range_text, range_feet,
    requires_verbal, requires_somatic, requires_material, material_text, ritual, concentration,
    duration, description, higher_level, save_ability_id, attack_roll, damage_roll
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20
)
ON CONFLICT (slug, document_id) DO UPDATE SET
    name = EXCLUDED.name, level = EXCLUDED.level, school_id = EXCLUDED.school_id,
    casting_time = EXCLUDED.casting_time, range_text = EXCLUDED.range_text, range_feet = EXCLUDED.range_feet,
    requires_verbal = EXCLUDED.requires_verbal, requires_somatic = EXCLUDED.requires_somatic,
    requires_material = EXCLUDED.requires_material, material_text = EXCLUDED.material_text,
    ritual = EXCLUDED.ritual, concentration = EXCLUDED.concentration, duration = EXCLUDED.duration,
    description = EXCLUDED.description, higher_level = EXCLUDED.higher_level,
    save_ability_id = EXCLUDED.save_ability_id, attack_roll = EXCLUDED.attack_roll, damage_roll = EXCLUDED.damage_roll
RETURNING id
`

type UpsertSpellParams struct {
	DocumentID       int64
	Slug             string
	Name             string
	Level            int32
	SchoolID         int64
	CastingTime      string
	RangeText        string
	RangeFeet        pgtype.Int4
	RequiresVerbal   bool
	RequiresSomatic  bool
	RequiresMaterial bool
	MaterialText     pgtype.Text
	Ritual           bool
	Concentration    bool
	Duration         string
	Description      string
	HigherLevel      pgtype.Text
	SaveAbilityID    pgtype.Int8
	AttackRoll       bool
	DamageRoll       pgtype.Text
}

func (q *Queries) UpsertSpell(ctx context.Context, arg UpsertSpellParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertSpell,
		arg.DocumentID,
		arg.Slug,
		arg.Name,
		arg.Level,
		arg.SchoolID,
		arg.CastingTime,
		arg.RangeText,
		arg.RangeFeet,
		arg.RequiresVerbal,
		arg.RequiresSomatic,
		arg.RequiresMaterial,
		arg.MaterialText,
		arg.Ritual,
		arg.Concentration,
		arg.Duration,
		arg.Description,
		arg.HigherLevel,
		arg.SaveAbilityID,
		arg.AttackRoll,
		arg.DamageRoll,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
