// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downtime.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const campaignDowntime = `-- name: CampaignDowntime :one
SELECT game_day, game_minute, downtime_advanced FROM campaign.campaigns WHERE id = $1
`

type CampaignDowntimeRow struct {
	GameDay          int32
	GameMinute       int32
	DowntimeAdvanced int32
}

func (q *Queries) CampaignDowntime(ctx context.Context, id uuid.UUID) (CampaignDowntimeRow, error) {
	row := q.db.QueryRow(ctx, campaignDowntime, id)
	var i CampaignDowntimeRow
	err := row.Scan(&i.GameDay, &i.GameMinute, &i.DowntimeAdvanced)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM campaign.recipes WHERE campaign_id = $1 AND id = $2
`

type DeleteRecipeParams struct {
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecipe, arg.CampaignID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const downtimeCharacters = `-- name: DowntimeCharacters :many
SELECT id, name, owner_member_id, downtime_days, downtime_spent FROM campaign.characters WHERE campaign_id = $1 ORDER BY name, id
`

type DowntimeCharactersRow struct {
	ID            uuid.UUID
	Name          string
	OwnerMemberID uuid.UUID
	DowntimeDays  int32
	DowntimeSpent int32
}

func (q *Queries) DowntimeCharacters(ctx context.Context, campaignID uuid.UUID) ([]DowntimeCharactersRow, error) {
	rows, err := q.db.Query(ctx, downtimeCharacters, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DowntimeCharactersRow{}
	for rows.Next() {
		var i DowntimeCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerMemberID,
			&i.DowntimeDays,
			&i.DowntimeSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantDowntimeToAll = `-- name: GrantDowntimeToAll :exec
UPDATE campaign.characters SET downtime_days = LEAST(downtime_days + $1, 100000), downtime_spent = 0 WHERE campaign_id = $2
`

type GrantDowntimeToAllParams struct {
	Days       int32
	CampaignID uuid.UUID
}

// A downtime given to the whole party is a new one: every Character starts it having lived through none of it.
func (q *Queries) GrantDowntimeToAll(ctx context.Context, arg GrantDowntimeToAllParams) error {
	_, err := q.db.Exec(ctx, grantDowntimeToAll, arg.Days, arg.CampaignID)
	return err
}

const grantDowntimeToOne = `-- name: GrantDowntimeToOne :execrows
UPDATE campaign.characters SET downtime_days = LEAST(downtime_days + $1, 100000) WHERE campaign_id = $2 AND id = $3
`

type GrantDowntimeToOneParams struct {
	Days       int32
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GrantDowntimeToOne(ctx context.Context, arg GrantDowntimeToOneParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantDowntimeToOne, arg.Days, arg.CampaignID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDowntimeLog = `-- name: InsertDowntimeLog :exec
INSERT INTO campaign.downtime_log (id, campaign_id, character_id, activity, detail, days, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertDowntimeLogParams struct {
	ID          uuid.UUID
	CampaignID  uuid.UUID
	CharacterID uuid.UUID
	Activity    string
	Detail      string
	Days        int32
	Now         time.Time
}

func (q *Queries) InsertDowntimeLog(ctx context.Context, arg InsertDowntimeLogParams) error {
	_, err := q.db.Exec(ctx, insertDowntimeLog,
		arg.ID,
		arg.CampaignID,
		arg.CharacterID,
		arg.Activity,
		arg.Detail,
		arg.Days,
		arg.Now,
	)
	return err
}

const insertRecipe = `-- name: InsertRecipe :exec
INSERT INTO campaign.recipes (id, campaign_id, name, item_slug, quantity, tool_slug, days, cost_cp, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertRecipeParams struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	Name       string
	ItemSlug   string
	Quantity   int32
	ToolSlug   pgtype.Text
	Days       int32
	CostCp     int32
	Now        time.Time
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) error {
	_, err := q.db.Exec(ctx, insertRecipe,
		arg.ID,
		arg.CampaignID,
		arg.Name,
		arg.ItemSlug,
		arg.Quantity,
		arg.ToolSlug,
		arg.Days,
		arg.CostCp,
		arg.Now,
	)
	return err
}

const insertRecipeIngredient = `-- name: InsertRecipeIngredient :exec
INSERT INTO campaign.recipe_ingredients (recipe_id, position, item_slug, count) VALUES ($1, $2, $3, $4)
`

type InsertRecipeIngredientParams struct {
	RecipeID uuid.UUID
	Position int32
	ItemSlug string
	Count    int32
}

func (q *Queries) InsertRecipeIngredient(ctx context.Context, arg InsertRecipeIngredientParams) error {
	_, err := q.db.Exec(ctx, insertRecipeIngredient,
		arg.RecipeID,
		arg.Position,
		arg.ItemSlug,
		arg.Count,
	)
	return err
}

const listDowntimeLog = `-- name: ListDowntimeLog :many
SELECT l.id, l.character_id, c.name AS character_name, l.activity, l.detail, l.days, l.created_at
FROM campaign.downtime_log l JOIN campaign.characters c ON c.id = l.character_id
WHERE l.campaign_id = $1 ORDER BY l.created_at DESC, l.id LIMIT 50
`

type ListDowntimeLogRow struct {
	ID            uuid.UUID
	CharacterID   uuid.UUID
	CharacterName string
	Activity      string
	Detail        string
	Days          int32
	CreatedAt     time.Time
}

func (q *Queries) ListDowntimeLog(ctx context.Context, campaignID uuid.UUID) ([]ListDowntimeLogRow, error) {
	rows, err := q.db.Query(ctx, listDowntimeLog, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDowntimeLogRow{}
	for rows.Next() {
		var i ListDowntimeLogRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.CharacterName,
			&i.Activity,
			&i.Detail,
			&i.Days,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT i.recipe_id, i.item_slug, i.count FROM campaign.recipe_ingredients i JOIN campaign.recipes r ON r.id = i.recipe_id
WHERE r.campaign_id = $1 ORDER BY i.recipe_id, i.position
`

type ListRecipeIngredientsRow struct {
	RecipeID uuid.UUID
	ItemSlug string
	Count    int32
}

func (q *Queries) ListRecipeIngredients(ctx context.Context, campaignID uuid.UUID) ([]ListRecipeIngredientsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipeIngredientsRow{}
	for rows.Next() {
		var i ListRecipeIngredientsRow
		if err := rows.Scan(&i.RecipeID, &i.ItemSlug, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, campaign_id, name, item_slug, quantity, tool_slug, days, cost_cp, created_at FROM campaign.recipes WHERE campaign_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListRecipes(ctx context.Context, campaignID uuid.UUID) ([]CampaignRecipe, error) {
	rows, err := q.db.Query(ctx, listRecipes, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignRecipe{}
	for rows.Next() {
		var i CampaignRecipe
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.ItemSlug,
			&i.Quantity,
			&i.ToolSlug,
			&i.Days,
			&i.CostCp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCampaignDowntime = `-- name: LockCampaignDowntime :one
SELECT id FROM campaign.campaigns WHERE id = $1 FOR UPDATE
`

// Holds the Campaign's downtime for one change at a time: whoever comes second reads what the first left.
func (q *Queries) LockCampaignDowntime(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCampaignDowntime, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const setCharacterDowntime = `-- name: SetCharacterDowntime :exec
UPDATE campaign.characters SET downtime_days = $1, downtime_spent = $2 WHERE id = $3
`

type SetCharacterDowntimeParams struct {
	Days  int32
	Spent int32
	ID    uuid.UUID
}

func (q *Queries) SetCharacterDowntime(ctx context.Context, arg SetCharacterDowntimeParams) error {
	_, err := q.db.Exec(ctx, setCharacterDowntime, arg.Days, arg.Spent, arg.ID)
	return err
}

const setDowntimeClock = `-- name: SetDowntimeClock :exec
UPDATE campaign.campaigns SET game_day = $1, game_minute = $2, downtime_advanced = $3 WHERE id = $4
`

type SetDowntimeClockParams struct {
	GameDay    int32
	GameMinute int32
	Advanced   int32
	ID         uuid.UUID
}

func (q *Queries) SetDowntimeClock(ctx context.Context, arg SetDowntimeClockParams) error {
	_, err := q.db.Exec(ctx, setDowntimeClock,
		arg.GameDay,
		arg.GameMinute,
		arg.Advanced,
		arg.ID,
	)
	return err
}

const trainingDays = `-- name: TrainingDays :one
SELECT coalesce(sum(days), 0)::int FROM campaign.downtime_log WHERE character_id = $1 AND activity = 'train' AND detail = $2
`

type TrainingDaysParams struct {
	CharacterID uuid.UUID
	Detail      string
}

// The days a Character has spent training in one thing.
func (q *Queries) TrainingDays(ctx context.Context, arg TrainingDaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, trainingDays, arg.CharacterID, arg.Detail)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
