// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: injuries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const characterInjuries = `-- name: CharacterInjuries :many
SELECT character_id, slug, name, cure, level FROM campaign.character_injuries WHERE character_id = $1 ORDER BY created_at, slug
`

type CharacterInjuriesRow struct {
	CharacterID uuid.UUID
	Slug        string
	Name        string
	Cure        string
	Level       int32
}

func (q *Queries) CharacterInjuries(ctx context.Context, characterID uuid.UUID) ([]CharacterInjuriesRow, error) {
	rows, err := q.db.Query(ctx, characterInjuries, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterInjuriesRow{}
	for rows.Next() {
		var i CharacterInjuriesRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Slug,
			&i.Name,
			&i.Cure,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCharacterInjury = `-- name: DeleteCharacterInjury :exec
DELETE FROM campaign.character_injuries WHERE character_id = $1 AND slug = $2
`

type DeleteCharacterInjuryParams struct {
	CharacterID uuid.UUID
	Slug        string
}

func (q *Queries) DeleteCharacterInjury(ctx context.Context, arg DeleteCharacterInjuryParams) error {
	_, err := q.db.Exec(ctx, deleteCharacterInjury, arg.CharacterID, arg.Slug)
	return err
}

const upsertCharacterInjury = `-- name: UpsertCharacterInjury :exec
INSERT INTO campaign.character_injuries (character_id, slug, name, cure, level, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (character_id, slug) DO UPDATE SET name = excluded.name, cure = excluded.cure, level = excluded.level
`

type UpsertCharacterInjuryParams struct {
	CharacterID uuid.UUID
	Slug        string
	Name        string
	Cure        string
	Level       int32
	Now         time.Time
}

func (q *Queries) UpsertCharacterInjury(ctx context.Context, arg UpsertCharacterInjuryParams) error {
	_, err := q.db.Exec(ctx, upsertCharacterInjury,
		arg.CharacterID,
		arg.Slug,
		arg.Name,
		arg.Cure,
		arg.Level,
		arg.Now,
	)
	return err
}
