// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addToLibraryCollection = `-- name: AddToLibraryCollection :exec
INSERT INTO library.collection_entries (collection_id, entry_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddToLibraryCollectionParams struct {
	CollectionID uuid.UUID
	EntryID      uuid.UUID
}

func (q *Queries) AddToLibraryCollection(ctx context.Context, arg AddToLibraryCollectionParams) error {
	_, err := q.db.Exec(ctx, addToLibraryCollection, arg.CollectionID, arg.EntryID)
	return err
}

const campaignHome = `-- name: CampaignHome :one
SELECT collection_id FROM library.campaign_homes WHERE campaign_id = $1
`

func (q *Queries) CampaignHome(ctx context.Context, campaignID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, campaignHome, campaignID)
	var collection_id uuid.UUID
	err := row.Scan(&collection_id)
	return collection_id, err
}

const campaignLibraryCollections = `-- name: CampaignLibraryCollections :many
SELECT c.id, c.owner_subject, c.name, c.description, c.created_at, c.updated_at,
    ARRAY(SELECT ce.entry_id FROM library.collection_entries ce WHERE ce.collection_id = c.id ORDER BY ce.entry_id)::uuid[] AS entry_ids,
    (cc.campaign_id IS NOT NULL)::boolean AS switched_on
FROM library.collections c
LEFT JOIN library.campaign_collections cc ON cc.collection_id = c.id AND cc.campaign_id = $1::uuid
WHERE c.owner_subject = $2 OR cc.campaign_id IS NOT NULL
ORDER BY lower(c.name), c.id
`

type CampaignLibraryCollectionsParams struct {
	CampaignID   pgtype.UUID
	OwnerSubject string
}

type CampaignLibraryCollectionsRow struct {
	ID           uuid.UUID
	OwnerSubject string
	Name         string
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EntryIds     []uuid.UUID
	SwitchedOn   bool
}

func (q *Queries) CampaignLibraryCollections(ctx context.Context, arg CampaignLibraryCollectionsParams) ([]CampaignLibraryCollectionsRow, error) {
	rows, err := q.db.Query(ctx, campaignLibraryCollections, arg.CampaignID, arg.OwnerSubject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLibraryCollectionsRow{}
	for rows.Next() {
		var i CampaignLibraryCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSubject,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryIds,
			&i.SwitchedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignLibraryLinks = `-- name: CampaignLibraryLinks :many
WITH visible AS (
    SELECT l.entry_id FROM library.campaign_links l WHERE l.campaign_id = $1 AND l.direct
    UNION
    SELECT ce.entry_id FROM library.collection_entries ce
    JOIN library.campaign_collections cc ON cc.collection_id = ce.collection_id WHERE cc.campaign_id = $1
)
SELECT e.id, e.owner_subject, e.kind, e.name, e.fields, e.revision, e.created_at, e.updated_at,
    l.pinned_revision, coalesce(l.override, '{}'::jsonb)::jsonb AS override, coalesce(l.direct, false)::boolean AS direct,
    r.name AS pinned_name, r.fields AS pinned_fields,
    ARRAY(SELECT c.name FROM library.collection_entries ce
        JOIN library.campaign_collections cc ON cc.collection_id = ce.collection_id AND cc.campaign_id = $1
        JOIN library.collections c ON c.id = ce.collection_id
        WHERE ce.entry_id = e.id ORDER BY c.name)::text[] AS via
FROM visible v
JOIN library.entries e ON e.id = v.entry_id
LEFT JOIN library.campaign_links l ON l.entry_id = e.id AND l.campaign_id = $1
LEFT JOIN library.entry_revisions r ON r.entry_id = e.id AND r.no = l.pinned_revision
WHERE $2::uuid IS NULL OR e.id = $2::uuid
ORDER BY e.kind, lower(e.name), e.id
`

type CampaignLibraryLinksParams struct {
	CampaignID uuid.UUID
	EntryID    pgtype.UUID
}

type CampaignLibraryLinksRow struct {
	ID             uuid.UUID
	OwnerSubject   string
	Kind           string
	Name           string
	Fields         []byte
	Revision       int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	PinnedRevision pgtype.Int4
	Override       []byte
	Direct         bool
	PinnedName     pgtype.Text
	PinnedFields   []byte
	Via            []string
}

func (q *Queries) CampaignLibraryLinks(ctx context.Context, arg CampaignLibraryLinksParams) ([]CampaignLibraryLinksRow, error) {
	rows, err := q.db.Query(ctx, campaignLibraryLinks, arg.CampaignID, arg.EntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignLibraryLinksRow{}
	for rows.Next() {
		var i CampaignLibraryLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSubject,
			&i.Kind,
			&i.Name,
			&i.Fields,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PinnedRevision,
			&i.Override,
			&i.Direct,
			&i.PinnedName,
			&i.PinnedFields,
			&i.Via,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignProposals = `-- name: CampaignProposals :many
SELECT id, campaign_id, author_subject, author_name, kind, name, fields, note, base_entry_id, status, message, entry_id, created_at, updated_at
FROM library.proposals
WHERE campaign_id = $1 AND ($2::text IS NULL OR author_subject = $2::text)
ORDER BY created_at DESC, id
`

type CampaignProposalsParams struct {
	CampaignID    uuid.UUID
	AuthorSubject pgtype.Text
}

func (q *Queries) CampaignProposals(ctx context.Context, arg CampaignProposalsParams) ([]LibraryProposal, error) {
	rows, err := q.db.Query(ctx, campaignProposals, arg.CampaignID, arg.AuthorSubject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryProposal{}
	for rows.Next() {
		var i LibraryProposal
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.AuthorSubject,
			&i.AuthorName,
			&i.Kind,
			&i.Name,
			&i.Fields,
			&i.Note,
			&i.BaseEntryID,
			&i.Status,
			&i.Message,
			&i.EntryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearLibraryCollection = `-- name: ClearLibraryCollection :exec
DELETE FROM library.collection_entries WHERE collection_id = $1
`

func (q *Queries) ClearLibraryCollection(ctx context.Context, collectionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearLibraryCollection, collectionID)
	return err
}

const insertCampaignHome = `-- name: InsertCampaignHome :exec
INSERT INTO library.campaign_homes (campaign_id, collection_id) VALUES ($1, $2)
`

type InsertCampaignHomeParams struct {
	CampaignID   uuid.UUID
	CollectionID uuid.UUID
}

func (q *Queries) InsertCampaignHome(ctx context.Context, arg InsertCampaignHomeParams) error {
	_, err := q.db.Exec(ctx, insertCampaignHome, arg.CampaignID, arg.CollectionID)
	return err
}

const insertLibraryCollection = `-- name: InsertLibraryCollection :exec
INSERT INTO library.collections (id, owner_subject, name, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
`

type InsertLibraryCollectionParams struct {
	ID           uuid.UUID
	OwnerSubject string
	Name         string
	Description  string
	Now          time.Time
}

func (q *Queries) InsertLibraryCollection(ctx context.Context, arg InsertLibraryCollectionParams) error {
	_, err := q.db.Exec(ctx, insertLibraryCollection,
		arg.ID,
		arg.OwnerSubject,
		arg.Name,
		arg.Description,
		arg.Now,
	)
	return err
}

const insertLibraryEntry = `-- name: InsertLibraryEntry :exec
INSERT INTO library.entries (id, owner_subject, kind, name, fields, revision, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 1, $6, $6)
`

type InsertLibraryEntryParams struct {
	ID           uuid.UUID
	OwnerSubject string
	Kind         string
	Name         string
	Fields       []byte
	Now          time.Time
}

func (q *Queries) InsertLibraryEntry(ctx context.Context, arg InsertLibraryEntryParams) error {
	_, err := q.db.Exec(ctx, insertLibraryEntry,
		arg.ID,
		arg.OwnerSubject,
		arg.Kind,
		arg.Name,
		arg.Fields,
		arg.Now,
	)
	return err
}

const insertLibraryRevision = `-- name: InsertLibraryRevision :exec
INSERT INTO library.entry_revisions (entry_id, no, name, fields, author_subject, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLibraryRevisionParams struct {
	EntryID       uuid.UUID
	No            int32
	Name          string
	Fields        []byte
	AuthorSubject string
	Now           time.Time
}

func (q *Queries) InsertLibraryRevision(ctx context.Context, arg InsertLibraryRevisionParams) error {
	_, err := q.db.Exec(ctx, insertLibraryRevision,
		arg.EntryID,
		arg.No,
		arg.Name,
		arg.Fields,
		arg.AuthorSubject,
		arg.Now,
	)
	return err
}

const insertProposal = `-- name: InsertProposal :exec
INSERT INTO library.proposals (id, campaign_id, author_subject, author_name, kind, name, fields, note, base_entry_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending', $10, $10)
`

type InsertProposalParams struct {
	ID            uuid.UUID
	CampaignID    uuid.UUID
	AuthorSubject string
	AuthorName    string
	Kind          string
	Name          string
	Fields        []byte
	Note          string
	BaseEntryID   pgtype.UUID
	Now           time.Time
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) error {
	_, err := q.db.Exec(ctx, insertProposal,
		arg.ID,
		arg.CampaignID,
		arg.AuthorSubject,
		arg.AuthorName,
		arg.Kind,
		arg.Name,
		arg.Fields,
		arg.Note,
		arg.BaseEntryID,
		arg.Now,
	)
	return err
}

const insertProposalReview = `-- name: InsertProposalReview :exec
INSERT INTO library.proposal_reviews (proposal_id, no, action, message, by_name, created_at)
SELECT $1, coalesce(max(no), 0) + 1, $2, $3, $4, $5 FROM library.proposal_reviews WHERE proposal_id = $1
`

type InsertProposalReviewParams struct {
	ProposalID uuid.UUID
	Action     string
	Message    string
	ByName     string
	Now        time.Time
}

func (q *Queries) InsertProposalReview(ctx context.Context, arg InsertProposalReviewParams) error {
	_, err := q.db.Exec(ctx, insertProposalReview,
		arg.ProposalID,
		arg.Action,
		arg.Message,
		arg.ByName,
		arg.Now,
	)
	return err
}

const libraryCollection = `-- name: LibraryCollection :one
SELECT c.id, c.owner_subject, c.name, c.description, c.created_at, c.updated_at,
    ARRAY(SELECT ce.entry_id FROM library.collection_entries ce WHERE ce.collection_id = c.id ORDER BY ce.entry_id)::uuid[] AS entry_ids
FROM library.collections c WHERE c.id = $1
`

type LibraryCollectionRow struct {
	ID           uuid.UUID
	OwnerSubject string
	Name         string
	Description  string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EntryIds     []uuid.UUID
}

func (q *Queries) LibraryCollection(ctx context.Context, id uuid.UUID) (LibraryCollectionRow, error) {
	row := q.db.QueryRow(ctx, libraryCollection, id)
	var i LibraryCollectionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSubject,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EntryIds,
	)
	return i, err
}

const libraryEntries = `-- name: LibraryEntries :many
SELECT id, owner_subject, kind, name, fields, revision, created_at, updated_at FROM library.entries
WHERE owner_subject = $1 AND ($2::text IS NULL OR kind = $2::text)
ORDER BY kind, lower(name), id
`

type LibraryEntriesParams struct {
	OwnerSubject string
	Kind         pgtype.Text
}

func (q *Queries) LibraryEntries(ctx context.Context, arg LibraryEntriesParams) ([]LibraryEntry, error) {
	rows, err := q.db.Query(ctx, libraryEntries, arg.OwnerSubject, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryEntry{}
	for rows.Next() {
		var i LibraryEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSubject,
			&i.Kind,
			&i.Name,
			&i.Fields,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const libraryEntry = `-- name: LibraryEntry :one
SELECT id, owner_subject, kind, name, fields, revision, created_at, updated_at FROM library.entries WHERE id = $1
`

func (q *Queries) LibraryEntry(ctx context.Context, id uuid.UUID) (LibraryEntry, error) {
	row := q.db.QueryRow(ctx, libraryEntry, id)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerSubject,
		&i.Kind,
		&i.Name,
		&i.Fields,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const libraryEntryUses = `-- name: LibraryEntryUses :many
SELECT c.id, c.name, l.pinned_revision FROM campaign.campaigns c
LEFT JOIN library.campaign_links l ON l.campaign_id = c.id AND l.entry_id = $1
WHERE coalesce(l.direct, false) OR EXISTS (
    SELECT 1 FROM library.collection_entries ce JOIN library.campaign_collections cc ON cc.collection_id = ce.collection_id
    WHERE ce.entry_id = $1 AND cc.campaign_id = c.id)
ORDER BY lower(c.name), c.id
`

type LibraryEntryUsesRow struct {
	ID             uuid.UUID
	Name           string
	PinnedRevision pgtype.Int4
}

func (q *Queries) LibraryEntryUses(ctx context.Context, entryID uuid.UUID) ([]LibraryEntryUsesRow, error) {
	rows, err := q.db.Query(ctx, libraryEntryUses, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryEntryUsesRow{}
	for rows.Next() {
		var i LibraryEntryUsesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PinnedRevision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const libraryRevisionExists = `-- name: LibraryRevisionExists :one
SELECT EXISTS (SELECT 1 FROM library.entry_revisions WHERE entry_id = $1 AND no = $2)
`

type LibraryRevisionExistsParams struct {
	EntryID uuid.UUID
	No      int32
}

func (q *Queries) LibraryRevisionExists(ctx context.Context, arg LibraryRevisionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, libraryRevisionExists, arg.EntryID, arg.No)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const libraryRevisions = `-- name: LibraryRevisions :many
SELECT no, name, fields, author_subject, created_at FROM library.entry_revisions WHERE entry_id = $1 ORDER BY no DESC
`

type LibraryRevisionsRow struct {
	No            int32
	Name          string
	Fields        []byte
	AuthorSubject string
	CreatedAt     time.Time
}

func (q *Queries) LibraryRevisions(ctx context.Context, entryID uuid.UUID) ([]LibraryRevisionsRow, error) {
	rows, err := q.db.Query(ctx, libraryRevisions, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryRevisionsRow{}
	for rows.Next() {
		var i LibraryRevisionsRow
		if err := rows.Scan(
			&i.No,
			&i.Name,
			&i.Fields,
			&i.AuthorSubject,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkLibraryEntry = `-- name: LinkLibraryEntry :exec
INSERT INTO library.campaign_links (campaign_id, entry_id, linked_at, updated_at) VALUES ($1, $2, $3, $3)
ON CONFLICT (campaign_id, entry_id) DO UPDATE SET direct = true, updated_at = excluded.updated_at
`

type LinkLibraryEntryParams struct {
	CampaignID uuid.UUID
	EntryID    uuid.UUID
	Now        time.Time
}

func (q *Queries) LinkLibraryEntry(ctx context.Context, arg LinkLibraryEntryParams) error {
	_, err := q.db.Exec(ctx, linkLibraryEntry, arg.CampaignID, arg.EntryID, arg.Now)
	return err
}

const pinLibraryRevision = `-- name: PinLibraryRevision :exec
INSERT INTO library.campaign_links (campaign_id, entry_id, pinned_revision, direct, linked_at, updated_at)
VALUES ($1, $2, $3, false, $4, $4)
ON CONFLICT (campaign_id, entry_id) DO UPDATE SET pinned_revision = excluded.pinned_revision, updated_at = excluded.updated_at
`

type PinLibraryRevisionParams struct {
	CampaignID     uuid.UUID
	EntryID        uuid.UUID
	PinnedRevision pgtype.Int4
	Now            time.Time
}

func (q *Queries) PinLibraryRevision(ctx context.Context, arg PinLibraryRevisionParams) error {
	_, err := q.db.Exec(ctx, pinLibraryRevision,
		arg.CampaignID,
		arg.EntryID,
		arg.PinnedRevision,
		arg.Now,
	)
	return err
}

const proposal = `-- name: Proposal :one
SELECT id, campaign_id, author_subject, author_name, kind, name, fields, note, base_entry_id, status, message, entry_id, created_at, updated_at
FROM library.proposals WHERE id = $1
`

func (q *Queries) Proposal(ctx context.Context, id uuid.UUID) (LibraryProposal, error) {
	row := q.db.QueryRow(ctx, proposal, id)
	var i LibraryProposal
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.AuthorSubject,
		&i.AuthorName,
		&i.Kind,
		&i.Name,
		&i.Fields,
		&i.Note,
		&i.BaseEntryID,
		&i.Status,
		&i.Message,
		&i.EntryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const proposalReviews = `-- name: ProposalReviews :many
SELECT no, action, message, by_name, created_at FROM library.proposal_reviews WHERE proposal_id = $1 ORDER BY no
`

type ProposalReviewsRow struct {
	No        int32
	Action    string
	Message   string
	ByName    string
	CreatedAt time.Time
}

func (q *Queries) ProposalReviews(ctx context.Context, proposalID uuid.UUID) ([]ProposalReviewsRow, error) {
	rows, err := q.db.Query(ctx, proposalReviews, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProposalReviewsRow{}
	for rows.Next() {
		var i ProposalReviewsRow
		if err := rows.Scan(
			&i.No,
			&i.Action,
			&i.Message,
			&i.ByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLibraryOverride = `-- name: SetLibraryOverride :exec
INSERT INTO library.campaign_links (campaign_id, entry_id, override, direct, linked_at, updated_at)
VALUES ($1, $2, $3, false, $4, $4)
ON CONFLICT (campaign_id, entry_id) DO UPDATE SET override = excluded.override, updated_at = excluded.updated_at
`

type SetLibraryOverrideParams struct {
	CampaignID uuid.UUID
	EntryID    uuid.UUID
	Override   []byte
	Now        time.Time
}

func (q *Queries) SetLibraryOverride(ctx context.Context, arg SetLibraryOverrideParams) error {
	_, err := q.db.Exec(ctx, setLibraryOverride,
		arg.CampaignID,
		arg.EntryID,
		arg.Override,
		arg.Now,
	)
	return err
}

const switchOffLibraryCollection = `-- name: SwitchOffLibraryCollection :exec
DELETE FROM library.campaign_collections WHERE campaign_id = $1 AND collection_id = $2
`

type SwitchOffLibraryCollectionParams struct {
	CampaignID   uuid.UUID
	CollectionID uuid.UUID
}

func (q *Queries) SwitchOffLibraryCollection(ctx context.Context, arg SwitchOffLibraryCollectionParams) error {
	_, err := q.db.Exec(ctx, switchOffLibraryCollection, arg.CampaignID, arg.CollectionID)
	return err
}

const switchOnLibraryCollection = `-- name: SwitchOnLibraryCollection :exec
INSERT INTO library.campaign_collections (campaign_id, collection_id, switched_at) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type SwitchOnLibraryCollectionParams struct {
	CampaignID   uuid.UUID
	CollectionID uuid.UUID
	Now          time.Time
}

func (q *Queries) SwitchOnLibraryCollection(ctx context.Context, arg SwitchOnLibraryCollectionParams) error {
	_, err := q.db.Exec(ctx, switchOnLibraryCollection, arg.CampaignID, arg.CollectionID, arg.Now)
	return err
}

const unlinkLibraryEntry = `-- name: UnlinkLibraryEntry :execrows
DELETE FROM library.campaign_links WHERE campaign_id = $1 AND entry_id = $2 AND direct
`

type UnlinkLibraryEntryParams struct {
	CampaignID uuid.UUID
	EntryID    uuid.UUID
}

func (q *Queries) UnlinkLibraryEntry(ctx context.Context, arg UnlinkLibraryEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkLibraryEntry, arg.CampaignID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLibraryCollection = `-- name: UpdateLibraryCollection :exec
UPDATE library.collections SET name = $1, description = $2, updated_at = $3 WHERE id = $4
`

type UpdateLibraryCollectionParams struct {
	Name        string
	Description string
	Now         time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateLibraryCollection(ctx context.Context, arg UpdateLibraryCollectionParams) error {
	_, err := q.db.Exec(ctx, updateLibraryCollection,
		arg.Name,
		arg.Description,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateLibraryEntry = `-- name: UpdateLibraryEntry :one
UPDATE library.entries SET name = $1, fields = $2, revision = revision + 1, updated_at = $3 WHERE id = $4 RETURNING revision
`

type UpdateLibraryEntryParams struct {
	Name   string
	Fields []byte
	Now    time.Time
	ID     uuid.UUID
}

func (q *Queries) UpdateLibraryEntry(ctx context.Context, arg UpdateLibraryEntryParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateLibraryEntry,
		arg.Name,
		arg.Fields,
		arg.Now,
		arg.ID,
	)
	var revision int32
	err := row.Scan(&revision)
	return revision, err
}

const updateProposal = `-- name: UpdateProposal :exec
UPDATE library.proposals SET name = $1, fields = $2, note = $3, status = $4, message = $5,
    entry_id = $6, updated_at = $7
WHERE id = $8
`

type UpdateProposalParams struct {
	Name    string
	Fields  []byte
	Note    string
	Status  string
	Message string
	EntryID pgtype.UUID
	Now     time.Time
	ID      uuid.UUID
}

func (q *Queries) UpdateProposal(ctx context.Context, arg UpdateProposalParams) error {
	_, err := q.db.Exec(ctx, updateProposal,
		arg.Name,
		arg.Fields,
		arg.Note,
		arg.Status,
		arg.Message,
		arg.EntryID,
		arg.Now,
		arg.ID,
	)
	return err
}
