// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loot.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const campaignContainerCoins = `-- name: CampaignContainerCoins :many
SELECT k.container_id, k.coin, k.amount
FROM campaign.container_coins k JOIN campaign.containers c ON c.id = k.container_id
WHERE c.campaign_id = $1 ORDER BY k.container_id, k.coin
`

func (q *Queries) CampaignContainerCoins(ctx context.Context, campaignID uuid.UUID) ([]CampaignContainerCoin, error) {
	rows, err := q.db.Query(ctx, campaignContainerCoins, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignContainerCoin{}
	for rows.Next() {
		var i CampaignContainerCoin
		if err := rows.Scan(&i.ContainerID, &i.Coin, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignContainers = `-- name: CampaignContainers :many
SELECT id, kind, character_id, parent_id, label, created_at FROM campaign.containers WHERE campaign_id = $1 ORDER BY created_at, id
`

type CampaignContainersRow struct {
	ID          uuid.UUID
	Kind        string
	CharacterID pgtype.UUID
	ParentID    pgtype.UUID
	Label       string
	CreatedAt   time.Time
}

func (q *Queries) CampaignContainers(ctx context.Context, campaignID uuid.UUID) ([]CampaignContainersRow, error) {
	rows, err := q.db.Query(ctx, campaignContainers, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignContainersRow{}
	for rows.Next() {
		var i CampaignContainersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CharacterID,
			&i.ParentID,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignHasLiveSession = `-- name: CampaignHasLiveSession :one
SELECT EXISTS (SELECT 1 FROM play.sessions WHERE campaign_id = $1 AND status = 'live')::boolean
`

func (q *Queries) CampaignHasLiveSession(ctx context.Context, campaignID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, campaignHasLiveSession, campaignID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const campaignItemInstances = `-- name: CampaignItemInstances :many
SELECT i.id, i.container_id, i.item_slug, i.custom_name, i.quantity, i.charges, i.identified, i.attuned, i.equipped_slot
FROM campaign.item_instances i JOIN campaign.containers c ON c.id = i.container_id
WHERE c.campaign_id = $1 ORDER BY i.container_id, i.created_at, i.id
`

type CampaignItemInstancesRow struct {
	ID           uuid.UUID
	ContainerID  uuid.UUID
	ItemSlug     string
	CustomName   pgtype.Text
	Quantity     int32
	Charges      pgtype.Int4
	Identified   bool
	Attuned      bool
	EquippedSlot pgtype.Text
}

func (q *Queries) CampaignItemInstances(ctx context.Context, campaignID uuid.UUID) ([]CampaignItemInstancesRow, error) {
	rows, err := q.db.Query(ctx, campaignItemInstances, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignItemInstancesRow{}
	for rows.Next() {
		var i CampaignItemInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContainerID,
			&i.ItemSlug,
			&i.CustomName,
			&i.Quantity,
			&i.Charges,
			&i.Identified,
			&i.Attuned,
			&i.EquippedSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignLootEntries = `-- name: CampaignLootEntries :many
SELECT e.table_id, e.ordering, e.weight, e.kind, e.item_slug, e.coin, e.amount, e.nested_table_id
FROM prep.loot_entries e JOIN prep.loot_tables t ON t.id = e.table_id
WHERE t.campaign_id = $1 ORDER BY e.table_id, e.ordering
`

func (q *Queries) CampaignLootEntries(ctx context.Context, campaignID uuid.UUID) ([]PrepLootEntry, error) {
	rows, err := q.db.Query(ctx, campaignLootEntries, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrepLootEntry{}
	for rows.Next() {
		var i PrepLootEntry
		if err := rows.Scan(
			&i.TableID,
			&i.Ordering,
			&i.Weight,
			&i.Kind,
			&i.ItemSlug,
			&i.Coin,
			&i.Amount,
			&i.NestedTableID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearLootEntries = `-- name: ClearLootEntries :exec
DELETE FROM prep.loot_entries WHERE table_id = $1
`

func (q *Queries) ClearLootEntries(ctx context.Context, tableID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearLootEntries, tableID)
	return err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM campaign.containers WHERE id = $1
`

func (q *Queries) DeleteContainer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContainer, id)
	return err
}

const deleteContainerCoins = `-- name: DeleteContainerCoins :exec
DELETE FROM campaign.container_coins WHERE container_id = $1 AND coin = $2
`

type DeleteContainerCoinsParams struct {
	ContainerID uuid.UUID
	Coin        string
}

func (q *Queries) DeleteContainerCoins(ctx context.Context, arg DeleteContainerCoinsParams) error {
	_, err := q.db.Exec(ctx, deleteContainerCoins, arg.ContainerID, arg.Coin)
	return err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM campaign.item_instances WHERE id = $1
`

func (q *Queries) DeleteInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInstance, id)
	return err
}

const deleteLootTable = `-- name: DeleteLootTable :execrows
DELETE FROM prep.loot_tables WHERE campaign_id = $1 AND id = $2
`

type DeleteLootTableParams struct {
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) DeleteLootTable(ctx context.Context, arg DeleteLootTableParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLootTable, arg.CampaignID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStack = `-- name: DeleteStack :exec
DELETE FROM campaign.item_instances
WHERE container_id = $1 AND item_slug = $2
    AND custom_name IS NULL AND charges IS NULL AND equipped_slot IS NULL AND NOT attuned AND identified
`

type DeleteStackParams struct {
	ContainerID uuid.UUID
	ItemSlug    string
}

func (q *Queries) DeleteStack(ctx context.Context, arg DeleteStackParams) error {
	_, err := q.db.Exec(ctx, deleteStack, arg.ContainerID, arg.ItemSlug)
	return err
}

const getLootTableRevision = `-- name: GetLootTableRevision :one
SELECT r.id, t.name, t.rolls
FROM campaign.revisions r JOIN prep.loot_table_revisions t ON t.revision_id = r.id
WHERE r.campaign_id = $1 AND r.entity_type = 'loot_table' AND r.entity_id = $2 AND r.revision_no = $3
`

type GetLootTableRevisionParams struct {
	CampaignID uuid.UUID
	EntityID   uuid.UUID
	RevisionNo int32
}

type GetLootTableRevisionRow struct {
	ID    uuid.UUID
	Name  string
	Rolls int32
}

func (q *Queries) GetLootTableRevision(ctx context.Context, arg GetLootTableRevisionParams) (GetLootTableRevisionRow, error) {
	row := q.db.QueryRow(ctx, getLootTableRevision, arg.CampaignID, arg.EntityID, arg.RevisionNo)
	var i GetLootTableRevisionRow
	err := row.Scan(&i.ID, &i.Name, &i.Rolls)
	return i, err
}

const healCharacter = `-- name: HealCharacter :exec
UPDATE campaign.characters SET hp_current = LEAST(hp_max, hp_current + $1) WHERE id = $2
`

type HealCharacterParams struct {
	Amount int32
	ID     uuid.UUID
}

func (q *Queries) HealCharacter(ctx context.Context, arg HealCharacterParams) error {
	_, err := q.db.Exec(ctx, healCharacter, arg.Amount, arg.ID)
	return err
}

const identifyInstance = `-- name: IdentifyInstance :exec
UPDATE campaign.item_instances SET identified = true WHERE id = $1
`

func (q *Queries) IdentifyInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, identifyInstance, id)
	return err
}

const insertContainer = `-- name: InsertContainer :exec
INSERT INTO campaign.containers (id, campaign_id, kind, character_id, label, created_at)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING
`

type InsertContainerParams struct {
	ID          uuid.UUID
	CampaignID  uuid.UUID
	Kind        string
	CharacterID pgtype.UUID
	Label       string
	Now         time.Time
}

func (q *Queries) InsertContainer(ctx context.Context, arg InsertContainerParams) error {
	_, err := q.db.Exec(ctx, insertContainer,
		arg.ID,
		arg.CampaignID,
		arg.Kind,
		arg.CharacterID,
		arg.Label,
		arg.Now,
	)
	return err
}

const insertInstance = `-- name: InsertInstance :exec
INSERT INTO campaign.item_instances (id, container_id, item_slug, quantity, identified, attuned, equipped_slot, created_at)
VALUES ($1, $2, $3, 1, true, $4, $5, $6)
`

type InsertInstanceParams struct {
	ID           uuid.UUID
	ContainerID  uuid.UUID
	ItemSlug     string
	Attuned      bool
	EquippedSlot pgtype.Text
	Now          time.Time
}

func (q *Queries) InsertInstance(ctx context.Context, arg InsertInstanceParams) error {
	_, err := q.db.Exec(ctx, insertInstance,
		arg.ID,
		arg.ContainerID,
		arg.ItemSlug,
		arg.Attuned,
		arg.EquippedSlot,
		arg.Now,
	)
	return err
}

const insertItemEvent = `-- name: InsertItemEvent :exec
INSERT INTO play.action_item_events (action_id, position, from_label, to_label, item_slug, coin, count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertItemEventParams struct {
	ActionID  uuid.UUID
	Position  int32
	FromLabel string
	ToLabel   string
	ItemSlug  pgtype.Text
	Coin      pgtype.Text
	Count     int32
}

func (q *Queries) InsertItemEvent(ctx context.Context, arg InsertItemEventParams) error {
	_, err := q.db.Exec(ctx, insertItemEvent,
		arg.ActionID,
		arg.Position,
		arg.FromLabel,
		arg.ToLabel,
		arg.ItemSlug,
		arg.Coin,
		arg.Count,
	)
	return err
}

const insertLootEntry = `-- name: InsertLootEntry :exec
INSERT INTO prep.loot_entries (table_id, ordering, weight, kind, item_slug, coin, amount, nested_table_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLootEntryParams struct {
	TableID       uuid.UUID
	Ordering      int32
	Weight        int32
	Kind          string
	ItemSlug      pgtype.Text
	Coin          pgtype.Text
	Amount        string
	NestedTableID pgtype.UUID
}

func (q *Queries) InsertLootEntry(ctx context.Context, arg InsertLootEntryParams) error {
	_, err := q.db.Exec(ctx, insertLootEntry,
		arg.TableID,
		arg.Ordering,
		arg.Weight,
		arg.Kind,
		arg.ItemSlug,
		arg.Coin,
		arg.Amount,
		arg.NestedTableID,
	)
	return err
}

const insertLootRevisionEntry = `-- name: InsertLootRevisionEntry :exec
INSERT INTO prep.loot_revision_entries (revision_id, ordering, weight, kind, item_slug, coin, amount, nested_table_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLootRevisionEntryParams struct {
	RevisionID    uuid.UUID
	Ordering      int32
	Weight        int32
	Kind          string
	ItemSlug      pgtype.Text
	Coin          pgtype.Text
	Amount        string
	NestedTableID pgtype.UUID
}

func (q *Queries) InsertLootRevisionEntry(ctx context.Context, arg InsertLootRevisionEntryParams) error {
	_, err := q.db.Exec(ctx, insertLootRevisionEntry,
		arg.RevisionID,
		arg.Ordering,
		arg.Weight,
		arg.Kind,
		arg.ItemSlug,
		arg.Coin,
		arg.Amount,
		arg.NestedTableID,
	)
	return err
}

const insertLootTableRevision = `-- name: InsertLootTableRevision :exec
INSERT INTO prep.loot_table_revisions (revision_id, name, rolls) VALUES ($1, $2, $3)
`

type InsertLootTableRevisionParams struct {
	RevisionID uuid.UUID
	Name       string
	Rolls      int32
}

func (q *Queries) InsertLootTableRevision(ctx context.Context, arg InsertLootTableRevisionParams) error {
	_, err := q.db.Exec(ctx, insertLootTableRevision, arg.RevisionID, arg.Name, arg.Rolls)
	return err
}

const inventoryCharacters = `-- name: InventoryCharacters :many
SELECT c.id, c.name, c.owner_member_id, coalesce((SELECT a.base + a.bonus + a.increase FROM campaign.character_abilities a WHERE a.character_id = c.id AND a.ability = 'strength'), 10)::int AS strength,
    coalesce(nullif(ARRAY(SELECT x.class_slug FROM campaign.character_classes x WHERE x.character_id = c.id ORDER BY x.position), '{}'), ARRAY[c.class_slug])::text[] AS classes
FROM campaign.characters c WHERE c.campaign_id = $1 ORDER BY c.name, c.id
`

type InventoryCharactersRow struct {
	ID            uuid.UUID
	Name          string
	OwnerMemberID uuid.UUID
	Strength      int32
	Classes       []string
}

func (q *Queries) InventoryCharacters(ctx context.Context, campaignID uuid.UUID) ([]InventoryCharactersRow, error) {
	rows, err := q.db.Query(ctx, inventoryCharacters, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryCharactersRow{}
	for rows.Next() {
		var i InventoryCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerMemberID,
			&i.Strength,
			&i.Classes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemsBySlug = `-- name: ItemsBySlug :many
SELECT DISTINCT ON (i.slug) i.slug, i.name, i.weight_lb::float8 AS weight_lb, i.category, i.requires_attunement,
    coalesce(i.attunement_detail, '')::text AS attunement_detail,
    coalesce(ch.max_charges, 0)::int AS max_charges, coalesce(ch.regain_dice, 0)::int AS regain_dice,
    coalesce(ch.regain_faces, 0)::int AS regain_faces, coalesce(ch.regain_bonus, 0)::int AS regain_bonus,
    coalesce(ch.recharge_on, '')::text AS recharge_on
FROM compendium.items i
LEFT JOIN compendium.item_charges ch ON ch.item_slug = i.slug
JOIN compendium.documents d ON d.id = i.document_id
WHERE i.slug = ANY($1::text[])
ORDER BY i.slug, (d.key = (SELECT c.ruleset_pref FROM campaign.campaigns c WHERE c.id = $2)) DESC, d.precedence DESC
`

type ItemsBySlugParams struct {
	Slugs      []string
	CampaignID uuid.UUID
}

type ItemsBySlugRow struct {
	Slug               string
	Name               string
	WeightLb           float64
	Category           string
	RequiresAttunement bool
	AttunementDetail   string
	MaxCharges         int32
	RegainDice         int32
	RegainFaces        int32
	RegainBonus        int32
	RechargeOn         string
}

func (q *Queries) ItemsBySlug(ctx context.Context, arg ItemsBySlugParams) ([]ItemsBySlugRow, error) {
	rows, err := q.db.Query(ctx, itemsBySlug, arg.Slugs, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemsBySlugRow{}
	for rows.Next() {
		var i ItemsBySlugRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.WeightLb,
			&i.Category,
			&i.RequiresAttunement,
			&i.AttunementDetail,
			&i.MaxCharges,
			&i.RegainDice,
			&i.RegainFaces,
			&i.RegainBonus,
			&i.RechargeOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLootTables = `-- name: ListLootTables :many
SELECT id, name, rolls, updated_at FROM prep.loot_tables WHERE campaign_id = $1 ORDER BY name, id
`

type ListLootTablesRow struct {
	ID        uuid.UUID
	Name      string
	Rolls     int32
	UpdatedAt time.Time
}

func (q *Queries) ListLootTables(ctx context.Context, campaignID uuid.UUID) ([]ListLootTablesRow, error) {
	rows, err := q.db.Query(ctx, listLootTables, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLootTablesRow{}
	for rows.Next() {
		var i ListLootTablesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rolls,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lootRevisionEntries = `-- name: LootRevisionEntries :many
SELECT ordering, weight, kind, item_slug, coin, amount, nested_table_id FROM prep.loot_revision_entries WHERE revision_id = $1 ORDER BY ordering
`

type LootRevisionEntriesRow struct {
	Ordering      int32
	Weight        int32
	Kind          string
	ItemSlug      pgtype.Text
	Coin          pgtype.Text
	Amount        string
	NestedTableID pgtype.UUID
}

func (q *Queries) LootRevisionEntries(ctx context.Context, revisionID uuid.UUID) ([]LootRevisionEntriesRow, error) {
	rows, err := q.db.Query(ctx, lootRevisionEntries, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LootRevisionEntriesRow{}
	for rows.Next() {
		var i LootRevisionEntriesRow
		if err := rows.Scan(
			&i.Ordering,
			&i.Weight,
			&i.Kind,
			&i.ItemSlug,
			&i.Coin,
			&i.Amount,
			&i.NestedTableID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lootTableInUse = `-- name: LootTableInUse :one
SELECT count(*)::int FROM prep.loot_entries WHERE nested_table_id = $1
`

func (q *Queries) LootTableInUse(ctx context.Context, nestedTableID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lootTableInUse, nestedTableID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const moveInstance = `-- name: MoveInstance :exec
UPDATE campaign.item_instances SET container_id = $1, equipped_slot = NULL WHERE id = $2
`

type MoveInstanceParams struct {
	ContainerID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) MoveInstance(ctx context.Context, arg MoveInstanceParams) error {
	_, err := q.db.Exec(ctx, moveInstance, arg.ContainerID, arg.ID)
	return err
}

const saveLootTable = `-- name: SaveLootTable :exec
INSERT INTO prep.loot_tables (id, campaign_id, name, rolls, updated_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET name = excluded.name, rolls = excluded.rolls, updated_at = excluded.updated_at
`

type SaveLootTableParams struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	Name       string
	Rolls      int32
	Now        time.Time
}

func (q *Queries) SaveLootTable(ctx context.Context, arg SaveLootTableParams) error {
	_, err := q.db.Exec(ctx, saveLootTable,
		arg.ID,
		arg.CampaignID,
		arg.Name,
		arg.Rolls,
		arg.Now,
	)
	return err
}

const setCharacterArmor = `-- name: SetCharacterArmor :exec
UPDATE campaign.characters SET armor_slug = $1, shield = $2 WHERE id = $3
`

type SetCharacterArmorParams struct {
	ArmorSlug pgtype.Text
	Shield    bool
	ID        uuid.UUID
}

func (q *Queries) SetCharacterArmor(ctx context.Context, arg SetCharacterArmorParams) error {
	_, err := q.db.Exec(ctx, setCharacterArmor, arg.ArmorSlug, arg.Shield, arg.ID)
	return err
}

const setContainerCoins = `-- name: SetContainerCoins :exec
INSERT INTO campaign.container_coins (container_id, coin, amount) VALUES ($1, $2, $3)
ON CONFLICT (container_id, coin) DO UPDATE SET amount = excluded.amount
`

type SetContainerCoinsParams struct {
	ContainerID uuid.UUID
	Coin        string
	Amount      int32
}

func (q *Queries) SetContainerCoins(ctx context.Context, arg SetContainerCoinsParams) error {
	_, err := q.db.Exec(ctx, setContainerCoins, arg.ContainerID, arg.Coin, arg.Amount)
	return err
}

const setInstanceAttuned = `-- name: SetInstanceAttuned :exec
UPDATE campaign.item_instances SET attuned = $1 WHERE id = $2
`

type SetInstanceAttunedParams struct {
	Attuned bool
	ID      uuid.UUID
}

func (q *Queries) SetInstanceAttuned(ctx context.Context, arg SetInstanceAttunedParams) error {
	_, err := q.db.Exec(ctx, setInstanceAttuned, arg.Attuned, arg.ID)
	return err
}

const setInstanceCharges = `-- name: SetInstanceCharges :exec
UPDATE campaign.item_instances SET charges = $1 WHERE id = $2
`

type SetInstanceChargesParams struct {
	Charges pgtype.Int4
	ID      uuid.UUID
}

func (q *Queries) SetInstanceCharges(ctx context.Context, arg SetInstanceChargesParams) error {
	_, err := q.db.Exec(ctx, setInstanceCharges, arg.Charges, arg.ID)
	return err
}

const setInstanceSlot = `-- name: SetInstanceSlot :exec
UPDATE campaign.item_instances SET equipped_slot = $1 WHERE id = $2
`

type SetInstanceSlotParams struct {
	EquippedSlot pgtype.Text
	ID           uuid.UUID
}

func (q *Queries) SetInstanceSlot(ctx context.Context, arg SetInstanceSlotParams) error {
	_, err := q.db.Exec(ctx, setInstanceSlot, arg.EquippedSlot, arg.ID)
	return err
}

const setStack = `-- name: SetStack :exec
INSERT INTO campaign.item_instances (id, container_id, item_slug, quantity, identified, attuned, created_at)
VALUES ($1, $2, $3, $4, true, false, $5)
ON CONFLICT (container_id, item_slug) WHERE custom_name IS NULL AND charges IS NULL AND equipped_slot IS NULL AND NOT attuned AND identified
DO UPDATE SET quantity = excluded.quantity
`

type SetStackParams struct {
	ID          uuid.UUID
	ContainerID uuid.UUID
	ItemSlug    string
	Quantity    int32
	Now         time.Time
}

func (q *Queries) SetStack(ctx context.Context, arg SetStackParams) error {
	_, err := q.db.Exec(ctx, setStack,
		arg.ID,
		arg.ContainerID,
		arg.ItemSlug,
		arg.Quantity,
		arg.Now,
	)
	return err
}
