// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maps.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addReveal = `-- name: AddReveal :exec
INSERT INTO campaign.map_reveals (map_id, q, r) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddRevealParams struct {
	MapID uuid.UUID
	Q     int32
	R     int32
}

func (q *Queries) AddReveal(ctx context.Context, arg AddRevealParams) error {
	_, err := q.db.Exec(ctx, addReveal, arg.MapID, arg.Q, arg.R)
	return err
}

const addWall = `-- name: AddWall :exec
INSERT INTO campaign.map_walls (map_id, q, r) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddWallParams struct {
	MapID uuid.UUID
	Q     int32
	R     int32
}

func (q *Queries) AddWall(ctx context.Context, arg AddWallParams) error {
	_, err := q.db.Exec(ctx, addWall, arg.MapID, arg.Q, arg.R)
	return err
}

const deleteEdge = `-- name: DeleteEdge :exec
DELETE FROM campaign.map_edges WHERE map_id = $1 AND id = $2
`

type DeleteEdgeParams struct {
	MapID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteEdge, arg.MapID, arg.ID)
	return err
}

const deleteLight = `-- name: DeleteLight :exec
DELETE FROM campaign.map_lights WHERE map_id = $1 AND id = $2
`

type DeleteLightParams struct {
	MapID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteLight(ctx context.Context, arg DeleteLightParams) error {
	_, err := q.db.Exec(ctx, deleteLight, arg.MapID, arg.ID)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM campaign.map_nodes WHERE map_id = $1 AND id = $2
`

type DeleteNodeParams struct {
	MapID uuid.UUID
	ID    uuid.UUID
}

func (q *Queries) DeleteNode(ctx context.Context, arg DeleteNodeParams) error {
	_, err := q.db.Exec(ctx, deleteNode, arg.MapID, arg.ID)
	return err
}

const getMap = `-- name: GetMap :one
SELECT id, campaign_id, name, image_key, image_type, width_px, height_px, hex_size_px, origin_x, origin_y, ambient, created_at, updated_at, kind
FROM campaign.maps WHERE campaign_id = $1 AND id = $2
`

type GetMapParams struct {
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GetMap(ctx context.Context, arg GetMapParams) (CampaignMap, error) {
	row := q.db.QueryRow(ctx, getMap, arg.CampaignID, arg.ID)
	var i CampaignMap
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageKey,
		&i.ImageType,
		&i.WidthPx,
		&i.HeightPx,
		&i.HexSizePx,
		&i.OriginX,
		&i.OriginY,
		&i.Ambient,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
	)
	return i, err
}

const insertEdge = `-- name: InsertEdge :exec
INSERT INTO campaign.map_edges (id, map_id, from_node_id, to_node_id, distance_mi) VALUES ($1, $2, $3, $4, $5)
`

type InsertEdgeParams struct {
	ID         uuid.UUID
	MapID      uuid.UUID
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
	DistanceMi int32
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) error {
	_, err := q.db.Exec(ctx, insertEdge,
		arg.ID,
		arg.MapID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.DistanceMi,
	)
	return err
}

const insertHexEvent = `-- name: InsertHexEvent :exec
INSERT INTO play.action_hex_events (action_id, q, r) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertHexEventParams struct {
	ActionID uuid.UUID
	Q        int32
	R        int32
}

func (q *Queries) InsertHexEvent(ctx context.Context, arg InsertHexEventParams) error {
	_, err := q.db.Exec(ctx, insertHexEvent, arg.ActionID, arg.Q, arg.R)
	return err
}

const insertLight = `-- name: InsertLight :exec
INSERT INTO campaign.map_lights (id, map_id, q, r, bright_ft, dim_ft) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLightParams struct {
	ID       uuid.UUID
	MapID    uuid.UUID
	Q        int32
	R        int32
	BrightFt int32
	DimFt    int32
}

func (q *Queries) InsertLight(ctx context.Context, arg InsertLightParams) error {
	_, err := q.db.Exec(ctx, insertLight,
		arg.ID,
		arg.MapID,
		arg.Q,
		arg.R,
		arg.BrightFt,
		arg.DimFt,
	)
	return err
}

const insertMap = `-- name: InsertMap :one
INSERT INTO campaign.maps (campaign_id, name, kind, image_key, image_type, width_px, height_px, hex_size_px, origin_x, origin_y, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11)
RETURNING id, campaign_id, name, image_key, image_type, width_px, height_px, hex_size_px, origin_x, origin_y, ambient, created_at, updated_at, kind
`

type InsertMapParams struct {
	CampaignID uuid.UUID
	Name       string
	Kind       string
	ImageKey   string
	ImageType  string
	WidthPx    int32
	HeightPx   int32
	HexSizePx  float64
	OriginX    float64
	OriginY    float64
	Now        time.Time
}

func (q *Queries) InsertMap(ctx context.Context, arg InsertMapParams) (CampaignMap, error) {
	row := q.db.QueryRow(ctx, insertMap,
		arg.CampaignID,
		arg.Name,
		arg.Kind,
		arg.ImageKey,
		arg.ImageType,
		arg.WidthPx,
		arg.HeightPx,
		arg.HexSizePx,
		arg.OriginX,
		arg.OriginY,
		arg.Now,
	)
	var i CampaignMap
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Name,
		&i.ImageKey,
		&i.ImageType,
		&i.WidthPx,
		&i.HeightPx,
		&i.HexSizePx,
		&i.OriginX,
		&i.OriginY,
		&i.Ambient,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO campaign.map_nodes (id, map_id, name, q, r) VALUES ($1, $2, $3, $4, $5)
`

type InsertNodeParams struct {
	ID    uuid.UUID
	MapID uuid.UUID
	Name  string
	Q     int32
	R     int32
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.Exec(ctx, insertNode,
		arg.ID,
		arg.MapID,
		arg.Name,
		arg.Q,
		arg.R,
	)
	return err
}

const insertTravelLeg = `-- name: InsertTravelLeg :exec
INSERT INTO play.travel_legs (action_id, session_id, map_id, from_name, to_name, pace, distance_mi, minutes, days)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertTravelLegParams struct {
	ActionID   uuid.UUID
	SessionID  uuid.UUID
	MapID      uuid.UUID
	FromName   string
	ToName     string
	Pace       string
	DistanceMi int32
	Minutes    int32
	Days       int32
}

func (q *Queries) InsertTravelLeg(ctx context.Context, arg InsertTravelLegParams) error {
	_, err := q.db.Exec(ctx, insertTravelLeg,
		arg.ActionID,
		arg.SessionID,
		arg.MapID,
		arg.FromName,
		arg.ToName,
		arg.Pace,
		arg.DistanceMi,
		arg.Minutes,
		arg.Days,
	)
	return err
}

const listMaps = `-- name: ListMaps :many
SELECT id, campaign_id, name, image_key, image_type, width_px, height_px, hex_size_px, origin_x, origin_y, ambient, created_at, updated_at, kind
FROM campaign.maps WHERE campaign_id = $1 ORDER BY name, id
`

func (q *Queries) ListMaps(ctx context.Context, campaignID uuid.UUID) ([]CampaignMap, error) {
	rows, err := q.db.Query(ctx, listMaps, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignMap{}
	for rows.Next() {
		var i CampaignMap
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Name,
			&i.ImageKey,
			&i.ImageType,
			&i.WidthPx,
			&i.HeightPx,
			&i.HexSizePx,
			&i.OriginX,
			&i.OriginY,
			&i.Ambient,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapEdges = `-- name: MapEdges :many
SELECT id, from_node_id, to_node_id, distance_mi FROM campaign.map_edges WHERE map_id = $1 ORDER BY id
`

type MapEdgesRow struct {
	ID         uuid.UUID
	FromNodeID uuid.UUID
	ToNodeID   uuid.UUID
	DistanceMi int32
}

func (q *Queries) MapEdges(ctx context.Context, mapID uuid.UUID) ([]MapEdgesRow, error) {
	rows, err := q.db.Query(ctx, mapEdges, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapEdgesRow{}
	for rows.Next() {
		var i MapEdgesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.DistanceMi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapLights = `-- name: MapLights :many
SELECT id, q, r, bright_ft, dim_ft FROM campaign.map_lights WHERE map_id = $1 ORDER BY id
`

type MapLightsRow struct {
	ID       uuid.UUID
	Q        int32
	R        int32
	BrightFt int32
	DimFt    int32
}

func (q *Queries) MapLights(ctx context.Context, mapID uuid.UUID) ([]MapLightsRow, error) {
	rows, err := q.db.Query(ctx, mapLights, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapLightsRow{}
	for rows.Next() {
		var i MapLightsRow
		if err := rows.Scan(
			&i.ID,
			&i.Q,
			&i.R,
			&i.BrightFt,
			&i.DimFt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapNodes = `-- name: MapNodes :many
SELECT id, name, q, r FROM campaign.map_nodes WHERE map_id = $1 ORDER BY name, id
`

type MapNodesRow struct {
	ID   uuid.UUID
	Name string
	Q    int32
	R    int32
}

func (q *Queries) MapNodes(ctx context.Context, mapID uuid.UUID) ([]MapNodesRow, error) {
	rows, err := q.db.Query(ctx, mapNodes, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapNodesRow{}
	for rows.Next() {
		var i MapNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Q,
			&i.R,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapParty = `-- name: MapParty :many
SELECT node_id FROM campaign.map_parties WHERE map_id = $1
`

func (q *Queries) MapParty(ctx context.Context, mapID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, mapParty, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var node_id uuid.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapReveals = `-- name: MapReveals :many
SELECT q, r FROM campaign.map_reveals WHERE map_id = $1
`

type MapRevealsRow struct {
	Q int32
	R int32
}

func (q *Queries) MapReveals(ctx context.Context, mapID uuid.UUID) ([]MapRevealsRow, error) {
	rows, err := q.db.Query(ctx, mapReveals, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapRevealsRow{}
	for rows.Next() {
		var i MapRevealsRow
		if err := rows.Scan(&i.Q, &i.R); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapWalls = `-- name: MapWalls :many
SELECT q, r FROM campaign.map_walls WHERE map_id = $1
`

type MapWallsRow struct {
	Q int32
	R int32
}

func (q *Queries) MapWalls(ctx context.Context, mapID uuid.UUID) ([]MapWallsRow, error) {
	rows, err := q.db.Query(ctx, mapWalls, mapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapWallsRow{}
	for rows.Next() {
		var i MapWallsRow
		if err := rows.Scan(&i.Q, &i.R); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReveal = `-- name: RemoveReveal :exec
DELETE FROM campaign.map_reveals WHERE map_id = $1 AND q = $2 AND r = $3
`

type RemoveRevealParams struct {
	MapID uuid.UUID
	Q     int32
	R     int32
}

func (q *Queries) RemoveReveal(ctx context.Context, arg RemoveRevealParams) error {
	_, err := q.db.Exec(ctx, removeReveal, arg.MapID, arg.Q, arg.R)
	return err
}

const removeWall = `-- name: RemoveWall :exec
DELETE FROM campaign.map_walls WHERE map_id = $1 AND q = $2 AND r = $3
`

type RemoveWallParams struct {
	MapID uuid.UUID
	Q     int32
	R     int32
}

func (q *Queries) RemoveWall(ctx context.Context, arg RemoveWallParams) error {
	_, err := q.db.Exec(ctx, removeWall, arg.MapID, arg.Q, arg.R)
	return err
}

const sessionTravelLegs = `-- name: SessionTravelLegs :many
SELECT l.from_name, l.to_name, l.pace, l.distance_mi, l.minutes, l.days
FROM play.travel_legs l JOIN play.actions a ON a.id = l.action_id
WHERE l.session_id = $1 AND l.map_id = $2 ORDER BY a.seq
`

type SessionTravelLegsParams struct {
	SessionID uuid.UUID
	MapID     uuid.UUID
}

type SessionTravelLegsRow struct {
	FromName   string
	ToName     string
	Pace       string
	DistanceMi int32
	Minutes    int32
	Days       int32
}

func (q *Queries) SessionTravelLegs(ctx context.Context, arg SessionTravelLegsParams) ([]SessionTravelLegsRow, error) {
	rows, err := q.db.Query(ctx, sessionTravelLegs, arg.SessionID, arg.MapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionTravelLegsRow{}
	for rows.Next() {
		var i SessionTravelLegsRow
		if err := rows.Scan(
			&i.FromName,
			&i.ToName,
			&i.Pace,
			&i.DistanceMi,
			&i.Minutes,
			&i.Days,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMapAmbient = `-- name: SetMapAmbient :exec
UPDATE campaign.maps SET ambient = $1, updated_at = $2 WHERE id = $3
`

type SetMapAmbientParams struct {
	Ambient string
	Now     time.Time
	ID      uuid.UUID
}

func (q *Queries) SetMapAmbient(ctx context.Context, arg SetMapAmbientParams) error {
	_, err := q.db.Exec(ctx, setMapAmbient, arg.Ambient, arg.Now, arg.ID)
	return err
}

const setMapParty = `-- name: SetMapParty :exec
INSERT INTO campaign.map_parties (map_id, node_id) VALUES ($1, $2)
ON CONFLICT (map_id) DO UPDATE SET node_id = excluded.node_id
`

type SetMapPartyParams struct {
	MapID  uuid.UUID
	NodeID uuid.UUID
}

func (q *Queries) SetMapParty(ctx context.Context, arg SetMapPartyParams) error {
	_, err := q.db.Exec(ctx, setMapParty, arg.MapID, arg.NodeID)
	return err
}

const setSessionMap = `-- name: SetSessionMap :exec
UPDATE play.sessions SET map_id = $1 WHERE id = $2
`

type SetSessionMapParams struct {
	MapID pgtype.UUID
	ID    uuid.UUID
}

func (q *Queries) SetSessionMap(ctx context.Context, arg SetSessionMapParams) error {
	_, err := q.db.Exec(ctx, setSessionMap, arg.MapID, arg.ID)
	return err
}

const setSessionWorld = `-- name: SetSessionWorld :exec
UPDATE play.sessions SET world_map_id = $1 WHERE id = $2
`

type SetSessionWorldParams struct {
	MapID pgtype.UUID
	ID    uuid.UUID
}

func (q *Queries) SetSessionWorld(ctx context.Context, arg SetSessionWorldParams) error {
	_, err := q.db.Exec(ctx, setSessionWorld, arg.MapID, arg.ID)
	return err
}

const updateMap = `-- name: UpdateMap :execrows
UPDATE campaign.maps SET name = $1, hex_size_px = $2, origin_x = $3, origin_y = $4, ambient = $5,
    updated_at = $6
WHERE campaign_id = $7 AND id = $8
`

type UpdateMapParams struct {
	Name       string
	HexSizePx  float64
	OriginX    float64
	OriginY    float64
	Ambient    string
	Now        time.Time
	CampaignID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateMap(ctx context.Context, arg UpdateMapParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMap,
		arg.Name,
		arg.HexSizePx,
		arg.OriginX,
		arg.OriginY,
		arg.Ambient,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
