// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM campaign.push_subscriptions WHERE id = $1 AND subject = $2
`

type DeletePushSubscriptionParams struct {
	ID      uuid.UUID
	Subject string
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, arg.ID, arg.Subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dropPushEndpoint = `-- name: DropPushEndpoint :exec
DELETE FROM campaign.push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DropPushEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, dropPushEndpoint, endpoint)
	return err
}

const pushSubscriptions = `-- name: PushSubscriptions :many
SELECT id, endpoint, p256dh, auth FROM campaign.push_subscriptions WHERE subject = $1 ORDER BY created_at, id
`

type PushSubscriptionsRow struct {
	ID       uuid.UUID
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) PushSubscriptions(ctx context.Context, subject string) ([]PushSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, pushSubscriptions, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscriptionsRow{}
	for rows.Next() {
		var i PushSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO campaign.push_subscriptions (subject, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint) DO UPDATE SET subject = EXCLUDED.subject, p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth
RETURNING id
`

type UpsertPushSubscriptionParams struct {
	Subject  string
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.Subject,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
