// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbilityIDBySlug(ctx context.Context, slug string) (int64, error)
	ActionEffectEvent(ctx context.Context, actionID uuid.UUID) (uuid.UUID, error)
	ActionHPEvent(ctx context.Context, actionID uuid.UUID) (ActionHPEventRow, error)
	ActionHexEvents(ctx context.Context, actionID uuid.UUID) ([]ActionHexEventsRow, error)
	ActionLog(ctx context.Context, arg ActionLogParams) ([]ActionLogRow, error)
	ActionSpawnEvents(ctx context.Context, actionID uuid.UUID) ([]ActionSpawnEventsRow, error)
	ActionTokenEvent(ctx context.Context, actionID uuid.UUID) (ActionTokenEventRow, error)
	AddBackgroundBenefit(ctx context.Context, arg AddBackgroundBenefitParams) error
	AddCharacterSkill(ctx context.Context, arg AddCharacterSkillParams) error
	AddCharacterWeapon(ctx context.Context, arg AddCharacterWeaponParams) error
	AddClassFeature(ctx context.Context, arg AddClassFeatureParams) (int64, error)
	AddClassFeatureLevel(ctx context.Context, arg AddClassFeatureLevelParams) error
	AddClassSave(ctx context.Context, arg AddClassSaveParams) error
	AddFeatBenefit(ctx context.Context, arg AddFeatBenefitParams) error
	AddMember(ctx context.Context, arg AddMemberParams) (CampaignMember, error)
	AddMonsterAction(ctx context.Context, arg AddMonsterActionParams) (int64, error)
	AddMonsterAttack(ctx context.Context, arg AddMonsterAttackParams) error
	AddMonsterRelation(ctx context.Context, arg AddMonsterRelationParams) error
	AddMonsterStat(ctx context.Context, arg AddMonsterStatParams) error
	AddMonsterTrait(ctx context.Context, arg AddMonsterTraitParams) error
	AddRestAgreement(ctx context.Context, arg AddRestAgreementParams) error
	AddRestRester(ctx context.Context, arg AddRestResterParams) error
	AddResumeHex(ctx context.Context, arg AddResumeHexParams) error
	AddReveal(ctx context.Context, arg AddRevealParams) error
	AddSpeciesTrait(ctx context.Context, arg AddSpeciesTraitParams) error
	AddSpellClass(ctx context.Context, arg AddSpellClassParams) error
	AddSpellDamageType(ctx context.Context, arg AddSpellDamageTypeParams) error
	AddSpellScaling(ctx context.Context, arg AddSpellScalingParams) error
	AddWall(ctx context.Context, arg AddWallParams) error
	AddWeaponProperty(ctx context.Context, arg AddWeaponPropertyParams) error
	AddZoneCreature(ctx context.Context, arg AddZoneCreatureParams) error
	BackgroundBenefits(ctx context.Context, backgroundID int64) ([]BackgroundBenefitsRow, error)
	BuilderArmor(ctx context.Context, key string) ([]BuilderArmorRow, error)
	BuilderBackgrounds(ctx context.Context, key string) ([]BuilderBackgroundsRow, error)
	BuilderClasses(ctx context.Context, key string) ([]BuilderClassesRow, error)
	BuilderSpecies(ctx context.Context, key string) ([]BuilderSpeciesRow, error)
	BuilderWeapons(ctx context.Context, key string) ([]BuilderWeaponsRow, error)
	BumpSessionSeq(ctx context.Context, id uuid.UUID) (int64, error)
	CampaignChecks(ctx context.Context, campaignID uuid.UUID) ([]CampaignChecksRow, error)
	CampaignContainerCoins(ctx context.Context, campaignID uuid.UUID) ([]CampaignContainerCoin, error)
	CampaignContainers(ctx context.Context, campaignID uuid.UUID) ([]CampaignContainersRow, error)
	CampaignEntryMonsters(ctx context.Context, campaignID uuid.UUID) ([]PrepEntryMonster, error)
	CampaignHighGround(ctx context.Context, id uuid.UUID) (bool, error)
	CampaignItemInstances(ctx context.Context, campaignID uuid.UUID) ([]CampaignItemInstancesRow, error)
	CampaignLocations(ctx context.Context, campaignID uuid.UUID) ([]CampaignLocationsRow, error)
	CampaignLootEntries(ctx context.Context, campaignID uuid.UUID) ([]PrepLootEntry, error)
	CampaignNode(ctx context.Context, arg CampaignNodeParams) (CampaignNodeRow, error)
	CampaignNpc(ctx context.Context, arg CampaignNpcParams) (string, error)
	CampaignPoolMembers(ctx context.Context, campaignID uuid.UUID) ([]PrepPoolMember, error)
	CampaignReactionTimeout(ctx context.Context, id uuid.UUID) (int32, error)
	CampaignRestSupplies(ctx context.Context, id uuid.UUID) (bool, error)
	CampaignRuleset(ctx context.Context, id uuid.UUID) (string, error)
	CampaignShopStock(ctx context.Context, campaignID uuid.UUID) ([]PrepShopStock, error)
	CampaignShops(ctx context.Context, campaignID uuid.UUID) ([]PrepShop, error)
	CampaignTableEntries(ctx context.Context, campaignID uuid.UUID) ([]PrepTableEntry, error)
	CastHexes(ctx context.Context, castID uuid.UUID) ([]CastHexesRow, error)
	CastTargets(ctx context.Context, castID uuid.UUID) ([]CastTargetsRow, error)
	ChangeResourceUsed(ctx context.Context, arg ChangeResourceUsedParams) error
	CharacterAbilities(ctx context.Context, characterID uuid.UUID) ([]CharacterAbilitiesRow, error)
	CharacterSkills(ctx context.Context, characterID uuid.UUID) ([]CharacterSkillsRow, error)
	CharacterTrade(ctx context.Context, campaignID uuid.UUID) ([]CharacterTradeRow, error)
	CharacterWeapons(ctx context.Context, characterID uuid.UUID) ([]string, error)
	CheckMonsters(ctx context.Context, campaignID uuid.UUID) ([]PrepCheckMonster, error)
	ClassFeatures(ctx context.Context, classID int64) ([]ClassFeaturesRow, error)
	ClassSaves(ctx context.Context, classID int64) ([]string, error)
	ClearAttacks(ctx context.Context, combatID uuid.UUID) error
	ClearBackgroundBenefits(ctx context.Context, backgroundID int64) error
	ClearCasts(ctx context.Context, sessionID uuid.UUID) error
	ClearCharacterWeapons(ctx context.Context, characterID uuid.UUID) error
	ClearClassChildren(ctx context.Context, classID int64) error
	ClearContainerCoins(ctx context.Context, containerID uuid.UUID) error
	ClearEffectComponents(ctx context.Context, effectID int64) error
	ClearEffectScaling(ctx context.Context, effectID int64) error
	ClearEffects(ctx context.Context, sessionID uuid.UUID) error
	ClearElevation(ctx context.Context, arg ClearElevationParams) error
	ClearFeatBenefits(ctx context.Context, featID int64) error
	ClearLootEntries(ctx context.Context, tableID uuid.UUID) error
	ClearManuals(ctx context.Context, sessionID uuid.UUID) error
	ClearMonsterChildren(ctx context.Context, monsterID int64) error
	ClearPendingSaves(ctx context.Context, sessionID uuid.UUID) error
	ClearPoolMembers(ctx context.Context, poolID uuid.UUID) error
	ClearPrompts(ctx context.Context, combatID uuid.UUID) error
	ClearRest(ctx context.Context, sessionID uuid.UUID) error
	ClearRestMembers(ctx context.Context, sessionID uuid.UUID) error
	ClearResumePath(ctx context.Context, combatID uuid.UUID) error
	ClearSessionHaggles(ctx context.Context, sessionID uuid.UUID) error
	ClearSessionShop(ctx context.Context, sessionID uuid.UUID) error
	ClearShopStock(ctx context.Context, shopID uuid.UUID) error
	ClearSpeciesTraits(ctx context.Context, speciesID int64) error
	ClearSpellChildren(ctx context.Context, spellID int64) error
	ClearSurfaces(ctx context.Context, sessionID uuid.UUID) error
	ClearTableEntries(ctx context.Context, tableID uuid.UUID) error
	ClearWeaponProperties(ctx context.Context, weaponID int64) error
	CombatAttack(ctx context.Context, combatID uuid.UUID) (PlayAttack, error)
	CombatCombatants(ctx context.Context, combatID uuid.UUID) ([]PlayCombatant, error)
	CombatPrompt(ctx context.Context, combatID uuid.UUID) (CombatPromptRow, error)
	CompendiumVersion(ctx context.Context) (int64, error)
	ConditionsForDocument(ctx context.Context, documentKey string) ([]ConditionsForDocumentRow, error)
	CountDMs(ctx context.Context, campaignID uuid.UUID) (int32, error)
	CountEntriesByKind(ctx context.Context, arg CountEntriesByKindParams) ([]CountEntriesByKindRow, error)
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error)
	DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error
	DeleteContainer(ctx context.Context, id uuid.UUID) error
	DeleteContainerCoins(ctx context.Context, arg DeleteContainerCoinsParams) error
	DeleteDying(ctx context.Context, tokenID uuid.UUID) error
	DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error
	DeleteEncounterTable(ctx context.Context, arg DeleteEncounterTableParams) (int64, error)
	DeleteLight(ctx context.Context, arg DeleteLightParams) error
	DeleteLootTable(ctx context.Context, arg DeleteLootTableParams) (int64, error)
	DeleteNPC(ctx context.Context, arg DeleteNPCParams) (int64, error)
	DeleteNode(ctx context.Context, arg DeleteNodeParams) error
	DeletePendingAction(ctx context.Context, rollID uuid.UUID) error
	DeletePool(ctx context.Context, arg DeletePoolParams) (int64, error)
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error)
	DeleteScheduledCheck(ctx context.Context, id uuid.UUID) error
	DeleteSettlement(ctx context.Context, arg DeleteSettlementParams) (int64, error)
	DeleteShop(ctx context.Context, arg DeleteShopParams) (int64, error)
	DeleteShopStock(ctx context.Context, arg DeleteShopStockParams) error
	DeleteStack(ctx context.Context, arg DeleteStackParams) error
	DeleteToken(ctx context.Context, arg DeleteTokenParams) error
	DeleteTokenForm(ctx context.Context, tokenID uuid.UUID) error
	DeleteZone(ctx context.Context, arg DeleteZoneParams) error
	DeletedNPCs(ctx context.Context, campaignID uuid.UUID) ([]DeletedNPCsRow, error)
	DropPushEndpoint(ctx context.Context, endpoint string) error
	Edits(ctx context.Context, arg EditsParams) ([]EditsRow, error)
	EndSession(ctx context.Context, arg EndSessionParams) (int64, error)
	FeatBenefits(ctx context.Context, featID int64) ([]string, error)
	FindEntry(ctx context.Context, arg FindEntryParams) (FindEntryRow, error)
	FindInvite(ctx context.Context, arg FindInviteParams) (FindInviteRow, error)
	GameDay(ctx context.Context, id uuid.UUID) (int32, error)
	GetArmorDetail(ctx context.Context, id int64) (GetArmorDetailRow, error)
	GetBackgroundDetail(ctx context.Context, id int64) (string, error)
	GetCampaign(ctx context.Context, id uuid.UUID) (GetCampaignRow, error)
	GetCharacter(ctx context.Context, arg GetCharacterParams) (GetCharacterRow, error)
	GetClassDetail(ctx context.Context, id int64) (GetClassDetailRow, error)
	GetConditionDetail(ctx context.Context, id int64) (string, error)
	GetFeatDetail(ctx context.Context, id int64) (GetFeatDetailRow, error)
	GetInstanceCreatedAt(ctx context.Context) (time.Time, error)
	GetItemDetail(ctx context.Context, id int64) (GetItemDetailRow, error)
	GetLootTableRevision(ctx context.Context, arg GetLootTableRevisionParams) (GetLootTableRevisionRow, error)
	GetMap(ctx context.Context, arg GetMapParams) (CampaignMap, error)
	GetMember(ctx context.Context, arg GetMemberParams) (CampaignMember, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (CampaignMember, error)
	GetMonsterDetail(ctx context.Context, id int64) (GetMonsterDetailRow, error)
	GetNPC(ctx context.Context, arg GetNPCParams) (GetNPCRow, error)
	GetNPCRevision(ctx context.Context, arg GetNPCRevisionParams) (GetNPCRevisionRow, error)
	GetPoolRevision(ctx context.Context, arg GetPoolRevisionParams) (GetPoolRevisionRow, error)
	GetRest(ctx context.Context, sessionID uuid.UUID) (GetRestRow, error)
	GetRoll(ctx context.Context, arg GetRollParams) (PlayRollRequest, error)
	GetSession(ctx context.Context, arg GetSessionParams) (PlaySession, error)
	GetSettlementRevision(ctx context.Context, arg GetSettlementRevisionParams) (GetSettlementRevisionRow, error)
	GetShopRevision(ctx context.Context, arg GetShopRevisionParams) (GetShopRevisionRow, error)
	GetSpeciesDetail(ctx context.Context, id int64) (GetSpeciesDetailRow, error)
	GetSpell(ctx context.Context, arg GetSpellParams) (GetSpellRow, error)
	GetTableRevision(ctx context.Context, arg GetTableRevisionParams) (GetTableRevisionRow, error)
	GetWeaponDetail(ctx context.Context, id int64) (GetWeaponDetailRow, error)
	InsertAction(ctx context.Context, arg InsertActionParams) (uuid.UUID, error)
	InsertCast(ctx context.Context, arg InsertCastParams) error
	InsertCastHex(ctx context.Context, arg InsertCastHexParams) error
	InsertCastTarget(ctx context.Context, arg InsertCastTargetParams) error
	InsertCharacter(ctx context.Context, arg InsertCharacterParams) (uuid.UUID, error)
	InsertCheckMonster(ctx context.Context, arg InsertCheckMonsterParams) error
	InsertContainer(ctx context.Context, arg InsertContainerParams) error
	InsertEdge(ctx context.Context, arg InsertEdgeParams) error
	InsertEffect(ctx context.Context, arg InsertEffectParams) error
	InsertEffectArea(ctx context.Context, arg InsertEffectAreaParams) error
	InsertEffectBonusDie(ctx context.Context, arg InsertEffectBonusDieParams) error
	InsertEffectBranch(ctx context.Context, arg InsertEffectBranchParams) error
	InsertEffectComponent(ctx context.Context, arg InsertEffectComponentParams) error
	InsertEffectCounter(ctx context.Context, arg InsertEffectCounterParams) error
	InsertEffectCrit(ctx context.Context, arg InsertEffectCritParams) error
	InsertEffectEdge(ctx context.Context, arg InsertEffectEdgeParams) error
	InsertEffectEvent(ctx context.Context, arg InsertEffectEventParams) error
	InsertEffectExhaustion(ctx context.Context, arg InsertEffectExhaustionParams) error
	InsertEffectExtraDamage(ctx context.Context, arg InsertEffectExtraDamageParams) error
	InsertEffectForcedMove(ctx context.Context, arg InsertEffectForcedMoveParams) error
	InsertEffectForm(ctx context.Context, arg InsertEffectFormParams) error
	InsertEffectGrant(ctx context.Context, arg InsertEffectGrantParams) error
	InsertEffectManual(ctx context.Context, arg InsertEffectManualParams) error
	InsertEffectMode(ctx context.Context, arg InsertEffectModeParams) error
	InsertEffectMoveCost(ctx context.Context, arg InsertEffectMoveCostParams) error
	InsertEffectReaction(ctx context.Context, arg InsertEffectReactionParams) error
	InsertEffectResourceChange(ctx context.Context, arg InsertEffectResourceChangeParams) error
	InsertEffectSaveCondition(ctx context.Context, arg InsertEffectSaveConditionParams) error
	InsertEffectSaveDamage(ctx context.Context, arg InsertEffectSaveDamageParams) error
	InsertEffectSaveEdge(ctx context.Context, arg InsertEffectSaveEdgeParams) error
	InsertEffectScaling(ctx context.Context, arg InsertEffectScalingParams) error
	InsertEffectScalingStep(ctx context.Context, arg InsertEffectScalingStepParams) error
	InsertEffectSpeedPenalty(ctx context.Context, arg InsertEffectSpeedPenaltyParams) error
	InsertEffectSummon(ctx context.Context, arg InsertEffectSummonParams) error
	InsertEffectSurface(ctx context.Context, arg InsertEffectSurfaceParams) error
	InsertEffectTeleport(ctx context.Context, arg InsertEffectTeleportParams) error
	InsertEffectTempHP(ctx context.Context, arg InsertEffectTempHPParams) error
	InsertEntryMonster(ctx context.Context, arg InsertEntryMonsterParams) error
	InsertHPEvent(ctx context.Context, arg InsertHPEventParams) error
	InsertHexEvent(ctx context.Context, arg InsertHexEventParams) error
	InsertItemEvent(ctx context.Context, arg InsertItemEventParams) error
	InsertLight(ctx context.Context, arg InsertLightParams) error
	InsertLootEntry(ctx context.Context, arg InsertLootEntryParams) error
	InsertLootRevisionEntry(ctx context.Context, arg InsertLootRevisionEntryParams) error
	InsertLootTableRevision(ctx context.Context, arg InsertLootTableRevisionParams) error
	InsertManual(ctx context.Context, arg InsertManualParams) error
	InsertMap(ctx context.Context, arg InsertMapParams) (CampaignMap, error)
	InsertNPC(ctx context.Context, arg InsertNPCParams) (uuid.UUID, error)
	InsertNPCRevision(ctx context.Context, arg InsertNPCRevisionParams) error
	InsertNode(ctx context.Context, arg InsertNodeParams) error
	InsertPendingAction(ctx context.Context, arg InsertPendingActionParams) error
	InsertPendingSave(ctx context.Context, arg InsertPendingSaveParams) error
	InsertPoolMember(ctx context.Context, arg InsertPoolMemberParams) error
	InsertPoolRevision(ctx context.Context, arg InsertPoolRevisionParams) error
	InsertPoolRevisionMember(ctx context.Context, arg InsertPoolRevisionMemberParams) error
	InsertRevision(ctx context.Context, arg InsertRevisionParams) (uuid.UUID, error)
	InsertRoll(ctx context.Context, arg InsertRollParams) (uuid.UUID, error)
	InsertRollDie(ctx context.Context, arg InsertRollDieParams) error
	InsertRollEvent(ctx context.Context, arg InsertRollEventParams) error
	InsertRollLabel(ctx context.Context, arg InsertRollLabelParams) error
	InsertRollModifier(ctx context.Context, arg InsertRollModifierParams) error
	InsertScheduledCheck(ctx context.Context, arg InsertScheduledCheckParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) (PlaySession, error)
	InsertSessionAction(ctx context.Context, arg InsertSessionActionParams) (uuid.UUID, error)
	InsertSettlementRevision(ctx context.Context, arg InsertSettlementRevisionParams) error
	InsertShopRevision(ctx context.Context, arg InsertShopRevisionParams) error
	InsertShopRevisionStock(ctx context.Context, arg InsertShopRevisionStockParams) error
	InsertSpawnEvent(ctx context.Context, arg InsertSpawnEventParams) error
	InsertSurface(ctx context.Context, arg InsertSurfaceParams) error
	InsertTableEntry(ctx context.Context, arg InsertTableEntryParams) error
	InsertTableRevision(ctx context.Context, arg InsertTableRevisionParams) error
	InsertTableRevisionEntry(ctx context.Context, arg InsertTableRevisionEntryParams) error
	InsertTableRevisionMonster(ctx context.Context, arg InsertTableRevisionMonsterParams) error
	InsertToken(ctx context.Context, arg InsertTokenParams) error
	InsertTokenAttack(ctx context.Context, arg InsertTokenAttackParams) error
	InsertTokenEvent(ctx context.Context, arg InsertTokenEventParams) error
	InsertTokenSave(ctx context.Context, arg InsertTokenSaveParams) error
	InsertTravelLeg(ctx context.Context, arg InsertTravelLegParams) error
	InsertUndo(ctx context.Context, arg InsertUndoParams) error
	InventoryCharacters(ctx context.Context, campaignID uuid.UUID) ([]InventoryCharactersRow, error)
	ItemPrices(ctx context.Context, arg ItemPricesParams) ([]ItemPricesRow, error)
	ItemsBySlug(ctx context.Context, arg ItemsBySlugParams) ([]ItemsBySlugRow, error)
	LastDamage(ctx context.Context, sessionID pgtype.UUID) (LastDamageRow, error)
	LatestSnapshotHash(ctx context.Context) (string, error)
	ListCampaignsForSubject(ctx context.Context, arg ListCampaignsForSubjectParams) ([]ListCampaignsForSubjectRow, error)
	ListCharacters(ctx context.Context, campaignID uuid.UUID) ([]ListCharactersRow, error)
	ListChoices(ctx context.Context) ([]ListChoicesRow, error)
	ListEffectAreas(ctx context.Context) ([]ListEffectAreasRow, error)
	ListEffectBonusDice(ctx context.Context) ([]ListEffectBonusDiceRow, error)
	ListEffectBranches(ctx context.Context) ([]ListEffectBranchesRow, error)
	ListEffectComponents(ctx context.Context) ([]CompendiumEffectComponent, error)
	ListEffectCounters(ctx context.Context) ([]ListEffectCountersRow, error)
	ListEffectCrits(ctx context.Context) ([]ListEffectCritsRow, error)
	ListEffectDefinitions(ctx context.Context) ([]ListEffectDefinitionsRow, error)
	ListEffectEdges(ctx context.Context) ([]ListEffectEdgesRow, error)
	ListEffectExhaustion(ctx context.Context) ([]ListEffectExhaustionRow, error)
	ListEffectExtraDamage(ctx context.Context) ([]ListEffectExtraDamageRow, error)
	ListEffectForcedMoves(ctx context.Context) ([]ListEffectForcedMovesRow, error)
	ListEffectForms(ctx context.Context) ([]ListEffectFormsRow, error)
	ListEffectGrants(ctx context.Context) ([]ListEffectGrantsRow, error)
	ListEffectManual(ctx context.Context) ([]ListEffectManualRow, error)
	ListEffectModes(ctx context.Context) ([]ListEffectModesRow, error)
	ListEffectMoveCosts(ctx context.Context) ([]ListEffectMoveCostsRow, error)
	ListEffectReactions(ctx context.Context) ([]ListEffectReactionsRow, error)
	ListEffectResourceChanges(ctx context.Context) ([]ListEffectResourceChangesRow, error)
	ListEffectSaveConditions(ctx context.Context) ([]ListEffectSaveConditionsRow, error)
	ListEffectSaveDamage(ctx context.Context) ([]ListEffectSaveDamageRow, error)
	ListEffectSaveEdges(ctx context.Context) ([]ListEffectSaveEdgesRow, error)
	ListEffectScalingSteps(ctx context.Context) ([]CompendiumEffectScalingStep, error)
	ListEffectScalings(ctx context.Context) ([]CompendiumEffectScaling, error)
	ListEffectSpeedPenalties(ctx context.Context) ([]ListEffectSpeedPenaltiesRow, error)
	ListEffectSummons(ctx context.Context) ([]ListEffectSummonsRow, error)
	ListEffectSurfaces(ctx context.Context) ([]ListEffectSurfacesRow, error)
	ListEffectTeleports(ctx context.Context) ([]ListEffectTeleportsRow, error)
	ListEffectTempHPs(ctx context.Context) ([]ListEffectTempHPsRow, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error)
	ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error)
	ListLootTables(ctx context.Context, campaignID uuid.UUID) ([]ListLootTablesRow, error)
	ListMaps(ctx context.Context, campaignID uuid.UUID) ([]CampaignMap, error)
	ListMembers(ctx context.Context, campaignID uuid.UUID) ([]CampaignMember, error)
	ListNPCs(ctx context.Context, campaignID uuid.UUID) ([]ListNPCsRow, error)
	ListPools(ctx context.Context, campaignID uuid.UUID) ([]ListPoolsRow, error)
	ListPrerequisites(ctx context.Context) ([]CompendiumPrerequisite, error)
	ListResourceDice(ctx context.Context) ([]CompendiumResourceDice, error)
	ListResourceMaxima(ctx context.Context) ([]CompendiumResourceMaxima, error)
	ListResourceRecharges(ctx context.Context) ([]CompendiumResourceRecharge, error)
	ListResources(ctx context.Context) ([]CompendiumResource, error)
	ListRestAgreements(ctx context.Context, sessionID uuid.UUID) ([]uuid.UUID, error)
	ListRestResters(ctx context.Context, sessionID uuid.UUID) ([]ListRestRestersRow, error)
	ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ListRevisionsRow, error)
	ListRolls(ctx context.Context, arg ListRollsParams) ([]uuid.UUID, error)
	ListScaleSteps(ctx context.Context) ([]CompendiumScaleStep, error)
	ListScales(ctx context.Context) ([]CompendiumScale, error)
	ListSessions(ctx context.Context, campaignID uuid.UUID) ([]PlaySession, error)
	ListSettlements(ctx context.Context, campaignID uuid.UUID) ([]ListSettlementsRow, error)
	ListSources(ctx context.Context) ([]ListSourcesRow, error)
	ListSpells(ctx context.Context, arg ListSpellsParams) ([]ListSpellsRow, error)
	ListTables(ctx context.Context, campaignID uuid.UUID) ([]ListTablesRow, error)
	LockCampaign(ctx context.Context, id uuid.UUID) error
	LockCampaignLog(ctx context.Context, lockKey string) error
	LockEntity(ctx context.Context, lockKey string) error
	LockRoll(ctx context.Context, arg LockRollParams) (string, error)
	LockSessionOwner(ctx context.Context, lockKey string) (bool, error)
	LootRevisionEntries(ctx context.Context, revisionID uuid.UUID) ([]LootRevisionEntriesRow, error)
	LootTableInUse(ctx context.Context, nestedTableID pgtype.UUID) (int32, error)
	MapEdges(ctx context.Context, mapID uuid.UUID) ([]MapEdgesRow, error)
	MapElevations(ctx context.Context, mapID uuid.UUID) ([]MapElevationsRow, error)
	MapLights(ctx context.Context, mapID uuid.UUID) ([]MapLightsRow, error)
	MapNodes(ctx context.Context, mapID uuid.UUID) ([]MapNodesRow, error)
	MapParty(ctx context.Context, mapID uuid.UUID) ([]uuid.UUID, error)
	MapReveals(ctx context.Context, mapID uuid.UUID) ([]MapRevealsRow, error)
	MapWalls(ctx context.Context, mapID uuid.UUID) ([]MapWallsRow, error)
	MonsterActions(ctx context.Context, monsterID int64) ([]MonsterActionsRow, error)
	MonsterAmbushStats(ctx context.Context, monsterID int64) ([]MonsterAmbushStatsRow, error)
	MonsterAttackRows(ctx context.Context, monsterID int64) ([]MonsterAttackRowsRow, error)
	MonsterRelations(ctx context.Context, monsterID int64) ([]MonsterRelationsRow, error)
	MonsterSaves(ctx context.Context, monsterID int64) ([]MonsterSavesRow, error)
	MonsterStatblock(ctx context.Context, arg MonsterStatblockParams) (MonsterStatblockRow, error)
	MonsterStats(ctx context.Context, monsterID int64) ([]MonsterStatsRow, error)
	MonsterTraits(ctx context.Context, monsterID int64) ([]MonsterTraitsRow, error)
	MonsterXP(ctx context.Context, arg MonsterXPParams) (MonsterXPRow, error)
	MoveInstance(ctx context.Context, arg MoveInstanceParams) error
	NextActionSeq(ctx context.Context, campaignID uuid.UUID) (int32, error)
	NextRevisionNo(ctx context.Context, arg NextRevisionNoParams) (int32, error)
	NextSessionNumber(ctx context.Context, campaignID uuid.UUID) (int32, error)
	ObserveDamage(ctx context.Context, arg ObserveDamageParams) error
	PartyLevels(ctx context.Context, campaignID uuid.UUID) ([]int32, error)
	PoolInUse(ctx context.Context, poolID pgtype.UUID) (int32, error)
	PoolRevisionMembers(ctx context.Context, revisionID uuid.UUID) ([]PoolRevisionMembersRow, error)
	PushSubscriptions(ctx context.Context, subject string) ([]PushSubscriptionsRow, error)
	RecordCompendiumImport(ctx context.Context, snapshotHash string) (int64, error)
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	RemoveReveal(ctx context.Context, arg RemoveRevealParams) error
	RemoveWall(ctx context.Context, arg RemoveWallParams) error
	ResolveRoll(ctx context.Context, arg ResolveRollParams) error
	RestAbilities(ctx context.Context, ids []uuid.UUID) ([]RestAbilitiesRow, error)
	RestCharacters(ctx context.Context, arg RestCharactersParams) ([]RestCharactersRow, error)
	RestResourcesUsed(ctx context.Context, ids []uuid.UUID) ([]CampaignCharacterResource, error)
	ResumePath(ctx context.Context, combatID uuid.UUID) ([]ResumePathRow, error)
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error)
	RollDice(ctx context.Context, rollID uuid.UUID) ([]RollDiceRow, error)
	RollLabels(ctx context.Context, rollID uuid.UUID) ([]RollLabelsRow, error)
	RollModifiers(ctx context.Context, rollID uuid.UUID) ([]RollModifiersRow, error)
	RulesetYear(ctx context.Context, key string) (int32, error)
	RunningCombat(ctx context.Context, sessionID uuid.UUID) (PlayCombat, error)
	SaveAttack(ctx context.Context, arg SaveAttackParams) error
	SaveCombat(ctx context.Context, arg SaveCombatParams) error
	SaveCombatant(ctx context.Context, arg SaveCombatantParams) error
	SaveDying(ctx context.Context, arg SaveDyingParams) error
	SaveEncounterCheck(ctx context.Context, arg SaveEncounterCheckParams) error
	SaveEncounterTable(ctx context.Context, arg SaveEncounterTableParams) error
	SaveHaggle(ctx context.Context, arg SaveHaggleParams) error
	SaveLootTable(ctx context.Context, arg SaveLootTableParams) error
	SavePool(ctx context.Context, arg SavePoolParams) error
	SavePrompt(ctx context.Context, arg SavePromptParams) error
	SaveRest(ctx context.Context, arg SaveRestParams) error
	SaveRestResult(ctx context.Context, arg SaveRestResultParams) error
	SaveSettlement(ctx context.Context, arg SaveSettlementParams) error
	SaveShop(ctx context.Context, arg SaveShopParams) error
	SaveTable(ctx context.Context, arg SaveTableParams) error
	SaveTokenForm(ctx context.Context, arg SaveTokenFormParams) error
	SaveZone(ctx context.Context, arg SaveZoneParams) error
	SaveZoneCheck(ctx context.Context, arg SaveZoneCheckParams) error
	ScheduledChecks(ctx context.Context, campaignID uuid.UUID) ([]ScheduledChecksRow, error)
	SessionActionBySeq(ctx context.Context, arg SessionActionBySeqParams) (SessionActionBySeqRow, error)
	SessionByID(ctx context.Context, id uuid.UUID) (PlaySession, error)
	SessionCast(ctx context.Context, sessionID uuid.UUID) (SessionCastRow, error)
	SessionChecks(ctx context.Context, sessionID pgtype.UUID) ([]SessionChecksRow, error)
	SessionDying(ctx context.Context, sessionID uuid.UUID) ([]SessionDyingRow, error)
	SessionEffects(ctx context.Context, sessionID uuid.UUID) ([]SessionEffectsRow, error)
	SessionHaggles(ctx context.Context, sessionID uuid.UUID) ([]SessionHagglesRow, error)
	SessionLog(ctx context.Context, arg SessionLogParams) ([]SessionLogRow, error)
	SessionManuals(ctx context.Context, sessionID uuid.UUID) ([]SessionManualsRow, error)
	SessionObservations(ctx context.Context, sessionID uuid.UUID) ([]PlayObservedDamage, error)
	SessionPendingActions(ctx context.Context, sessionID uuid.UUID) ([]SessionPendingActionsRow, error)
	SessionPendingSaves(ctx context.Context, sessionID uuid.UUID) ([]SessionPendingSavesRow, error)
	SessionShop(ctx context.Context, sessionID uuid.UUID) ([]uuid.UUID, error)
	SessionSurfaces(ctx context.Context, sessionID uuid.UUID) ([]SessionSurfacesRow, error)
	SessionTable(ctx context.Context, sessionID uuid.UUID) (SessionTableRow, error)
	SessionTokenAttacks(ctx context.Context, sessionID uuid.UUID) ([]PlayTokenAttack, error)
	SessionTokenForms(ctx context.Context, sessionID uuid.UUID) ([]PlayTokenForm, error)
	SessionTokenReactions(ctx context.Context, sessionID uuid.UUID) ([]PlayTokenReaction, error)
	SessionTokenSaves(ctx context.Context, sessionID uuid.UUID) ([]PlayTokenSafe, error)
	SessionTokens(ctx context.Context, sessionID uuid.UUID) ([]SessionTokensRow, error)
	SessionTravelLegs(ctx context.Context, arg SessionTravelLegsParams) ([]SessionTravelLegsRow, error)
	SessionZoneChecks(ctx context.Context, sessionID uuid.UUID) ([]PlayZoneCheck, error)
	SessionZoneCreatures(ctx context.Context, sessionID uuid.UUID) ([]PlayZoneCreature, error)
	SessionZones(ctx context.Context, sessionID uuid.UUID) ([]SessionZonesRow, error)
	SetCharacterAbility(ctx context.Context, arg SetCharacterAbilityParams) error
	SetCharacterPortrait(ctx context.Context, arg SetCharacterPortraitParams) error
	SetCharacterToken(ctx context.Context, arg SetCharacterTokenParams) error
	SetContainerCoins(ctx context.Context, arg SetContainerCoinsParams) error
	SetElevation(ctx context.Context, arg SetElevationParams) error
	SetGameDay(ctx context.Context, arg SetGameDayParams) error
	SetMapAmbient(ctx context.Context, arg SetMapAmbientParams) error
	SetMapParty(ctx context.Context, arg SetMapPartyParams) error
	SetMemberRole(ctx context.Context, arg SetMemberRoleParams) error
	SetResourceUsed(ctx context.Context, arg SetResourceUsedParams) error
	SetRollDie(ctx context.Context, arg SetRollDieParams) (int64, error)
	SetSessionMap(ctx context.Context, arg SetSessionMapParams) error
	SetSessionShop(ctx context.Context, arg SetSessionShopParams) error
	SetSessionWorld(ctx context.Context, arg SetSessionWorldParams) error
	SetShopStock(ctx context.Context, arg SetShopStockParams) error
	SetShopStockedDay(ctx context.Context, arg SetShopStockedDayParams) error
	SetStack(ctx context.Context, arg SetStackParams) error
	SetTokenHP(ctx context.Context, arg SetTokenHPParams) error
	SetTokenReaction(ctx context.Context, arg SetTokenReactionParams) error
	SetTokenTactics(ctx context.Context, arg SetTokenTacticsParams) error
	SetTokenTempHP(ctx context.Context, arg SetTokenTempHPParams) error
	ShopRevisionStock(ctx context.Context, revisionID uuid.UUID) ([]ShopRevisionStockRow, error)
	SpeciesTraits(ctx context.Context, speciesID int64) ([]SpeciesTraitsRow, error)
	SpellClasses(ctx context.Context, spellID int64) ([]string, error)
	SpellDamageTypes(ctx context.Context, spellID int64) ([]string, error)
	SpellScaling(ctx context.Context, spellID int64) ([]SpellScalingRow, error)
	SpendHitDie(ctx context.Context, id uuid.UUID) error
	TableRevisionEntries(ctx context.Context, revisionID uuid.UUID) ([]TableRevisionEntriesRow, error)
	TableRevisionMonsters(ctx context.Context, revisionID uuid.UUID) ([]TableRevisionMonstersRow, error)
	UnlockSessionOwner(ctx context.Context, lockKey string) (bool, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (UpdateCampaignRow, error)
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) error
	UpdateMap(ctx context.Context, arg UpdateMapParams) (int64, error)
	UpdateNPC(ctx context.Context, arg UpdateNPCParams) (int64, error)
	UpdateToken(ctx context.Context, arg UpdateTokenParams) error
	UpsertArmor(ctx context.Context, arg UpsertArmorParams) error
	UpsertBackground(ctx context.Context, arg UpsertBackgroundParams) (int64, error)
	UpsertClass(ctx context.Context, arg UpsertClassParams) (int64, error)
	UpsertCondition(ctx context.Context, arg UpsertConditionParams) error
	UpsertDamageType(ctx context.Context, arg UpsertDamageTypeParams) (int64, error)
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error)
	UpsertEffectDefinition(ctx context.Context, arg UpsertEffectDefinitionParams) (int64, error)
	UpsertFeat(ctx context.Context, arg UpsertFeatParams) (int64, error)
	UpsertItem(ctx context.Context, arg UpsertItemParams) error
	UpsertMagicSchool(ctx context.Context, arg UpsertMagicSchoolParams) (int64, error)
	UpsertMonster(ctx context.Context, arg UpsertMonsterParams) (int64, error)
	UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (uuid.UUID, error)
	UpsertSpecies(ctx context.Context, arg UpsertSpeciesParams) (int64, error)
	UpsertSpell(ctx context.Context, arg UpsertSpellParams) (int64, error)
	UpsertWeapon(ctx context.Context, arg UpsertWeaponParams) (int64, error)
	WeaponProperties(ctx context.Context, weaponID int64) ([]WeaponPropertiesRow, error)
}

var _ Querier = (*Queries)(nil)
