// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retrains.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const characterRevisions = `-- name: CharacterRevisions :many
SELECT r.revision_no, r.caller_name, r.created_at, cr.snapshot_id, cr.retrain_id
FROM campaign.revisions r JOIN campaign.character_revisions cr ON cr.revision_id = r.id
WHERE r.campaign_id = $1 AND r.entity_type = 'character' AND r.entity_id = $2
ORDER BY r.revision_no DESC
`

type CharacterRevisionsParams struct {
	CampaignID uuid.UUID
	EntityID   uuid.UUID
}

type CharacterRevisionsRow struct {
	RevisionNo int32
	CallerName string
	CreatedAt  time.Time
	SnapshotID uuid.UUID
	RetrainID  pgtype.UUID
}

func (q *Queries) CharacterRevisions(ctx context.Context, arg CharacterRevisionsParams) ([]CharacterRevisionsRow, error) {
	rows, err := q.db.Query(ctx, characterRevisions, arg.CampaignID, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterRevisionsRow{}
	for rows.Next() {
		var i CharacterRevisionsRow
		if err := rows.Scan(
			&i.RevisionNo,
			&i.CallerName,
			&i.CreatedAt,
			&i.SnapshotID,
			&i.RetrainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearCharacterAbilities = `-- name: ClearCharacterAbilities :exec
DELETE FROM campaign.character_abilities WHERE character_id = $1
`

func (q *Queries) ClearCharacterAbilities(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCharacterAbilities, characterID)
	return err
}

const clearCharacterPicks = `-- name: ClearCharacterPicks :exec
DELETE FROM campaign.character_picks WHERE character_id = $1
`

func (q *Queries) ClearCharacterPicks(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCharacterPicks, characterID)
	return err
}

const clearCharacterSkills = `-- name: ClearCharacterSkills :exec
DELETE FROM campaign.character_skills WHERE character_id = $1
`

func (q *Queries) ClearCharacterSkills(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCharacterSkills, characterID)
	return err
}

const decideRetrain = `-- name: DecideRetrain :execrows
UPDATE campaign.retrains SET status = $1, decided_by = $2, decided_at = $3 WHERE id = $4 AND status = 'pending'
`

type DecideRetrainParams struct {
	Status    string
	DecidedBy string
	Now       pgtype.Timestamptz
	ID        uuid.UUID
}

func (q *Queries) DecideRetrain(ctx context.Context, arg DecideRetrainParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideRetrain,
		arg.Status,
		arg.DecidedBy,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRetrain = `-- name: GetRetrain :one
SELECT id, character_id, proposed_id, status, reason, requested_by, decided_by, created_at, decided_at
FROM campaign.retrains WHERE campaign_id = $1 AND id = $2
`

type GetRetrainParams struct {
	CampaignID uuid.UUID
	ID         uuid.UUID
}

type GetRetrainRow struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	ProposedID  uuid.UUID
	Status      string
	Reason      string
	RequestedBy string
	DecidedBy   string
	CreatedAt   time.Time
	DecidedAt   pgtype.Timestamptz
}

func (q *Queries) GetRetrain(ctx context.Context, arg GetRetrainParams) (GetRetrainRow, error) {
	row := q.db.QueryRow(ctx, getRetrain, arg.CampaignID, arg.ID)
	var i GetRetrainRow
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.ProposedID,
		&i.Status,
		&i.Reason,
		&i.RequestedBy,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, species_slug, background_slug, ability_method, created_at FROM campaign.character_snapshots WHERE id = $1
`

type GetSnapshotRow struct {
	ID             uuid.UUID
	SpeciesSlug    string
	BackgroundSlug string
	AbilityMethod  string
	CreatedAt      time.Time
}

func (q *Queries) GetSnapshot(ctx context.Context, id uuid.UUID) (GetSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getSnapshot, id)
	var i GetSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.SpeciesSlug,
		&i.BackgroundSlug,
		&i.AbilityMethod,
		&i.CreatedAt,
	)
	return i, err
}

const insertCharacterRevision = `-- name: InsertCharacterRevision :exec
INSERT INTO campaign.character_revisions (revision_id, snapshot_id, retrain_id) VALUES ($1, $2, $3)
`

type InsertCharacterRevisionParams struct {
	RevisionID uuid.UUID
	SnapshotID uuid.UUID
	RetrainID  pgtype.UUID
}

func (q *Queries) InsertCharacterRevision(ctx context.Context, arg InsertCharacterRevisionParams) error {
	_, err := q.db.Exec(ctx, insertCharacterRevision, arg.RevisionID, arg.SnapshotID, arg.RetrainID)
	return err
}

const insertRetrain = `-- name: InsertRetrain :exec
INSERT INTO campaign.retrains (id, campaign_id, character_id, proposed_id, status, reason, requested_by, created_at)
VALUES ($1, $2, $3, $4, 'pending', $5, $6, $7)
`

type InsertRetrainParams struct {
	ID          uuid.UUID
	CampaignID  uuid.UUID
	CharacterID uuid.UUID
	ProposedID  uuid.UUID
	Reason      string
	RequestedBy string
	Now         time.Time
}

func (q *Queries) InsertRetrain(ctx context.Context, arg InsertRetrainParams) error {
	_, err := q.db.Exec(ctx, insertRetrain,
		arg.ID,
		arg.CampaignID,
		arg.CharacterID,
		arg.ProposedID,
		arg.Reason,
		arg.RequestedBy,
		arg.Now,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO campaign.character_snapshots (id, character_id, species_slug, background_slug, ability_method, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSnapshotParams struct {
	ID             uuid.UUID
	CharacterID    uuid.UUID
	SpeciesSlug    string
	BackgroundSlug string
	AbilityMethod  string
	Now            time.Time
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot,
		arg.ID,
		arg.CharacterID,
		arg.SpeciesSlug,
		arg.BackgroundSlug,
		arg.AbilityMethod,
		arg.Now,
	)
	return err
}

const insertSnapshotAbility = `-- name: InsertSnapshotAbility :exec
INSERT INTO campaign.character_snapshot_abilities (snapshot_id, ability, base, bonus, increase) VALUES ($1, $2, $3, $4, $5)
`

type InsertSnapshotAbilityParams struct {
	SnapshotID uuid.UUID
	Ability    string
	Base       int32
	Bonus      int32
	Increase   int32
}

func (q *Queries) InsertSnapshotAbility(ctx context.Context, arg InsertSnapshotAbilityParams) error {
	_, err := q.db.Exec(ctx, insertSnapshotAbility,
		arg.SnapshotID,
		arg.Ability,
		arg.Base,
		arg.Bonus,
		arg.Increase,
	)
	return err
}

const insertSnapshotPick = `-- name: InsertSnapshotPick :exec
INSERT INTO campaign.character_snapshot_picks (snapshot_id, level, choice, value) VALUES ($1, $2, $3, $4)
`

type InsertSnapshotPickParams struct {
	SnapshotID uuid.UUID
	Level      int32
	Choice     string
	Value      string
}

func (q *Queries) InsertSnapshotPick(ctx context.Context, arg InsertSnapshotPickParams) error {
	_, err := q.db.Exec(ctx, insertSnapshotPick,
		arg.SnapshotID,
		arg.Level,
		arg.Choice,
		arg.Value,
	)
	return err
}

const insertSnapshotSkill = `-- name: InsertSnapshotSkill :exec
INSERT INTO campaign.character_snapshot_skills (snapshot_id, skill) VALUES ($1, $2)
`

type InsertSnapshotSkillParams struct {
	SnapshotID uuid.UUID
	Skill      string
}

func (q *Queries) InsertSnapshotSkill(ctx context.Context, arg InsertSnapshotSkillParams) error {
	_, err := q.db.Exec(ctx, insertSnapshotSkill, arg.SnapshotID, arg.Skill)
	return err
}

const listRetrains = `-- name: ListRetrains :many
SELECT id, character_id, proposed_id, status, reason, requested_by, decided_by, created_at, decided_at
FROM campaign.retrains WHERE campaign_id = $1 AND character_id = $2 ORDER BY created_at DESC, id
`

type ListRetrainsParams struct {
	CampaignID  uuid.UUID
	CharacterID uuid.UUID
}

type ListRetrainsRow struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	ProposedID  uuid.UUID
	Status      string
	Reason      string
	RequestedBy string
	DecidedBy   string
	CreatedAt   time.Time
	DecidedAt   pgtype.Timestamptz
}

func (q *Queries) ListRetrains(ctx context.Context, arg ListRetrainsParams) ([]ListRetrainsRow, error) {
	rows, err := q.db.Query(ctx, listRetrains, arg.CampaignID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRetrainsRow{}
	for rows.Next() {
		var i ListRetrainsRow
		if err := rows.Scan(
			&i.ID,
			&i.CharacterID,
			&i.ProposedID,
			&i.Status,
			&i.Reason,
			&i.RequestedBy,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrainCharacter = `-- name: RetrainCharacter :exec
UPDATE campaign.characters
SET species_slug = $1, background_slug = $2, ability_method = $3,
    hp_max = $4, hp_current = LEAST(hp_current, $4), updated_at = $5
WHERE campaign_id = $6 AND id = $7
`

type RetrainCharacterParams struct {
	SpeciesSlug    string
	BackgroundSlug string
	AbilityMethod  string
	HpMax          int32
	Now            time.Time
	CampaignID     uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) RetrainCharacter(ctx context.Context, arg RetrainCharacterParams) error {
	_, err := q.db.Exec(ctx, retrainCharacter,
		arg.SpeciesSlug,
		arg.BackgroundSlug,
		arg.AbilityMethod,
		arg.HpMax,
		arg.Now,
		arg.CampaignID,
		arg.ID,
	)
	return err
}

const snapshotAbilities = `-- name: SnapshotAbilities :many
SELECT ability, base, bonus, increase FROM campaign.character_snapshot_abilities WHERE snapshot_id = $1
`

type SnapshotAbilitiesRow struct {
	Ability  string
	Base     int32
	Bonus    int32
	Increase int32
}

func (q *Queries) SnapshotAbilities(ctx context.Context, snapshotID uuid.UUID) ([]SnapshotAbilitiesRow, error) {
	rows, err := q.db.Query(ctx, snapshotAbilities, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotAbilitiesRow{}
	for rows.Next() {
		var i SnapshotAbilitiesRow
		if err := rows.Scan(
			&i.Ability,
			&i.Base,
			&i.Bonus,
			&i.Increase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotPicks = `-- name: SnapshotPicks :many
SELECT level, choice, value FROM campaign.character_snapshot_picks WHERE snapshot_id = $1 ORDER BY level, choice, value
`

type SnapshotPicksRow struct {
	Level  int32
	Choice string
	Value  string
}

func (q *Queries) SnapshotPicks(ctx context.Context, snapshotID uuid.UUID) ([]SnapshotPicksRow, error) {
	rows, err := q.db.Query(ctx, snapshotPicks, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotPicksRow{}
	for rows.Next() {
		var i SnapshotPicksRow
		if err := rows.Scan(&i.Level, &i.Choice, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotSkills = `-- name: SnapshotSkills :many
SELECT skill FROM campaign.character_snapshot_skills WHERE snapshot_id = $1 ORDER BY skill
`

func (q *Queries) SnapshotSkills(ctx context.Context, snapshotID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, snapshotSkills, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var skill string
		if err := rows.Scan(&skill); err != nil {
			return nil, err
		}
		items = append(items, skill)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
