// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO social.conversation_members (conversation_id, account_id, joined_at, last_read_at) VALUES ($1, $2, $3, $3)
`

type AddConversationMemberParams struct {
	ConversationID uuid.UUID
	AccountID      uuid.UUID
	Now            time.Time
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.AccountID, arg.Now)
	return err
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (SELECT 1 FROM social.friendships WHERE a = least($1::uuid, $2::uuid) AND b = greatest($1::uuid, $2::uuid))
`

type AreFriendsParams struct {
	X uuid.UUID
	Y uuid.UUID
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.X, arg.Y)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const conversationMembers = `-- name: ConversationMembers :many
SELECT m.conversation_id, a.id, a.username, a.nickname FROM social.conversation_members m JOIN identity.accounts a ON a.id = m.account_id
WHERE m.conversation_id = ANY($1::uuid[]) ORDER BY lower(a.nickname), a.username
`

type ConversationMembersRow struct {
	ConversationID uuid.UUID
	ID             uuid.UUID
	Username       string
	Nickname       string
}

func (q *Queries) ConversationMembers(ctx context.Context, ids []uuid.UUID) ([]ConversationMembersRow, error) {
	rows, err := q.db.Query(ctx, conversationMembers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationMembersRow{}
	for rows.Next() {
		var i ConversationMembersRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.Username,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conversationTitle = `-- name: ConversationTitle :one
SELECT title FROM social.conversations WHERE id = $1
`

func (q *Queries) ConversationTitle(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, conversationTitle, id)
	var title string
	err := row.Scan(&title)
	return title, err
}

const declineFriendRequest = `-- name: DeclineFriendRequest :exec
UPDATE social.friend_requests SET status = 'declined', decided_at = $1 WHERE id = $2
`

type DeclineFriendRequestParams struct {
	Now pgtype.Timestamptz
	ID  uuid.UUID
}

func (q *Queries) DeclineFriendRequest(ctx context.Context, arg DeclineFriendRequestParams) error {
	_, err := q.db.Exec(ctx, declineFriendRequest, arg.Now, arg.ID)
	return err
}

const deleteBlock = `-- name: DeleteBlock :execrows
DELETE FROM social.blocks WHERE blocker = $1 AND blocked = $2
`

type DeleteBlockParams struct {
	Blocker uuid.UUID
	Blocked uuid.UUID
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBlock, arg.Blocker, arg.Blocked)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM social.friend_requests WHERE id = $1
`

func (q *Queries) DeleteFriendRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendRequest, id)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :execrows
DELETE FROM social.friendships WHERE a = least($1::uuid, $2::uuid) AND b = greatest($1::uuid, $2::uuid)
`

type DeleteFriendshipParams struct {
	X uuid.UUID
	Y uuid.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendship, arg.X, arg.Y)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const directConversation = `-- name: DirectConversation :one
SELECT c.id FROM social.conversations c
WHERE (SELECT count(*) FROM social.conversation_members m WHERE m.conversation_id = c.id) = 2
    AND EXISTS (SELECT 1 FROM social.conversation_members m WHERE m.conversation_id = c.id AND m.account_id = $1)
    AND EXISTS (SELECT 1 FROM social.conversation_members m WHERE m.conversation_id = c.id AND m.account_id = $2)
    AND c.title = ''
LIMIT 1
`

type DirectConversationParams struct {
	X uuid.UUID
	Y uuid.UUID
}

// The one-to-one Conversation between two Accounts, if they have one.
func (q *Queries) DirectConversation(ctx context.Context, arg DirectConversationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, directConversation, arg.X, arg.Y)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const dueDigests = `-- name: DueDigests :many
SELECT DISTINCT q.account_id FROM social.email_queue q LEFT JOIN social.digests d ON d.account_id = q.account_id
WHERE d.sent_at IS NULL OR d.sent_at <= $1
`

func (q *Queries) DueDigests(ctx context.Context, cutoff time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dueDigests, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var account_id uuid.UUID
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO social.blocks (blocker, blocked, created_at) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type InsertBlockParams struct {
	Blocker uuid.UUID
	Blocked uuid.UUID
	Now     time.Time
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock, arg.Blocker, arg.Blocked, arg.Now)
	return err
}

const insertConversation = `-- name: InsertConversation :exec
INSERT INTO social.conversations (id, title, created_by, created_at, updated_at) VALUES ($1, $2, $3, $4, $4)
`

type InsertConversationParams struct {
	ID        uuid.UUID
	Title     string
	CreatedBy uuid.UUID
	Now       time.Time
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) error {
	_, err := q.db.Exec(ctx, insertConversation,
		arg.ID,
		arg.Title,
		arg.CreatedBy,
		arg.Now,
	)
	return err
}

const insertFriendRequest = `-- name: InsertFriendRequest :execrows
INSERT INTO social.friend_requests (id, from_account, to_account, status, created_at) VALUES ($1, $2, $3, 'pending', $4)
ON CONFLICT DO NOTHING
`

type InsertFriendRequestParams struct {
	ID          uuid.UUID
	FromAccount uuid.UUID
	ToAccount   uuid.UUID
	Now         time.Time
}

func (q *Queries) InsertFriendRequest(ctx context.Context, arg InsertFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFriendRequest,
		arg.ID,
		arg.FromAccount,
		arg.ToAccount,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertFriendship = `-- name: InsertFriendship :exec
INSERT INTO social.friendships (a, b, since) VALUES (least($1::uuid, $2::uuid), greatest($1::uuid, $2::uuid), $3) ON CONFLICT DO NOTHING
`

type InsertFriendshipParams struct {
	X   uuid.UUID
	Y   uuid.UUID
	Now time.Time
}

func (q *Queries) InsertFriendship(ctx context.Context, arg InsertFriendshipParams) error {
	_, err := q.db.Exec(ctx, insertFriendship, arg.X, arg.Y, arg.Now)
	return err
}

const insertMention = `-- name: InsertMention :exec
INSERT INTO social.message_mentions (message_id, ordinal, kind, campaign_id, target_id) VALUES ($1, $2, $3, $4, $5)
`

type InsertMentionParams struct {
	MessageID  uuid.UUID
	Ordinal    int32
	Kind       string
	CampaignID uuid.UUID
	TargetID   uuid.UUID
}

func (q *Queries) InsertMention(ctx context.Context, arg InsertMentionParams) error {
	_, err := q.db.Exec(ctx, insertMention,
		arg.MessageID,
		arg.Ordinal,
		arg.Kind,
		arg.CampaignID,
		arg.TargetID,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO social.messages (id, conversation_id, author, body, created_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Author         uuid.UUID
	Body           string
	Now            time.Time
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Author,
		arg.Body,
		arg.Now,
	)
	return err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS (SELECT 1 FROM social.blocks WHERE blocker = $1 AND blocked = $2)
`

type IsBlockedParams struct {
	Blocker uuid.UUID
	Blocked uuid.UUID
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.Blocker, arg.Blocked)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (SELECT 1 FROM social.conversation_members WHERE conversation_id = $1 AND account_id = $2)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID
	AccountID      uuid.UUID
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlocked = `-- name: ListBlocked :many
SELECT a.id, a.username, a.nickname, b.created_at FROM social.blocks b JOIN identity.accounts a ON a.id = b.blocked
WHERE b.blocker = $1 ORDER BY lower(a.nickname), a.username
`

type ListBlockedRow struct {
	ID        uuid.UUID
	Username  string
	Nickname  string
	CreatedAt time.Time
}

func (q *Queries) ListBlocked(ctx context.Context, me uuid.UUID) ([]ListBlockedRow, error) {
	rows, err := q.db.Query(ctx, listBlocked, me)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedRow{}
	for rows.Next() {
		var i ListBlockedRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Nickname,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.title, c.updated_at,
    (SELECT count(*) FROM social.messages msg WHERE msg.conversation_id = c.id AND msg.author <> $1 AND msg.created_at > me.last_read_at)::integer AS unread,
    coalesce((SELECT left(msg.body, 120) FROM social.messages msg WHERE msg.conversation_id = c.id ORDER BY msg.created_at DESC, msg.id DESC LIMIT 1), '')::text AS last_body
FROM social.conversations c JOIN social.conversation_members me ON me.conversation_id = c.id AND me.account_id = $1
ORDER BY c.updated_at DESC, c.id
`

type ListConversationsRow struct {
	ID        uuid.UUID
	Title     string
	UpdatedAt time.Time
	Unread    int32
	LastBody  string
}

func (q *Queries) ListConversations(ctx context.Context, me uuid.UUID) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, me)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.Unread,
			&i.LastBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT a.id, a.username, a.nickname, f.since FROM social.friendships f
JOIN identity.accounts a ON a.id = CASE WHEN f.a = $1 THEN f.b ELSE f.a END
WHERE f.a = $1 OR f.b = $1 ORDER BY lower(a.nickname), a.username
`

type ListFriendsRow struct {
	ID       uuid.UUID
	Username string
	Nickname string
	Since    time.Time
}

func (q *Queries) ListFriends(ctx context.Context, me uuid.UUID) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, me)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendsRow{}
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Nickname,
			&i.Since,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingRequests = `-- name: ListIncomingRequests :many
SELECT r.id, a.id AS account_id, a.username, a.nickname, r.created_at FROM social.friend_requests r
JOIN identity.accounts a ON a.id = r.from_account
WHERE r.to_account = $1 AND r.status = 'pending'
    AND NOT EXISTS (SELECT 1 FROM social.blocks b WHERE b.blocker = $1 AND b.blocked = r.from_account)
ORDER BY r.created_at DESC
`

type ListIncomingRequestsRow struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Username  string
	Nickname  string
	CreatedAt time.Time
}

func (q *Queries) ListIncomingRequests(ctx context.Context, me uuid.UUID) ([]ListIncomingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingRequests, me)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingRequestsRow{}
	for rows.Next() {
		var i ListIncomingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Username,
			&i.Nickname,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT msg.id, msg.author, a.username, a.nickname, msg.body, msg.created_at FROM social.messages msg JOIN identity.accounts a ON a.id = msg.author
WHERE msg.conversation_id = $1 AND msg.created_at < $2 ORDER BY msg.created_at DESC, msg.id DESC LIMIT $3
`

type ListMessagesParams struct {
	ConversationID uuid.UUID
	Before         time.Time
	Lim            int32
}

type ListMessagesRow struct {
	ID        uuid.UUID
	Author    uuid.UUID
	Username  string
	Nickname  string
	Body      string
	CreatedAt time.Time
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Username,
			&i.Nickname,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, kind, title, body, action_label, action_path, created_at, read_at FROM social.notifications
WHERE account_id = $1 ORDER BY created_at DESC, id LIMIT 50
`

type ListNotificationsRow struct {
	ID          uuid.UUID
	Kind        string
	Title       string
	Body        string
	ActionLabel string
	ActionPath  string
	CreatedAt   time.Time
	ReadAt      pgtype.Timestamptz
}

func (q *Queries) ListNotifications(ctx context.Context, accountID uuid.UUID) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.ActionLabel,
			&i.ActionPath,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingRequests = `-- name: ListOutgoingRequests :many
SELECT r.id, a.id AS account_id, a.username, a.nickname, r.created_at FROM social.friend_requests r
JOIN identity.accounts a ON a.id = r.to_account
WHERE r.from_account = $1 AND r.status = 'pending' ORDER BY r.created_at DESC
`

type ListOutgoingRequestsRow struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	Username  string
	Nickname  string
	CreatedAt time.Time
}

func (q *Queries) ListOutgoingRequests(ctx context.Context, me uuid.UUID) ([]ListOutgoingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingRequests, me)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingRequestsRow{}
	for rows.Next() {
		var i ListOutgoingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Username,
			&i.Nickname,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE social.conversation_members SET last_read_at = $1 WHERE conversation_id = $2 AND account_id = $3
`

type MarkConversationReadParams struct {
	Now            time.Time
	ConversationID uuid.UUID
	AccountID      uuid.UUID
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.Now, arg.ConversationID, arg.AccountID)
	return err
}

const markDigest = `-- name: MarkDigest :exec
INSERT INTO social.digests (account_id, sent_at) VALUES ($1, $2) ON CONFLICT (account_id) DO UPDATE SET sent_at = EXCLUDED.sent_at
`

type MarkDigestParams struct {
	AccountID uuid.UUID
	Now       time.Time
}

func (q *Queries) MarkDigest(ctx context.Context, arg MarkDigestParams) error {
	_, err := q.db.Exec(ctx, markDigest, arg.AccountID, arg.Now)
	return err
}

const mentionableCharacters = `-- name: MentionableCharacters :many
SELECT c.id, c.name, c.campaign_id, cp.name AS campaign_name FROM campaign.characters c
JOIN campaign.campaigns cp ON cp.id = c.campaign_id
JOIN campaign.members m ON m.campaign_id = c.campaign_id JOIN identity.accounts a ON a.subject = m.auth_subject
WHERE a.id = $1 AND c.name ILIKE '%' || $2::text || '%' ORDER BY c.name LIMIT 20
`

type MentionableCharactersParams struct {
	Reader uuid.UUID
	Q      string
}

type MentionableCharactersRow struct {
	ID           uuid.UUID
	Name         string
	CampaignID   uuid.UUID
	CampaignName string
}

func (q *Queries) MentionableCharacters(ctx context.Context, arg MentionableCharactersParams) ([]MentionableCharactersRow, error) {
	rows, err := q.db.Query(ctx, mentionableCharacters, arg.Reader, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentionableCharactersRow{}
	for rows.Next() {
		var i MentionableCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CampaignID,
			&i.CampaignName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mentionableLocations = `-- name: MentionableLocations :many
SELECT n.id, n.name, mp.campaign_id, cp.name AS campaign_name FROM campaign.map_nodes n
JOIN campaign.maps mp ON mp.id = n.map_id AND mp.kind = 'world' JOIN campaign.campaigns cp ON cp.id = mp.campaign_id
JOIN campaign.members m ON m.campaign_id = mp.campaign_id AND m.role = 'dm' JOIN identity.accounts a ON a.subject = m.auth_subject
WHERE a.id = $1 AND n.name ILIKE '%' || $2::text || '%' ORDER BY n.name LIMIT 20
`

type MentionableLocationsParams struct {
	Reader uuid.UUID
	Q      string
}

type MentionableLocationsRow struct {
	ID           uuid.UUID
	Name         string
	CampaignID   uuid.UUID
	CampaignName string
}

func (q *Queries) MentionableLocations(ctx context.Context, arg MentionableLocationsParams) ([]MentionableLocationsRow, error) {
	rows, err := q.db.Query(ctx, mentionableLocations, arg.Reader, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentionableLocationsRow{}
	for rows.Next() {
		var i MentionableLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CampaignID,
			&i.CampaignName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mentionedCharacter = `-- name: MentionedCharacter :one
SELECT c.name FROM campaign.characters c JOIN campaign.members m ON m.campaign_id = c.campaign_id
JOIN identity.accounts a ON a.subject = m.auth_subject
WHERE c.id = $1 AND c.campaign_id = $2 AND a.id = $3
`

type MentionedCharacterParams struct {
	TargetID   uuid.UUID
	CampaignID uuid.UUID
	Reader     uuid.UUID
}

// A Campaign Character a reader may open: they are a Member of its Campaign.
func (q *Queries) MentionedCharacter(ctx context.Context, arg MentionedCharacterParams) (string, error) {
	row := q.db.QueryRow(ctx, mentionedCharacter, arg.TargetID, arg.CampaignID, arg.Reader)
	var name string
	err := row.Scan(&name)
	return name, err
}

const mentionedLocation = `-- name: MentionedLocation :one
SELECT n.name, mp.id AS map_id FROM campaign.map_nodes n JOIN campaign.maps mp ON mp.id = n.map_id
JOIN campaign.members m ON m.campaign_id = mp.campaign_id AND m.role = 'dm'
JOIN identity.accounts a ON a.subject = m.auth_subject
WHERE n.id = $1 AND mp.campaign_id = $2 AND a.id = $3
`

type MentionedLocationParams struct {
	TargetID   uuid.UUID
	CampaignID uuid.UUID
	Reader     uuid.UUID
}

type MentionedLocationRow struct {
	Name  string
	MapID uuid.UUID
}

// A Location a reader may open: they are a DM of its Campaign.
func (q *Queries) MentionedLocation(ctx context.Context, arg MentionedLocationParams) (MentionedLocationRow, error) {
	row := q.db.QueryRow(ctx, mentionedLocation, arg.TargetID, arg.CampaignID, arg.Reader)
	var i MentionedLocationRow
	err := row.Scan(&i.Name, &i.MapID)
	return i, err
}

const messageMentions = `-- name: MessageMentions :many
SELECT message_id, ordinal, kind, campaign_id, target_id FROM social.message_mentions WHERE message_id = ANY($1::uuid[]) ORDER BY message_id, ordinal
`

func (q *Queries) MessageMentions(ctx context.Context, ids []uuid.UUID) ([]SocialMessageMention, error) {
	rows, err := q.db.Query(ctx, messageMentions, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialMessageMention{}
	for rows.Next() {
		var i SocialMessageMention
		if err := rows.Scan(
			&i.MessageID,
			&i.Ordinal,
			&i.Kind,
			&i.CampaignID,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationPreferences = `-- name: NotificationPreferences :many
SELECT kind, channel, enabled FROM social.notification_preferences WHERE account_id = $1
`

type NotificationPreferencesRow struct {
	Kind    string
	Channel string
	Enabled bool
}

func (q *Queries) NotificationPreferences(ctx context.Context, accountID uuid.UUID) ([]NotificationPreferencesRow, error) {
	rows, err := q.db.Query(ctx, notificationPreferences, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreferencesRow{}
	for rows.Next() {
		var i NotificationPreferencesRow
		if err := rows.Scan(&i.Kind, &i.Channel, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingBetween = `-- name: PendingBetween :one
SELECT id FROM social.friend_requests WHERE from_account = $1 AND to_account = $2 AND status = 'pending'
`

type PendingBetweenParams struct {
	FromAccount uuid.UUID
	ToAccount   uuid.UUID
}

func (q *Queries) PendingBetween(ctx context.Context, arg PendingBetweenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, pendingBetween, arg.FromAccount, arg.ToAccount)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const pendingRequest = `-- name: PendingRequest :one
SELECT id, from_account, to_account FROM social.friend_requests WHERE id = $1 AND status = 'pending'
`

type PendingRequestRow struct {
	ID          uuid.UUID
	FromAccount uuid.UUID
	ToAccount   uuid.UUID
}

func (q *Queries) PendingRequest(ctx context.Context, id uuid.UUID) (PendingRequestRow, error) {
	row := q.db.QueryRow(ctx, pendingRequest, id)
	var i PendingRequestRow
	err := row.Scan(&i.ID, &i.FromAccount, &i.ToAccount)
	return i, err
}

const queueEmail = `-- name: QueueEmail :exec
INSERT INTO social.email_queue (id, account_id, kind, title, body, action_label, action_path, dedupe_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (account_id, dedupe_key) WHERE dedupe_key <> ''
DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body, action_path = EXCLUDED.action_path, created_at = EXCLUDED.created_at
`

type QueueEmailParams struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	Title       string
	Body        string
	ActionLabel string
	ActionPath  string
	DedupeKey   string
	Now         time.Time
}

func (q *Queries) QueueEmail(ctx context.Context, arg QueueEmailParams) error {
	_, err := q.db.Exec(ctx, queueEmail,
		arg.ID,
		arg.AccountID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.ActionLabel,
		arg.ActionPath,
		arg.DedupeKey,
		arg.Now,
	)
	return err
}

const readAllNotifications = `-- name: ReadAllNotifications :exec
UPDATE social.notifications SET read_at = $1 WHERE account_id = $2 AND read_at IS NULL
`

type ReadAllNotificationsParams struct {
	Now       pgtype.Timestamptz
	AccountID uuid.UUID
}

func (q *Queries) ReadAllNotifications(ctx context.Context, arg ReadAllNotificationsParams) error {
	_, err := q.db.Exec(ctx, readAllNotifications, arg.Now, arg.AccountID)
	return err
}

const readNotification = `-- name: ReadNotification :execrows
UPDATE social.notifications SET read_at = $1 WHERE id = $2 AND account_id = $3 AND read_at IS NULL
`

type ReadNotificationParams struct {
	Now       pgtype.Timestamptz
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) ReadNotification(ctx context.Context, arg ReadNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, readNotification, arg.Now, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNotificationPreference = `-- name: SetNotificationPreference :exec
INSERT INTO social.notification_preferences (account_id, kind, channel, enabled) VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, kind, channel) DO UPDATE SET enabled = EXCLUDED.enabled
`

type SetNotificationPreferenceParams struct {
	AccountID uuid.UUID
	Kind      string
	Channel   string
	Enabled   bool
}

func (q *Queries) SetNotificationPreference(ctx context.Context, arg SetNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, setNotificationPreference,
		arg.AccountID,
		arg.Kind,
		arg.Channel,
		arg.Enabled,
	)
	return err
}

const socialAccountBySubject = `-- name: SocialAccountBySubject :one
SELECT id, username, nickname FROM identity.accounts WHERE subject = $1 AND NOT disabled
`

type SocialAccountBySubjectRow struct {
	ID       uuid.UUID
	Username string
	Nickname string
}

func (q *Queries) SocialAccountBySubject(ctx context.Context, subject string) (SocialAccountBySubjectRow, error) {
	row := q.db.QueryRow(ctx, socialAccountBySubject, subject)
	var i SocialAccountBySubjectRow
	err := row.Scan(&i.ID, &i.Username, &i.Nickname)
	return i, err
}

const socialAccountByUsername = `-- name: SocialAccountByUsername :one
SELECT id, username, nickname FROM identity.accounts WHERE username = $1 AND NOT disabled
`

type SocialAccountByUsernameRow struct {
	ID       uuid.UUID
	Username string
	Nickname string
}

func (q *Queries) SocialAccountByUsername(ctx context.Context, username string) (SocialAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, socialAccountByUsername, username)
	var i SocialAccountByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.Nickname)
	return i, err
}

const socialRecipient = `-- name: SocialRecipient :one
SELECT subject, coalesce(email, '')::text AS email, nickname FROM identity.accounts WHERE id = $1 AND NOT disabled
`

type SocialRecipientRow struct {
	Subject  string
	Email    string
	Nickname string
}

func (q *Queries) SocialRecipient(ctx context.Context, id uuid.UUID) (SocialRecipientRow, error) {
	row := q.db.QueryRow(ctx, socialRecipient, id)
	var i SocialRecipientRow
	err := row.Scan(&i.Subject, &i.Email, &i.Nickname)
	return i, err
}

const takeQueuedEmail = `-- name: TakeQueuedEmail :many
DELETE FROM social.email_queue WHERE account_id = $1
RETURNING kind, title, body, action_label, action_path, created_at
`

type TakeQueuedEmailRow struct {
	Kind        string
	Title       string
	Body        string
	ActionLabel string
	ActionPath  string
	CreatedAt   time.Time
}

func (q *Queries) TakeQueuedEmail(ctx context.Context, accountID uuid.UUID) ([]TakeQueuedEmailRow, error) {
	rows, err := q.db.Query(ctx, takeQueuedEmail, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TakeQueuedEmailRow{}
	for rows.Next() {
		var i TakeQueuedEmailRow
		if err := rows.Scan(
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.ActionLabel,
			&i.ActionPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE social.conversations SET updated_at = $1 WHERE id = $2
`

type TouchConversationParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation, arg.Now, arg.ID)
	return err
}

const unreadNotifications = `-- name: UnreadNotifications :one
SELECT count(*)::integer AS unread FROM social.notifications WHERE account_id = $1 AND read_at IS NULL
`

func (q *Queries) UnreadNotifications(ctx context.Context, accountID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, unreadNotifications, accountID)
	var unread int32
	err := row.Scan(&unread)
	return unread, err
}

const upsertNotification = `-- name: UpsertNotification :exec
INSERT INTO social.notifications (id, account_id, kind, title, body, action_label, action_path, dedupe_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (account_id, dedupe_key) WHERE read_at IS NULL AND dedupe_key <> ''
DO UPDATE SET title = EXCLUDED.title, body = EXCLUDED.body, action_label = EXCLUDED.action_label,
    action_path = EXCLUDED.action_path, created_at = EXCLUDED.created_at
`

type UpsertNotificationParams struct {
	ID          uuid.UUID
	AccountID   uuid.UUID
	Kind        string
	Title       string
	Body        string
	ActionLabel string
	ActionPath  string
	DedupeKey   string
	Now         time.Time
}

func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) error {
	_, err := q.db.Exec(ctx, upsertNotification,
		arg.ID,
		arg.AccountID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.ActionLabel,
		arg.ActionPath,
		arg.DedupeKey,
		arg.Now,
	)
	return err
}
