// Code generated by ogen, DO NOT EDIT.
package oas

type AcceptInviteRes interface {
	acceptInviteRes()
}

type CreateCampaignRes interface {
	createCampaignRes()
}

type CreateInviteRes interface {
	createInviteRes()
}

type GetAutomationCoverageRes interface {
	getAutomationCoverageRes()
}

type GetCampaignRes interface {
	getCampaignRes()
}

type GetEntryRes interface {
	getEntryRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetReadinessRes interface {
	getReadinessRes()
}

type GetSpellRes interface {
	getSpellRes()
}

type GetStatusRes interface {
	getStatusRes()
}

type ListCampaignsRes interface {
	listCampaignsRes()
}

type ListEntriesRes interface {
	listEntriesRes()
}

type ListInvitesRes interface {
	listInvitesRes()
}

type ListSourcesRes interface {
	listSourcesRes()
}

type ListSpellsRes interface {
	listSpellsRes()
}

type PreviewInviteRes interface {
	previewInviteRes()
}

type RemoveMemberRes interface {
	removeMemberRes()
}

type RevokeInviteRes interface {
	revokeInviteRes()
}

type UpdateCampaignRes interface {
	updateCampaignRes()
}

type UpdateMemberRes interface {
	updateMemberRes()
}
