// Code generated by ogen, DO NOT EDIT.
package oas

type AcceptInviteRes interface {
	acceptInviteRes()
}

type ClearTokenIconRes interface {
	clearTokenIconRes()
}

type CreateCampaignRes interface {
	createCampaignRes()
}

type CreateCharacterRes interface {
	createCharacterRes()
}

type CreateInviteRes interface {
	createInviteRes()
}

type CreateNpcRes interface {
	createNpcRes()
}

type CreateRollRes interface {
	createRollRes()
}

type DeleteCharacterRes interface {
	deleteCharacterRes()
}

type DeleteNpcRes interface {
	deleteNpcRes()
}

type DiffNpcRevisionsRes interface {
	diffNpcRevisionsRes()
}

type GetActionLogRes interface {
	getActionLogRes()
}

type GetAutomationCoverageRes interface {
	getAutomationCoverageRes()
}

type GetBuilderOptionsRes interface {
	getBuilderOptionsRes()
}

type GetCampaignRes interface {
	getCampaignRes()
}

type GetCharacterRes interface {
	getCharacterRes()
}

type GetEntryRes interface {
	getEntryRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetNpcRes interface {
	getNpcRes()
}

type GetPortraitRes interface {
	getPortraitRes()
}

type GetReadinessRes interface {
	getReadinessRes()
}

type GetRollRes interface {
	getRollRes()
}

type GetSpellRes interface {
	getSpellRes()
}

type GetStatusRes interface {
	getStatusRes()
}

type GetTokenIconRes interface {
	getTokenIconRes()
}

type ListCampaignsRes interface {
	listCampaignsRes()
}

type ListCharactersRes interface {
	listCharactersRes()
}

type ListDeletedNpcsRes interface {
	listDeletedNpcsRes()
}

type ListEntriesRes interface {
	listEntriesRes()
}

type ListInvitesRes interface {
	listInvitesRes()
}

type ListNpcRevisionsRes interface {
	listNpcRevisionsRes()
}

type ListNpcsRes interface {
	listNpcsRes()
}

type ListRollsRes interface {
	listRollsRes()
}

type ListSourcesRes interface {
	listSourcesRes()
}

type ListSpellsRes interface {
	listSpellsRes()
}

type PreviewCharacterRes interface {
	previewCharacterRes()
}

type PreviewInviteRes interface {
	previewInviteRes()
}

type PreviewReachRes interface {
	previewReachRes()
}

type PreviewSightRes interface {
	previewSightRes()
}

type RemoveMemberRes interface {
	removeMemberRes()
}

type RestoreNpcRevisionRes interface {
	restoreNpcRevisionRes()
}

type RevokeInviteRes interface {
	revokeInviteRes()
}

type RollRestRes interface {
	rollRestRes()
}

type SetDieRes interface {
	setDieRes()
}

type SetPortraitRes interface {
	setPortraitRes()
}

type SetTokenIconRes interface {
	setTokenIconRes()
}

type UpdateCampaignRes interface {
	updateCampaignRes()
}

type UpdateCharacterRes interface {
	updateCharacterRes()
}

type UpdateMemberRes interface {
	updateMemberRes()
}

type UpdateNpcRes interface {
	updateNpcRes()
}
