// Code generated by ogen, DO NOT EDIT.
package oas

type GetHealthRes interface {
	getHealthRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetReadinessRes interface {
	getReadinessRes()
}

type GetSpellRes interface {
	getSpellRes()
}

type GetStatusRes interface {
	getStatusRes()
}

type ListSourcesRes interface {
	listSourcesRes()
}

type ListSpellsRes interface {
	listSpellsRes()
}
