// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn8AllowedHeaders = map[string]string{
		"GET":  "X-User-Id",
		"POST": "Content-Type,X-User-Id",
	}
	rn4AllowedHeaders = map[string]string{
		"GET":   "X-User-Id",
		"PATCH": "Content-Type,X-User-Id",
	}
	rn9AllowedHeaders = map[string]string{
		"GET":  "X-User-Id",
		"POST": "Content-Type,X-User-Id",
	}
	rn33AllowedHeaders = map[string]string{
		"POST": "Content-Type,X-User-Id",
	}
	rn6AllowedHeaders = map[string]string{
		"DELETE": "X-User-Id",
		"GET":    "X-User-Id",
		"PATCH":  "Content-Type,X-User-Id",
	}
	rn24AllowedHeaders = map[string]string{
		"GET": "X-User-Id",
		"PUT": "Content-Type,X-User-Id",
	}
	rn7AllowedHeaders = map[string]string{
		"DELETE": "X-User-Id",
		"GET":    "X-User-Id",
		"PUT":    "Content-Type,X-User-Id",
	}
	rn11AllowedHeaders = map[string]string{
		"GET":  "X-User-Id",
		"POST": "X-User-Id",
	}
	rn39AllowedHeaders = map[string]string{
		"DELETE": "X-User-Id",
	}
	rn37AllowedHeaders = map[string]string{
		"DELETE": "X-User-Id",
		"PATCH":  "Content-Type,X-User-Id",
	}
	rn13AllowedHeaders = map[string]string{
		"GET": "If-None-Match,X-User-Id",
	}
	rn15AllowedHeaders = map[string]string{
		"GET": "If-None-Match,X-User-Id",
	}
	rn29AllowedHeaders = map[string]string{
		"GET": "If-None-Match,X-User-Id",
	}
	rn19AllowedHeaders = map[string]string{
		"GET": "If-None-Match,X-User-Id",
	}
	rn31AllowedHeaders = map[string]string{
		"GET": "X-User-Id",
	}
	rn32AllowedHeaders = map[string]string{
		"GET": "If-None-Match,X-User-Id",
	}
	rn27AllowedHeaders = map[string]string{
		"GET": "If-None-Match,X-User-Id",
	}
	rn1AllowedHeaders = map[string]string{
		"POST": "Content-Type,X-User-Id",
	}
	rn35AllowedHeaders = map[string]string{
		"POST": "Content-Type,X-User-Id",
	}
	rn22AllowedHeaders = map[string]string{
		"GET": "X-User-Id",
	}
	rn28AllowedHeaders = map[string]string{
		"GET": "X-User-Id",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/v1/"

				if l := len("api/v1/"); len(elem) >= l && elem[0:l] == "api/v1/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "c"

					if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "ampaigns"

						if l := len("ampaigns"); len(elem) >= l && elem[0:l] == "ampaigns" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListCampaignsRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleCreateCampaignRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,POST",
									allowedHeaders: rn8AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "campaignId"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleGetCampaignRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PATCH":
									s.handleUpdateCampaignRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,PATCH",
										allowedHeaders: rn4AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "characters"

									if l := len("characters"); len(elem) >= l && elem[0:l] == "characters" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch r.Method {
										case "GET":
											s.handleListCharactersRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										case "POST":
											s.handleCreateCharacterRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET,POST",
												allowedHeaders: rn9AllowedHeaders,
												acceptPost:     "application/json",
												acceptPatch:    "",
											})
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'p': // Prefix: "preview"
											origElem := elem
											if l := len("preview"); len(elem) >= l && elem[0:l] == "preview" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch r.Method {
												case "POST":
													s.handlePreviewCharacterRequest([1]string{
														args[0],
													}, elemIsEscaped, w, r)
												default:
													s.notAllowed(w, r, notAllowedParams{
														allowedMethods: "POST",
														allowedHeaders: rn33AllowedHeaders,
														acceptPost:     "application/json",
														acceptPatch:    "",
													})
												}

												return
											}

											elem = origElem
										}
										// Param: "characterId"
										// Match until "/"
										idx := strings.IndexByte(elem, '/')
										if idx < 0 {
											idx = len(elem)
										}
										args[1] = elem[:idx]
										elem = elem[idx:]

										if len(elem) == 0 {
											switch r.Method {
											case "DELETE":
												s.handleDeleteCharacterRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											case "GET":
												s.handleGetCharacterRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											case "PATCH":
												s.handleUpdateCharacterRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "DELETE,GET,PATCH",
													allowedHeaders: rn6AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "application/json",
												})
											}

											return
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case 'p': // Prefix: "portrait"

												if l := len("portrait"); len(elem) >= l && elem[0:l] == "portrait" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "GET":
														s.handleGetPortraitRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													case "PUT":
														s.handleSetPortraitRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, notAllowedParams{
															allowedMethods: "GET,PUT",
															allowedHeaders: rn24AllowedHeaders,
															acceptPost:     "",
															acceptPatch:    "",
														})
													}

													return
												}

											case 't': // Prefix: "token"

												if l := len("token"); len(elem) >= l && elem[0:l] == "token" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch r.Method {
													case "DELETE":
														s.handleClearTokenIconRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													case "GET":
														s.handleGetTokenIconRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													case "PUT":
														s.handleSetTokenIconRequest([2]string{
															args[0],
															args[1],
														}, elemIsEscaped, w, r)
													default:
														s.notAllowed(w, r, notAllowedParams{
															allowedMethods: "DELETE,GET,PUT",
															allowedHeaders: rn7AllowedHeaders,
															acceptPost:     "",
															acceptPatch:    "",
														})
													}

													return
												}

											}

										}

									}

								case 'i': // Prefix: "invites"

									if l := len("invites"); len(elem) >= l && elem[0:l] == "invites" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch r.Method {
										case "GET":
											s.handleListInvitesRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										case "POST":
											s.handleCreateInviteRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET,POST",
												allowedHeaders: rn11AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										// Param: "inviteId"
										// Leaf parameter, slashes are prohibited
										idx := strings.IndexByte(elem, '/')
										if idx >= 0 {
											break
										}
										args[1] = elem
										elem = ""

										if len(elem) == 0 {
											// Leaf node.
											switch r.Method {
											case "DELETE":
												s.handleRevokeInviteRequest([2]string{
													args[0],
													args[1],
												}, elemIsEscaped, w, r)
											default:
												s.notAllowed(w, r, notAllowedParams{
													allowedMethods: "DELETE",
													allowedHeaders: rn39AllowedHeaders,
													acceptPost:     "",
													acceptPatch:    "",
												})
											}

											return
										}

									}

								case 'm': // Prefix: "members/"

									if l := len("members/"); len(elem) >= l && elem[0:l] == "members/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "memberId"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "DELETE":
											s.handleRemoveMemberRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										case "PATCH":
											s.handleUpdateMemberRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "DELETE,PATCH",
												allowedHeaders: rn37AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "application/json",
											})
										}

										return
									}

								}

							}

						}

					case 'o': // Prefix: "ompendium/"

						if l := len("ompendium/"); len(elem) >= l && elem[0:l] == "ompendium/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "automation"

							if l := len("automation"); len(elem) >= l && elem[0:l] == "automation" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetAutomationCoverageRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn13AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'b': // Prefix: "builder"

							if l := len("builder"); len(elem) >= l && elem[0:l] == "builder" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetBuilderOptionsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn15AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'e': // Prefix: "entries"

							if l := len("entries"); len(elem) >= l && elem[0:l] == "entries" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListEntriesRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn29AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "kind"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[0] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "slug"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleGetEntryRequest([2]string{
												args[0],
												args[1],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn19AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'o': // Prefix: "ources"

								if l := len("ources"); len(elem) >= l && elem[0:l] == "ources" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleListSourcesRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn31AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 'p': // Prefix: "pells"

								if l := len("pells"); len(elem) >= l && elem[0:l] == "pells" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch r.Method {
									case "GET":
										s.handleListSpellsRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: rn32AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "slug"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[0] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "GET":
											s.handleGetSpellRequest([1]string{
												args[0],
											}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "GET",
												allowedHeaders: rn27AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

							}

						}

					}

				case 'i': // Prefix: "invites/"

					if l := len("invites/"); len(elem) >= l && elem[0:l] == "invites/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "accept"

						if l := len("accept"); len(elem) >= l && elem[0:l] == "accept" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleAcceptInviteRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn1AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'p': // Prefix: "preview"

						if l := len("preview"); len(elem) >= l && elem[0:l] == "preview" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handlePreviewInviteRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn35AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetMeRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn22AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 's': // Prefix: "status"

					if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleGetStatusRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: rn28AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'h': // Prefix: "healthz"

				if l := len("healthz"); len(elem) >= l && elem[0:l] == "healthz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetHealthRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'r': // Prefix: "readyz"

				if l := len("readyz"); len(elem) >= l && elem[0:l] == "readyz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleGetReadinessRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/v1/"

				if l := len("api/v1/"); len(elem) >= l && elem[0:l] == "api/v1/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'c': // Prefix: "c"

					if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "ampaigns"

						if l := len("ampaigns"); len(elem) >= l && elem[0:l] == "ampaigns" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListCampaignsOperation
								r.summary = "List my campaigns"
								r.operationID = "listCampaigns"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/campaigns"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = CreateCampaignOperation
								r.summary = "Create a campaign"
								r.operationID = "createCampaign"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/campaigns"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "campaignId"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = GetCampaignOperation
									r.summary = "Get a campaign"
									r.operationID = "getCampaign"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/campaigns/{campaignId}"
									r.args = args
									r.count = 1
									return r, true
								case "PATCH":
									r.name = UpdateCampaignOperation
									r.summary = "Update a campaign"
									r.operationID = "updateCampaign"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/campaigns/{campaignId}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'c': // Prefix: "characters"

									if l := len("characters"); len(elem) >= l && elem[0:l] == "characters" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch method {
										case "GET":
											r.name = ListCharactersOperation
											r.summary = "List characters"
											r.operationID = "listCharacters"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/campaigns/{campaignId}/characters"
											r.args = args
											r.count = 1
											return r, true
										case "POST":
											r.name = CreateCharacterOperation
											r.summary = "Create a character"
											r.operationID = "createCharacter"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/campaigns/{campaignId}/characters"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										if len(elem) == 0 {
											break
										}
										switch elem[0] {
										case 'p': // Prefix: "preview"
											origElem := elem
											if l := len("preview"); len(elem) >= l && elem[0:l] == "preview" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												// Leaf node.
												switch method {
												case "POST":
													r.name = PreviewCharacterOperation
													r.summary = "Preview a character"
													r.operationID = "previewCharacter"
													r.operationGroup = ""
													r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/preview"
													r.args = args
													r.count = 1
													return r, true
												default:
													return
												}
											}

											elem = origElem
										}
										// Param: "characterId"
										// Match until "/"
										idx := strings.IndexByte(elem, '/')
										if idx < 0 {
											idx = len(elem)
										}
										args[1] = elem[:idx]
										elem = elem[idx:]

										if len(elem) == 0 {
											switch method {
											case "DELETE":
												r.name = DeleteCharacterOperation
												r.summary = "Delete a character"
												r.operationID = "deleteCharacter"
												r.operationGroup = ""
												r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}"
												r.args = args
												r.count = 2
												return r, true
											case "GET":
												r.name = GetCharacterOperation
												r.summary = "Get a character sheet"
												r.operationID = "getCharacter"
												r.operationGroup = ""
												r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}"
												r.args = args
												r.count = 2
												return r, true
											case "PATCH":
												r.name = UpdateCharacterOperation
												r.summary = "Edit a character"
												r.operationID = "updateCharacter"
												r.operationGroup = ""
												r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}
										switch elem[0] {
										case '/': // Prefix: "/"

											if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
												elem = elem[l:]
											} else {
												break
											}

											if len(elem) == 0 {
												break
											}
											switch elem[0] {
											case 'p': // Prefix: "portrait"

												if l := len("portrait"); len(elem) >= l && elem[0:l] == "portrait" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "GET":
														r.name = GetPortraitOperation
														r.summary = "Get the portrait"
														r.operationID = "getPortrait"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}/portrait"
														r.args = args
														r.count = 2
														return r, true
													case "PUT":
														r.name = SetPortraitOperation
														r.summary = "Upload the portrait"
														r.operationID = "setPortrait"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}/portrait"
														r.args = args
														r.count = 2
														return r, true
													default:
														return
													}
												}

											case 't': // Prefix: "token"

												if l := len("token"); len(elem) >= l && elem[0:l] == "token" {
													elem = elem[l:]
												} else {
													break
												}

												if len(elem) == 0 {
													// Leaf node.
													switch method {
													case "DELETE":
														r.name = ClearTokenIconOperation
														r.summary = "Use initials for the token"
														r.operationID = "clearTokenIcon"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}/token"
														r.args = args
														r.count = 2
														return r, true
													case "GET":
														r.name = GetTokenIconOperation
														r.summary = "Get the token icon"
														r.operationID = "getTokenIcon"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}/token"
														r.args = args
														r.count = 2
														return r, true
													case "PUT":
														r.name = SetTokenIconOperation
														r.summary = "Upload the token icon"
														r.operationID = "setTokenIcon"
														r.operationGroup = ""
														r.pathPattern = "/api/v1/campaigns/{campaignId}/characters/{characterId}/token"
														r.args = args
														r.count = 2
														return r, true
													default:
														return
													}
												}

											}

										}

									}

								case 'i': // Prefix: "invites"

									if l := len("invites"); len(elem) >= l && elem[0:l] == "invites" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										switch method {
										case "GET":
											r.name = ListInvitesOperation
											r.summary = "List open invites"
											r.operationID = "listInvites"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/campaigns/{campaignId}/invites"
											r.args = args
											r.count = 1
											return r, true
										case "POST":
											r.name = CreateInviteOperation
											r.summary = "Create an invite link"
											r.operationID = "createInvite"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/campaigns/{campaignId}/invites"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}
									switch elem[0] {
									case '/': // Prefix: "/"

										if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
											elem = elem[l:]
										} else {
											break
										}

										// Param: "inviteId"
										// Leaf parameter, slashes are prohibited
										idx := strings.IndexByte(elem, '/')
										if idx >= 0 {
											break
										}
										args[1] = elem
										elem = ""

										if len(elem) == 0 {
											// Leaf node.
											switch method {
											case "DELETE":
												r.name = RevokeInviteOperation
												r.summary = "Revoke an invite link"
												r.operationID = "revokeInvite"
												r.operationGroup = ""
												r.pathPattern = "/api/v1/campaigns/{campaignId}/invites/{inviteId}"
												r.args = args
												r.count = 2
												return r, true
											default:
												return
											}
										}

									}

								case 'm': // Prefix: "members/"

									if l := len("members/"); len(elem) >= l && elem[0:l] == "members/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "memberId"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "DELETE":
											r.name = RemoveMemberOperation
											r.summary = "Remove a member"
											r.operationID = "removeMember"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/campaigns/{campaignId}/members/{memberId}"
											r.args = args
											r.count = 2
											return r, true
										case "PATCH":
											r.name = UpdateMemberOperation
											r.summary = "Change a member role"
											r.operationID = "updateMember"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/campaigns/{campaignId}/members/{memberId}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							}

						}

					case 'o': // Prefix: "ompendium/"

						if l := len("ompendium/"); len(elem) >= l && elem[0:l] == "ompendium/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "automation"

							if l := len("automation"); len(elem) >= l && elem[0:l] == "automation" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetAutomationCoverageOperation
									r.summary = "Get automation coverage"
									r.operationID = "getAutomationCoverage"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/compendium/automation"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'b': // Prefix: "builder"

							if l := len("builder"); len(elem) >= l && elem[0:l] == "builder" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetBuilderOptionsOperation
									r.summary = "Get character builder options"
									r.operationID = "getBuilderOptions"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/compendium/builder"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'e': // Prefix: "entries"

							if l := len("entries"); len(elem) >= l && elem[0:l] == "entries" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListEntriesOperation
									r.summary = "List compendium entries"
									r.operationID = "listEntries"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/compendium/entries"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "kind"
								// Match until "/"
								idx := strings.IndexByte(elem, '/')
								if idx < 0 {
									idx = len(elem)
								}
								args[0] = elem[:idx]
								elem = elem[idx:]

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "slug"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[1] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = GetEntryOperation
											r.summary = "Get a compendium entry"
											r.operationID = "getEntry"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/compendium/entries/{kind}/{slug}"
											r.args = args
											r.count = 2
											return r, true
										default:
											return
										}
									}

								}

							}

						case 's': // Prefix: "s"

							if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'o': // Prefix: "ources"

								if l := len("ources"); len(elem) >= l && elem[0:l] == "ources" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ListSourcesOperation
										r.summary = "List compendium sources"
										r.operationID = "listSources"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/compendium/sources"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							case 'p': // Prefix: "pells"

								if l := len("pells"); len(elem) >= l && elem[0:l] == "pells" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									switch method {
									case "GET":
										r.name = ListSpellsOperation
										r.summary = "List spells"
										r.operationID = "listSpells"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/compendium/spells"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}
								switch elem[0] {
								case '/': // Prefix: "/"

									if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
										elem = elem[l:]
									} else {
										break
									}

									// Param: "slug"
									// Leaf parameter, slashes are prohibited
									idx := strings.IndexByte(elem, '/')
									if idx >= 0 {
										break
									}
									args[0] = elem
									elem = ""

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "GET":
											r.name = GetSpellOperation
											r.summary = "Get a spell"
											r.operationID = "getSpell"
											r.operationGroup = ""
											r.pathPattern = "/api/v1/compendium/spells/{slug}"
											r.args = args
											r.count = 1
											return r, true
										default:
											return
										}
									}

								}

							}

						}

					}

				case 'i': // Prefix: "invites/"

					if l := len("invites/"); len(elem) >= l && elem[0:l] == "invites/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "accept"

						if l := len("accept"); len(elem) >= l && elem[0:l] == "accept" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = AcceptInviteOperation
								r.summary = "Accept an invite"
								r.operationID = "acceptInvite"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/invites/accept"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'p': // Prefix: "preview"

						if l := len("preview"); len(elem) >= l && elem[0:l] == "preview" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = PreviewInviteOperation
								r.summary = "Preview an invite"
								r.operationID = "previewInvite"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/invites/preview"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetMeOperation
							r.summary = "Who am I"
							r.operationID = "getMe"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/me"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 's': // Prefix: "status"

					if l := len("status"); len(elem) >= l && elem[0:l] == "status" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = GetStatusOperation
							r.summary = "Service status"
							r.operationID = "getStatus"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/status"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'h': // Prefix: "healthz"

				if l := len("healthz"); len(elem) >= l && elem[0:l] == "healthz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetHealthOperation
						r.summary = "Liveness probe"
						r.operationID = "getHealth"
						r.operationGroup = ""
						r.pathPattern = "/healthz"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'r': // Prefix: "readyz"

				if l := len("readyz"); len(elem) >= l && elem[0:l] == "readyz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = GetReadinessOperation
						r.summary = "Readiness probe"
						r.operationID = "getReadiness"
						r.operationGroup = ""
						r.pathPattern = "/readyz"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			}

		}
	}
	return r, false
}
