// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	AccountHandler
	BuildHandler
	PlayHandler
	ReadHandler
}

// AccountHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Account
type AccountHandler interface {
	// AcceptAccountInvite implements acceptAccountInvite operation.
	//
	// Creates the Account the invite was for and signs it in on this device.
	//
	// POST /api/v1/account-invites/accept
	AcceptAccountInvite(ctx context.Context, req *AccountSetup) (AcceptAccountInviteRes, error)
	// AcceptFriendRequest implements acceptFriendRequest operation.
	//
	// The two are Friends from now on.
	//
	// POST /api/v1/friend-requests/{requestId}/accept
	AcceptFriendRequest(ctx context.Context, params AcceptFriendRequestParams) (AcceptFriendRequestRes, error)
	// BeginTwoStep implements beginTwoStep operation.
	//
	// Makes a new authenticator secret for the signed-in Account; confirming it with a code turns two-step
	// on.
	//
	// POST /api/v1/account/two-step
	BeginTwoStep(ctx context.Context) (BeginTwoStepRes, error)
	// CancelFriendRequest implements cancelFriendRequest operation.
	//
	// Withdraws a request the signed-in Account sent.
	//
	// DELETE /api/v1/friend-requests/{requestId}
	CancelFriendRequest(ctx context.Context, params CancelFriendRequestParams) (CancelFriendRequestRes, error)
	// ConfirmTwoStep implements confirmTwoStep operation.
	//
	// Checks a first code from the app and returns the recovery codes, shown only now.
	//
	// POST /api/v1/account/two-step/confirm
	ConfirmTwoStep(ctx context.Context, req *TwoStepCode, params ConfirmTwoStepParams) (ConfirmTwoStepRes, error)
	// CreateAccessToken implements createAccessToken operation.
	//
	// A token for MCP clients and scripts that acts as this Account within its scopes; it is shown only
	// now.
	//
	// POST /api/v1/account/access-tokens
	CreateAccessToken(ctx context.Context, req *AccessTokenRequest) (CreateAccessTokenRes, error)
	// CreateAccountInvite implements createAccountInvite operation.
	//
	// An Admin's one-time Account Invite, closed once used or when it expires. Only an Admin can invite
	// another Admin.
	//
	// POST /api/v1/admin/account-invites
	CreateAccountInvite(ctx context.Context, req *AccountInviteRequest) (CreateAccountInviteRes, error)
	// CreateOidcAccount implements createOidcAccount operation.
	//
	// Sets up an Account for a login no Account has yet, and signs it in.
	//
	// POST /api/v1/oidc/accounts
	CreateOidcAccount(ctx context.Context, req *OidcAccountSetup) (CreateOidcAccountRes, error)
	// CreatePushSubscription implements createPushSubscription operation.
	//
	// Asks for this device to be told about the caller's turns and Reaction Prompts while the app is
	// closed.
	//
	// POST /api/v1/push/subscriptions
	CreatePushSubscription(ctx context.Context, req *PushSubscriptionInput) (CreatePushSubscriptionRes, error)
	// DeclineFriendRequest implements declineFriendRequest operation.
	//
	// Turns the request down; with block, the sender's later requests never show.
	//
	// POST /api/v1/friend-requests/{requestId}/decline
	DeclineFriendRequest(ctx context.Context, req *FriendRequestDecline, params DeclineFriendRequestParams) (DeclineFriendRequestRes, error)
	// DeletePushSubscription implements deletePushSubscription operation.
	//
	// Stops notifications to one of the caller's devices.
	//
	// DELETE /api/v1/push/subscriptions/{subscriptionId}
	DeletePushSubscription(ctx context.Context, params DeletePushSubscriptionParams) (DeletePushSubscriptionRes, error)
	// DisableTwoStep implements disableTwoStep operation.
	//
	// Needs a current code or a recovery code; the recovery codes go too.
	//
	// POST /api/v1/account/two-step/disable
	DisableTwoStep(ctx context.Context, req *TwoStepCode) (DisableTwoStepRes, error)
	// DraftReleaseNote implements draftReleaseNote operation.
	//
	// Starts the one Release Note of a full release, listing the features its changelog says it added. For
	// Admins.
	//
	// POST /api/v1/admin/release-notes
	DraftReleaseNote(ctx context.Context, req *ReleaseNoteDraft) (DraftReleaseNoteRes, error)
	// EditReleaseNote implements editReleaseNote operation.
	//
	// Changes its words until it has been announced. For Admins.
	//
	// PUT /api/v1/admin/release-notes/{noteId}
	EditReleaseNote(ctx context.Context, req *ReleaseNoteChange, params EditReleaseNoteParams) (EditReleaseNoteRes, error)
	// FinishOidc implements finishOidc operation.
	//
	// Takes the code and state the provider sent back. Signs in a linked login, links the login when the
	// Account page started it, or leaves it waiting for an Account.
	//
	// POST /api/v1/oidc/callback
	FinishOidc(ctx context.Context, req *OidcCallback, params FinishOidcParams) (FinishOidcRes, error)
	// LinkOidcAccount implements linkOidcAccount operation.
	//
	// Links a login no Account has yet to the Account a Username and password sign in, and signs it in.
	//
	// POST /api/v1/oidc/links
	LinkOidcAccount(ctx context.Context, req *OidcAccountLink) (LinkOidcAccountRes, error)
	// PassTwoStep implements passTwoStep operation.
	//
	// Signs in with a code from the authenticator app or a recovery code. A challenge lasts five minutes
	// and five wrong codes.
	//
	// POST /api/v1/sign-in/two-step
	PassTwoStep(ctx context.Context, req *TwoStepAnswer) (PassTwoStepRes, error)
	// PreviewAccountInvite implements previewAccountInvite operation.
	//
	// Whether an invite link can still set up an Account; gone once used or expired.
	//
	// POST /api/v1/account-invites/preview
	PreviewAccountInvite(ctx context.Context, req *LinkToken) (PreviewAccountInviteRes, error)
	// PublishReleaseNote implements publishReleaseNote operation.
	//
	// Puts it live now, or at a later moment; once live it is announced in every bell. For Admins.
	//
	// POST /api/v1/admin/release-notes/{noteId}/publish
	PublishReleaseNote(ctx context.Context, req *ReleaseNotePublish, params PublishReleaseNoteParams) (PublishReleaseNoteRes, error)
	// ReadAllNotifications implements readAllNotifications operation.
	//
	// Clears the bell.
	//
	// POST /api/v1/notifications/read
	ReadAllNotifications(ctx context.Context) (ReadAllNotificationsRes, error)
	// ReadNotification implements readNotification operation.
	//
	// Marks one Notification read, as acting on it does.
	//
	// POST /api/v1/notifications/{notificationId}/read
	ReadNotification(ctx context.Context, params ReadNotificationParams) (ReadNotificationRes, error)
	// RequestSignInLink implements requestSignInLink operation.
	//
	// For a forgotten password. Answers the same whether or not an Account has the email.
	//
	// POST /api/v1/sign-in-links
	RequestSignInLink(ctx context.Context, req *SignInLinkRequest) (RequestSignInLinkRes, error)
	// ResetAccountTwoStep implements resetAccountTwoStep operation.
	//
	// Turns two-step off for a holder who lost their phone and recovery codes.
	//
	// POST /api/v1/admin/accounts/{accountId}/two-step/reset
	ResetAccountTwoStep(ctx context.Context, params ResetAccountTwoStepParams) (ResetAccountTwoStepRes, error)
	// ResetRecoveryCodes implements resetRecoveryCodes operation.
	//
	// Needs a current code; the old recovery codes stop working.
	//
	// POST /api/v1/account/two-step/recovery-codes
	ResetRecoveryCodes(ctx context.Context, req *TwoStepCode) (ResetRecoveryCodesRes, error)
	// RevokeAccessToken implements revokeAccessToken operation.
	//
	// The token stops working at once.
	//
	// DELETE /api/v1/account/access-tokens/{accessId}
	RevokeAccessToken(ctx context.Context, params RevokeAccessTokenParams) (RevokeAccessTokenRes, error)
	// SeeReleaseNote implements seeReleaseNote operation.
	//
	// It no longer shows on the Dashboard.
	//
	// POST /api/v1/release-notes/{noteId}/seen
	SeeReleaseNote(ctx context.Context, params SeeReleaseNoteParams) (SeeReleaseNoteRes, error)
	// SendAdminSignInLink implements sendAdminSignInLink operation.
	//
	// Sends the holder a link that signs them in once, within 30 minutes.
	//
	// POST /api/v1/admin/accounts/{accountId}/sign-in-link
	SendAdminSignInLink(ctx context.Context, params SendAdminSignInLinkParams) (SendAdminSignInLinkRes, error)
	// SendFriendRequest implements sendFriendRequest operation.
	//
	// Asks the Account with a Username to be Friends. A request they already sent is accepted at once. The
	// answer is the same whether or not they blocked the sender.
	//
	// POST /api/v1/friend-requests
	SendFriendRequest(ctx context.Context, req *FriendRequestCreate) (SendFriendRequestRes, error)
	// SendMessage implements sendMessage operation.
	//
	// Posts a message, with Mentions of game content the sender may open.
	//
	// POST /api/v1/conversations/{conversationId}/messages
	SendMessage(ctx context.Context, req *MessageSend, params SendMessageParams) (SendMessageRes, error)
	// SetAccountDisabled implements setAccountDisabled operation.
	//
	// Disabling ends every session and Access Token the Account has. Nobody disables themselves.
	//
	// PUT /api/v1/admin/accounts/{accountId}/disabled
	SetAccountDisabled(ctx context.Context, req *Toggle, params SetAccountDisabledParams) (SetAccountDisabledRes, error)
	// SetAccountPassword implements setAccountPassword operation.
	//
	// Replaces the signed-in Account's password, for example after signing in with an emailed link.
	//
	// PUT /api/v1/account/password
	SetAccountPassword(ctx context.Context, req *PasswordChange) (SetAccountPasswordRes, error)
	// SetAdminRole implements setAdminRole operation.
	//
	// Nobody removes their own Admin role.
	//
	// PUT /api/v1/admin/accounts/{accountId}/admin
	SetAdminRole(ctx context.Context, req *Toggle, params SetAdminRoleParams) (SetAdminRoleRes, error)
	// SetNotificationPreferences implements setNotificationPreferences operation.
	//
	// Sets the channels for each kind given; security Notifications always show in app.
	//
	// PUT /api/v1/notification-preferences
	SetNotificationPreferences(ctx context.Context, req *NotificationPreferences) (SetNotificationPreferencesRes, error)
	// SignIn implements signIn operation.
	//
	// Signs the Account in on this device. Every failure answers the same.
	//
	// POST /api/v1/sign-in
	SignIn(ctx context.Context, req *SignInRequest) (SignInRes, error)
	// SignOut implements signOut operation.
	//
	// Ends this device's session and clears its cookie.
	//
	// POST /api/v1/sign-out
	SignOut(ctx context.Context, params SignOutParams) (SignOutRes, error)
	// StartConversation implements startConversation operation.
	//
	// Opens a Conversation with Friends, one-to-one (found again if it exists) or a titled group of up to
	// ten.
	//
	// POST /api/v1/conversations
	StartConversation(ctx context.Context, req *ConversationStart) (StartConversationRes, error)
	// StartOidcLink implements startOidcLink operation.
	//
	// Returns where to send the browser to link a login to the signed-in Account.
	//
	// POST /api/v1/account/oidc-link
	StartOidcLink(ctx context.Context) (StartOidcLinkRes, error)
	// StartOidcSignIn implements startOidcSignIn operation.
	//
	// Returns where to send the browser, and binds the sign-in to this browser with a short-lived cookie.
	//
	// POST /api/v1/oidc/sign-ins
	StartOidcSignIn(ctx context.Context) (StartOidcSignInRes, error)
	// Unblock implements unblock operation.
	//
	// Lets the Account's Friend requests through again.
	//
	// DELETE /api/v1/blocks/{accountId}
	Unblock(ctx context.Context, params UnblockParams) (UnblockRes, error)
	// Unfriend implements unfriend operation.
	//
	// The two are no longer Friends.
	//
	// DELETE /api/v1/friends/{accountId}
	Unfriend(ctx context.Context, params UnfriendParams) (UnfriendRes, error)
	// UnlinkOidc implements unlinkOidc operation.
	//
	// Removes the linked login; the Account stays. An Account without a password keeps its login.
	//
	// DELETE /api/v1/account/oidc-link
	UnlinkOidc(ctx context.Context) (UnlinkOidcRes, error)
	// UpdateAccount implements updateAccount operation.
	//
	// Sets the signed-in Account's Username, Nickname and email. What a linked login provides stays
	// read-only.
	//
	// PUT /api/v1/account
	UpdateAccount(ctx context.Context, req *AccountChange) (UpdateAccountRes, error)
	// UseSignInLink implements useSignInLink operation.
	//
	// Signs the Account in on this device; a link works once, within 30 minutes.
	//
	// POST /api/v1/sign-in-links/use
	UseSignInLink(ctx context.Context, req *LinkToken) (UseSignInLinkRes, error)
}

// BuildHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Build
type BuildHandler interface {
	// AcceptInvite implements acceptInvite operation.
	//
	// Joins the caller to the Campaign as a Player. A Member keeps their role.
	//
	// POST /api/v1/invites/accept
	AcceptInvite(ctx context.Context, req *InviteAccept) (AcceptInviteRes, error)
	// ApproveRetrain implements approveRetrain operation.
	//
	// Checks the build again, keeps the old one as a Revision and rebuilds the Character. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/retrains/{retrainId}/approve
	ApproveRetrain(ctx context.Context, params ApproveRetrainParams) (ApproveRetrainRes, error)
	// ClearTokenIcon implements clearTokenIcon operation.
	//
	// Removes the token icon so the token shows initials. The owner or a DM, never during Combat.
	//
	// DELETE /api/v1/campaigns/{campaignId}/characters/{characterId}/token
	ClearTokenIcon(ctx context.Context, params ClearTokenIconParams) (ClearTokenIconRes, error)
	// CopySpell implements copySpell operation.
	//
	// Writes a wizard spell into the spellbook, free up to the book's allotment, otherwise for 50 gp and 2
	// hours per spell level.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/spellbook
	CopySpell(ctx context.Context, req *SpellChoice, params CopySpellParams) (CopySpellRes, error)
	// CreateCampaign implements createCampaign operation.
	//
	// Starts a Campaign with the caller as its first DM.
	//
	// POST /api/v1/campaigns
	CreateCampaign(ctx context.Context, req *CampaignCreate) (CreateCampaignRes, error)
	// CreateCharacter implements createCharacter operation.
	//
	// Builds a first-level Character owned by the caller, validated against the campaign ruleset.
	//
	// POST /api/v1/campaigns/{campaignId}/characters
	CreateCharacter(ctx context.Context, req *CharacterBuild, params CreateCharacterParams) (CreateCharacterRes, error)
	// CreateEncounterPool implements createEncounterPool operation.
	//
	// Adds an Encounter Pool and records its first Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/encounter-pools
	CreateEncounterPool(ctx context.Context, req *EncounterPoolInput, params CreateEncounterPoolParams) (CreateEncounterPoolRes, error)
	// CreateEncounterTable implements createEncounterTable operation.
	//
	// Adds an Encounter Table and records its first Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/encounter-tables
	CreateEncounterTable(ctx context.Context, req *EncounterTableInput, params CreateEncounterTableParams) (CreateEncounterTableRes, error)
	// CreateInvite implements createInvite operation.
	//
	// Opens a link that adds whoever follows it as a Player. The token is shown only once. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/invites
	CreateInvite(ctx context.Context, params CreateInviteParams) (CreateInviteRes, error)
	// CreateLibraryCollection implements createLibraryCollection operation.
	//
	// Starts an empty Collection in the caller's Library.
	//
	// POST /api/v1/library/collections
	CreateLibraryCollection(ctx context.Context, req *LibraryCollectionInput) (CreateLibraryCollectionRes, error)
	// CreateLibraryEntry implements createLibraryEntry operation.
	//
	// Adds an entry to the caller's Library as its first Revision.
	//
	// POST /api/v1/library
	CreateLibraryEntry(ctx context.Context, req *LibraryEntryInput) (CreateLibraryEntryRes, error)
	// CreateLootTable implements createLootTable operation.
	//
	// Adds a Loot Table and records its first Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/loot-tables
	CreateLootTable(ctx context.Context, req *LootTableInput, params CreateLootTableParams) (CreateLootTableRes, error)
	// CreateNpc implements createNpc operation.
	//
	// Adds an NPC and records its first Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/npcs
	CreateNpc(ctx context.Context, req *NpcInput, params CreateNpcParams) (CreateNpcRes, error)
	// CreateProposal implements createProposal operation.
	//
	// Sends the DM a new entry for the Campaign, or a change to one it sees. The DMs hear of it.
	//
	// POST /api/v1/campaigns/{campaignId}/proposals
	CreateProposal(ctx context.Context, req *ProposalInput, params CreateProposalParams) (CreateProposalRes, error)
	// CreateSettlement implements createSettlement operation.
	//
	// Adds a Settlement and records its first Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/settlements
	CreateSettlement(ctx context.Context, req *SettlementInput, params CreateSettlementParams) (CreateSettlementRes, error)
	// CreateShop implements createShop operation.
	//
	// Adds a Shop and records its first Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/shops
	CreateShop(ctx context.Context, req *ShopInput, params CreateShopParams) (CreateShopRes, error)
	// DeclineRetrain implements declineRetrain operation.
	//
	// Declines a pending retrain. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/retrains/{retrainId}/decline
	DeclineRetrain(ctx context.Context, params DeclineRetrainParams) (DeclineRetrainRes, error)
	// DeleteCharacter implements deleteCharacter operation.
	//
	// Removes a Character. The owner or a DM, never during Combat.
	//
	// DELETE /api/v1/campaigns/{campaignId}/characters/{characterId}
	DeleteCharacter(ctx context.Context, params DeleteCharacterParams) (DeleteCharacterRes, error)
	// DeleteEncounterPool implements deleteEncounterPool operation.
	//
	// Removes the Encounter Pool; its Revisions keep it restorable. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/encounter-pools/{poolId}
	DeleteEncounterPool(ctx context.Context, params DeleteEncounterPoolParams) (DeleteEncounterPoolRes, error)
	// DeleteEncounterTable implements deleteEncounterTable operation.
	//
	// Removes the Encounter Table; its Revisions keep it restorable. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/encounter-tables/{tableId}
	DeleteEncounterTable(ctx context.Context, params DeleteEncounterTableParams) (DeleteEncounterTableRes, error)
	// DeleteLootTable implements deleteLootTable operation.
	//
	// Removes the Loot Table; its Revisions keep it restorable. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/loot-tables/{lootTableId}
	DeleteLootTable(ctx context.Context, params DeleteLootTableParams) (DeleteLootTableRes, error)
	// DeleteNpc implements deleteNpc operation.
	//
	// Removes the NPC; its Revisions keep it restorable. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/npcs/{npcId}
	DeleteNpc(ctx context.Context, params DeleteNpcParams) (DeleteNpcRes, error)
	// DeleteSettlement implements deleteSettlement operation.
	//
	// Removes the Settlement; its Revisions keep it restorable. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/settlements/{settlementId}
	DeleteSettlement(ctx context.Context, params DeleteSettlementParams) (DeleteSettlementRes, error)
	// DeleteShop implements deleteShop operation.
	//
	// Removes the Shop; its Revisions keep it restorable. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/shops/{shopId}
	DeleteShop(ctx context.Context, params DeleteShopParams) (DeleteShopRes, error)
	// DiscardCharacterDraft implements discardCharacterDraft operation.
	//
	// Starts the wizard over.
	//
	// DELETE /api/v1/campaigns/{campaignId}/character-draft
	DiscardCharacterDraft(ctx context.Context, params DiscardCharacterDraftParams) (DiscardCharacterDraftRes, error)
	// JoinCampaign implements joinCampaign operation.
	//
	// Adds the Character to a Campaign the signed-in Account belongs to, with its build checked against
	// that Campaign's rules and its own progress from first level.
	//
	// POST /api/v1/characters/{characterId}/campaigns
	JoinCampaign(ctx context.Context, req *CharacterJoin, params JoinCampaignParams) (JoinCampaignRes, error)
	// LevelUp implements levelUp operation.
	//
	// Takes the unlocked next level with its choices, multiclassing when the prerequisites hold.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/level-up
	LevelUp(ctx context.Context, req *LevelUpRequest, params LevelUpParams) (LevelUpRes, error)
	// LinkLibraryEntry implements linkLibraryEntry operation.
	//
	// Links one of the caller's entries into a Campaign they run; linking it again changes nothing. DM
	// only.
	//
	// POST /api/v1/campaigns/{campaignId}/library
	LinkLibraryEntry(ctx context.Context, req *LibraryLinkInput, params LinkLibraryEntryParams) (LinkLibraryEntryRes, error)
	// PinLibraryRevision implements pinLibraryRevision operation.
	//
	// Holds the Campaign to one Revision of the entry, so later edits to its base pass the Campaign by. DM
	// only.
	//
	// PUT /api/v1/campaigns/{campaignId}/library/{entryId}/pin
	PinLibraryRevision(ctx context.Context, req *LibraryPinInput, params PinLibraryRevisionParams) (PinLibraryRevisionRes, error)
	// PrepareSpells implements prepareSpells operation.
	//
	// Sets the spells prepared through one class within its limit, after a long rest or a new level.
	//
	// PUT /api/v1/campaigns/{campaignId}/characters/{characterId}/spells/prepared
	PrepareSpells(ctx context.Context, req *SpellPreparation, params PrepareSpellsParams) (PrepareSpellsRes, error)
	// PreviewCharacter implements previewCharacter operation.
	//
	// Validates a build and returns the sheet it would make, without saving it.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/preview
	PreviewCharacter(ctx context.Context, req *CharacterBuild, params PreviewCharacterParams) (PreviewCharacterRes, error)
	// PreviewInvite implements previewInvite operation.
	//
	// Which Campaign an invite link leads to, before joining.
	//
	// POST /api/v1/invites/preview
	PreviewInvite(ctx context.Context, req *InviteToken) (PreviewInviteRes, error)
	// PreviewReach implements previewReach operation.
	//
	// Every hex a mover can reach and, with a target, the cheapest path to it. Changes nothing.
	//
	// POST /api/v1/rules/hex/reach
	PreviewReach(ctx context.Context, req *ReachRequest) (PreviewReachRes, error)
	// PreviewSight implements previewSight operation.
	//
	// Whether one hex can see another and the cover in between. Changes nothing.
	//
	// POST /api/v1/rules/hex/sight
	PreviewSight(ctx context.Context, req *SightRequest) (PreviewSightRes, error)
	// RemoveMember implements removeMember operation.
	//
	// A DM removes a Member, or a Member leaves. The last DM cannot leave.
	//
	// DELETE /api/v1/campaigns/{campaignId}/members/{memberId}
	RemoveMember(ctx context.Context, params RemoveMemberParams) (RemoveMemberRes, error)
	// RequestRetrain implements requestRetrain operation.
	//
	// Proposes a rebuilt build for the DM to approve (origin, ability scores, class skills, new values for
	// each level's picks, and Ability Score Improvements). The owner only.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/retrains
	RequestRetrain(ctx context.Context, req *RetrainRequest, params RequestRetrainParams) (RequestRetrainRes, error)
	// RerollStock implements rerollStock operation.
	//
	// Generates the Shop's Stock afresh from its Loot Table, scaled by its Settlement, and records it as a
	// Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/shops/{shopId}/stock
	RerollStock(ctx context.Context, params RerollStockParams) (RerollStockRes, error)
	// RestoreEncounterPoolRevision implements restoreEncounterPoolRevision operation.
	//
	// Brings the Encounter Pool back to a Revision, recreating it if deleted; the restore is itself a
	// Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/encounter-pools/{poolId}/revisions/{revisionNo}/restore
	RestoreEncounterPoolRevision(ctx context.Context, params RestoreEncounterPoolRevisionParams) (RestoreEncounterPoolRevisionRes, error)
	// RestoreEncounterTableRevision implements restoreEncounterTableRevision operation.
	//
	// Brings the Encounter Table back to a Revision, recreating it if deleted; the restore is itself a
	// Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/encounter-tables/{tableId}/revisions/{revisionNo}/restore
	RestoreEncounterTableRevision(ctx context.Context, params RestoreEncounterTableRevisionParams) (RestoreEncounterTableRevisionRes, error)
	// RestoreLootTableRevision implements restoreLootTableRevision operation.
	//
	// Brings the Loot Table back to a Revision, recreating it if deleted; the restore is itself a
	// Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/loot-tables/{lootTableId}/revisions/{revisionNo}/restore
	RestoreLootTableRevision(ctx context.Context, params RestoreLootTableRevisionParams) (RestoreLootTableRevisionRes, error)
	// RestoreNpcRevision implements restoreNpcRevision operation.
	//
	// Brings the NPC back to a Revision, recreating it if deleted; the restore is itself a Revision. DM
	// only.
	//
	// POST /api/v1/campaigns/{campaignId}/npcs/{npcId}/revisions/{revisionNo}/restore
	RestoreNpcRevision(ctx context.Context, params RestoreNpcRevisionParams) (RestoreNpcRevisionRes, error)
	// RestoreSettlementRevision implements restoreSettlementRevision operation.
	//
	// Brings the Settlement back to a Revision, recreating it if deleted; the restore is itself a
	// Revision. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/settlements/{settlementId}/revisions/{revisionNo}/restore
	RestoreSettlementRevision(ctx context.Context, params RestoreSettlementRevisionParams) (RestoreSettlementRevisionRes, error)
	// RestoreShopRevision implements restoreShopRevision operation.
	//
	// Brings the Shop back to a Revision, recreating it if deleted; the restore is itself a Revision. DM
	// only.
	//
	// POST /api/v1/campaigns/{campaignId}/shops/{shopId}/revisions/{revisionNo}/restore
	RestoreShopRevision(ctx context.Context, params RestoreShopRevisionParams) (RestoreShopRevisionRes, error)
	// ResubmitProposal implements resubmitProposal operation.
	//
	// Its author sends a Proposal the DM asked changes to again, changed.
	//
	// PUT /api/v1/campaigns/{campaignId}/proposals/{proposalId}
	ResubmitProposal(ctx context.Context, req *ProposalUpdate, params ResubmitProposalParams) (ResubmitProposalRes, error)
	// ReviewProposal implements reviewProposal operation.
	//
	// A DM approves a pending Proposal (copied once into their Library and linked into the Campaign
	// Collection, edited first if they like), asks for changes with a message, or declines it. The author
	// hears either way.
	//
	// POST /api/v1/campaigns/{campaignId}/proposals/{proposalId}/review
	ReviewProposal(ctx context.Context, req *ProposalReviewInput, params ReviewProposalParams) (ReviewProposalRes, error)
	// RevokeInvite implements revokeInvite operation.
	//
	// Closes an invite link. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/invites/{inviteId}
	RevokeInvite(ctx context.Context, params RevokeInviteParams) (RevokeInviteRes, error)
	// RollCharacterScores implements rollCharacterScores operation.
	//
	// Rolls six scores of 4d6 dropping the lowest, once per draft, when the Campaign allows rolling.
	//
	// POST /api/v1/campaigns/{campaignId}/character-draft/roll
	RollCharacterScores(ctx context.Context, params RollCharacterScoresParams) (RollCharacterScoresRes, error)
	// SaveCharacterDraft implements saveCharacterDraft operation.
	//
	// Keeps the wizard's choices so the caller can come back to them; rolled scores stay as the server
	// rolled them.
	//
	// PUT /api/v1/campaigns/{campaignId}/character-draft
	SaveCharacterDraft(ctx context.Context, req *CharacterDraftSave, params SaveCharacterDraftParams) (SaveCharacterDraftRes, error)
	// SetCampaignOverride implements setCampaignOverride operation.
	//
	// Replaces the fields this Campaign sees differently from the entry's base. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/library/{entryId}/override
	SetCampaignOverride(ctx context.Context, req *CampaignOverrideInput, params SetCampaignOverrideParams) (SetCampaignOverrideRes, error)
	// SetPortrait implements setPortrait operation.
	//
	// A PNG, JPEG or WebP picture of at most 10 MB. The owner or a DM, never during Combat.
	//
	// PUT /api/v1/campaigns/{campaignId}/characters/{characterId}/portrait
	SetPortrait(ctx context.Context, req SetPortraitReq, params SetPortraitParams) (SetPortraitRes, error)
	// SetTokenIcon implements setTokenIcon operation.
	//
	// A PNG, JPEG or WebP picture of at most 10 MB. The owner or a DM, never during Combat.
	//
	// PUT /api/v1/campaigns/{campaignId}/characters/{characterId}/token
	SetTokenIcon(ctx context.Context, req SetTokenIconReq, params SetTokenIconParams) (SetTokenIconRes, error)
	// SwitchLibraryCollection implements switchLibraryCollection operation.
	//
	// On brings the Collection's entries into the Campaign; off hides those not linked otherwise. Only its
	// owner switches it on; any DM of the Campaign switches it off.
	//
	// PUT /api/v1/campaigns/{campaignId}/collections/{collectionId}
	SwitchLibraryCollection(ctx context.Context, req *LibrarySwitchInput, params SwitchLibraryCollectionParams) (SwitchLibraryCollectionRes, error)
	// UndoChange implements undoChange operation.
	//
	// Undoes a prep change by its Revision id. A creation is deleted; anything else is restored to the
	// Revision before it. Only an entity's latest change can be undone. The undo is itself a Revision. DM
	// only.
	//
	// POST /api/v1/campaigns/{campaignId}/activity/{revisionId}/undo
	UndoChange(ctx context.Context, params UndoChangeParams) (UndoChangeRes, error)
	// UnlinkLibraryEntry implements unlinkLibraryEntry operation.
	//
	// Takes the entry out of the Campaign with its Campaign Override; the entry stays in the Library. DM
	// only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/library/{entryId}
	UnlinkLibraryEntry(ctx context.Context, params UnlinkLibraryEntryParams) (UnlinkLibraryEntryRes, error)
	// UnpinLibraryRevision implements unpinLibraryRevision operation.
	//
	// The Campaign follows the entry's latest Revision again. DM only.
	//
	// DELETE /api/v1/campaigns/{campaignId}/library/{entryId}/pin
	UnpinLibraryRevision(ctx context.Context, params UnpinLibraryRevisionParams) (UnpinLibraryRevisionRes, error)
	// UpdateCampaign implements updateCampaign operation.
	//
	// Changes a Campaign's settings. DM only.
	//
	// PATCH /api/v1/campaigns/{campaignId}
	UpdateCampaign(ctx context.Context, req *CampaignUpdate, params UpdateCampaignParams) (UpdateCampaignRes, error)
	// UpdateCharacter implements updateCharacter operation.
	//
	// Out-of-combat changes by the owner or a DM; refused with 409 while the Character is in Combat.
	//
	// PATCH /api/v1/campaigns/{campaignId}/characters/{characterId}
	UpdateCharacter(ctx context.Context, req *CharacterEdit, params UpdateCharacterParams) (UpdateCharacterRes, error)
	// UpdateEncounterPool implements updateEncounterPool operation.
	//
	// Replaces the Encounter Pool and records a Revision. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/encounter-pools/{poolId}
	UpdateEncounterPool(ctx context.Context, req *EncounterPoolInput, params UpdateEncounterPoolParams) (UpdateEncounterPoolRes, error)
	// UpdateEncounterTable implements updateEncounterTable operation.
	//
	// Replaces the Encounter Table and records a Revision. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/encounter-tables/{tableId}
	UpdateEncounterTable(ctx context.Context, req *EncounterTableInput, params UpdateEncounterTableParams) (UpdateEncounterTableRes, error)
	// UpdateLibraryCollection implements updateLibraryCollection operation.
	//
	// Renames one of the caller's Collections and sets which of their entries it holds; every Campaign it
	// is switched on in sees the new set.
	//
	// PUT /api/v1/library/collections/{collectionId}
	UpdateLibraryCollection(ctx context.Context, req *LibraryCollectionUpdate, params UpdateLibraryCollectionParams) (UpdateLibraryCollectionRes, error)
	// UpdateLibraryEntry implements updateLibraryEntry operation.
	//
	// Saves a new base as the entry's next Revision. Every Campaign that follows the latest Revision sees
	// it; a pinned Campaign does not.
	//
	// PUT /api/v1/library/{entryId}
	UpdateLibraryEntry(ctx context.Context, req *LibraryEntryUpdate, params UpdateLibraryEntryParams) (UpdateLibraryEntryRes, error)
	// UpdateLootTable implements updateLootTable operation.
	//
	// Replaces the Loot Table and records a Revision. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/loot-tables/{lootTableId}
	UpdateLootTable(ctx context.Context, req *LootTableInput, params UpdateLootTableParams) (UpdateLootTableRes, error)
	// UpdateMap implements updateMap operation.
	//
	// Renames a Map and sets its hex size, grid origin and ambient light. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/maps/{mapId}
	UpdateMap(ctx context.Context, req *MapEdit, params UpdateMapParams) (UpdateMapRes, error)
	// UpdateMember implements updateMember operation.
	//
	// Makes a Member a DM or a Player. DM only; the last DM cannot step down.
	//
	// PATCH /api/v1/campaigns/{campaignId}/members/{memberId}
	UpdateMember(ctx context.Context, req *MemberUpdate, params UpdateMemberParams) (UpdateMemberRes, error)
	// UpdateMyCharacter implements updateMyCharacter operation.
	//
	// Sets a Character's name and Backstory; the name shows in every Campaign it plays in.
	//
	// PUT /api/v1/characters/{characterId}
	UpdateMyCharacter(ctx context.Context, req *OwnedCharacterChange, params UpdateMyCharacterParams) (UpdateMyCharacterRes, error)
	// UpdateNpc implements updateNpc operation.
	//
	// Replaces the NPC and records a Revision. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/npcs/{npcId}
	UpdateNpc(ctx context.Context, req *NpcInput, params UpdateNpcParams) (UpdateNpcRes, error)
	// UpdateSettlement implements updateSettlement operation.
	//
	// Replaces the Settlement and records a Revision. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/settlements/{settlementId}
	UpdateSettlement(ctx context.Context, req *SettlementInput, params UpdateSettlementParams) (UpdateSettlementRes, error)
	// UpdateShop implements updateShop operation.
	//
	// Replaces the Shop and records a Revision. DM only.
	//
	// PUT /api/v1/campaigns/{campaignId}/shops/{shopId}
	UpdateShop(ctx context.Context, req *ShopInput, params UpdateShopParams) (UpdateShopRes, error)
	// UploadMap implements uploadMap operation.
	//
	// A PNG, JPEG or WebP picture of at most 25 MB and 36 megapixels, with a default hex calibration. DM
	// only.
	//
	// POST /api/v1/campaigns/{campaignId}/maps
	UploadMap(ctx context.Context, req UploadMapReq, params UploadMapParams) (UploadMapRes, error)
}

// PlayHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Play
type PlayHandler interface {
	// CastRitual implements castRitual operation.
	//
	// Casts a prepared ritual spell out of combat without a slot, adding its casting time and 10 minutes
	// to the Game Clock.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/spells/rituals
	CastRitual(ctx context.Context, req *SpellChoice, params CastRitualParams) (CastRitualRes, error)
	// CreateRoll implements createRoll operation.
	//
	// Opens a Roll Request for the caller, or, from a DM, for another Member.
	//
	// POST /api/v1/campaigns/{campaignId}/rolls
	CreateRoll(ctx context.Context, req *RollCreate, params CreateRollParams) (CreateRollRes, error)
	// EndSession implements endSession operation.
	//
	// Ends a live Session and disconnects everyone. DM only.
	//
	// POST /api/v1/campaigns/{campaignId}/sessions/{sessionId}/end
	EndSession(ctx context.Context, params EndSessionParams) (EndSessionRes, error)
	// KeepRoll implements keepRoll operation.
	//
	// Keeps a roll its roller could reroll with Heroic Inspiration, and resolves it. The roller or a DM.
	//
	// POST /api/v1/campaigns/{campaignId}/rolls/{rollId}/keep
	KeepRoll(ctx context.Context, params KeepRollParams) (KeepRollRes, error)
	// MoveItem implements moveItem operation.
	//
	// Puts an item in a slot, back in the bag, with another Character or in the Party Stash. Not during a
	// live Session.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/inventory/move
	MoveItem(ctx context.Context, req *InventoryMove, params MoveItemParams) (MoveItemRes, error)
	// PassInspiration implements passInspiration operation.
	//
	// Gives the Character's Heroic Inspiration to another Character in the Campaign that lacks it. The
	// owner only.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/inspiration/pass
	PassInspiration(ctx context.Context, req *InspirationPass, params PassInspirationParams) (PassInspirationRes, error)
	// RerollDie implements rerollDie operation.
	//
	// Spends the roller's Heroic Inspiration to roll one die again; the new face stands and the roll
	// resolves. The roller only.
	//
	// POST /api/v1/campaigns/{campaignId}/rolls/{rollId}/reroll
	RerollDie(ctx context.Context, req *RerollIn, params RerollDieParams) (RerollDieRes, error)
	// RollRest implements rollRest operation.
	//
	// The server rolls every die still empty. The roller or a DM.
	//
	// POST /api/v1/campaigns/{campaignId}/rolls/{rollId}/rest
	RollRest(ctx context.Context, params RollRestParams) (RollRestRes, error)
	// SendLiveCommand implements sendLiveCommand operation.
	//
	// Sends one command to a live Session as the caller, with the same authority as their live connection,
	// and answers once the Session has applied it. Members only.
	//
	// POST /api/v1/campaigns/{campaignId}/sessions/{sessionId}/commands
	SendLiveCommand(ctx context.Context, req *LiveCommand, params SendLiveCommandParams) (SendLiveCommandRes, error)
	// SetDie implements setDie operation.
	//
	// The server rolls the die from a logged seed, or takes the face read off a physical die. The roller
	// or a DM; the last die resolves the request.
	//
	// POST /api/v1/campaigns/{campaignId}/rolls/{rollId}/dice/{dieNo}
	SetDie(ctx context.Context, req *DieFill, params SetDieParams) (SetDieRes, error)
	// StartSession implements startSession operation.
	//
	// Opens the next live Session. DM only. Live play then runs over the WebSocket at
	// /api/v1/campaigns/{campaignId}/sessions/{sessionId}/live?audience=dm|party|table, whose messages are
	// LiveCommand and LiveUpdate.
	//
	// POST /api/v1/campaigns/{campaignId}/sessions
	StartSession(ctx context.Context, params StartSessionParams) (StartSessionRes, error)
	// SwapWeaponSet implements swapWeaponSet operation.
	//
	// Changes the weapon set in hand between melee and ranged outside a fight. In a live Session the swap
	// is a command that pays the 2024 equip rules.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/inventory/swap
	SwapWeaponSet(ctx context.Context, params SwapWeaponSetParams) (SwapWeaponSetRes, error)
	// TakeFromStash implements takeFromStash operation.
	//
	// Moves an item from the Party Stash into the Character's bag. Not during a live Session.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/inventory/take
	TakeFromStash(ctx context.Context, req *InventoryTake, params TakeFromStashParams) (TakeFromStashRes, error)
	// UseItem implements useItem operation.
	//
	// Drinks a potion, throws an item away, attunes or unattunes it (three at most), identifies it, or
	// spends its charges. Not during a live Session.
	//
	// POST /api/v1/campaigns/{campaignId}/characters/{characterId}/inventory/use
	UseItem(ctx context.Context, req *InventoryUse, params UseItemParams) (UseItemRes, error)
}

// ReadHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Read
type ReadHandler interface {
	// DiffNpcRevisions implements diffNpcRevisions operation.
	//
	// The fields that differ between two Revisions. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/npcs/{npcId}/revisions/diff
	DiffNpcRevisions(ctx context.Context, params DiffNpcRevisionsParams) (DiffNpcRevisionsRes, error)
	// GetAccount implements getAccount operation.
	//
	// The Account the caller is signed in as.
	//
	// GET /api/v1/account
	GetAccount(ctx context.Context) (GetAccountRes, error)
	// GetAccountHistory implements getAccountHistory operation.
	//
	// What happened to the signed-in Account and who did it, newest first.
	//
	// GET /api/v1/account/history
	GetAccountHistory(ctx context.Context) (GetAccountHistoryRes, error)
	// GetActionLog implements getActionLog operation.
	//
	// The Campaign's recent Actions with their seeds. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/log
	GetActionLog(ctx context.Context, params GetActionLogParams) (GetActionLogRes, error)
	// GetAdminAccount implements getAdminAccount operation.
	//
	// How the Account signs in, its live sessions and Access Tokens, its Campaigns and its history.
	//
	// GET /api/v1/admin/accounts/{accountId}
	GetAdminAccount(ctx context.Context, params GetAdminAccountParams) (GetAdminAccountRes, error)
	// GetAutomationCoverage implements getAutomationCoverage operation.
	//
	// How many entries of each kind the rules engine computes fully, partly, or leaves to the DM.
	//
	// GET /api/v1/compendium/automation
	GetAutomationCoverage(ctx context.Context, params GetAutomationCoverageParams) (GetAutomationCoverageRes, error)
	// GetBuilderOptions implements getBuilderOptions operation.
	//
	// Every class, species, background, armour and weapon a first-level character can choose in one
	// ruleset.
	//
	// GET /api/v1/compendium/builder
	GetBuilderOptions(ctx context.Context, params GetBuilderOptionsParams) (GetBuilderOptionsRes, error)
	// GetCampaign implements getCampaign operation.
	//
	// A Campaign's home with its settings, the caller's role and every Member. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}
	GetCampaign(ctx context.Context, params GetCampaignParams) (GetCampaignRes, error)
	// GetCharacter implements getCharacter operation.
	//
	// A Character's sheet. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}
	GetCharacter(ctx context.Context, params GetCharacterParams) (GetCharacterRes, error)
	// GetCharacterDraft implements getCharacterDraft operation.
	//
	// The Character the caller is making in this Campaign's wizard, with the step reached, the choices so
	// far and any rolled scores.
	//
	// GET /api/v1/campaigns/{campaignId}/character-draft
	GetCharacterDraft(ctx context.Context, params GetCharacterDraftParams) (GetCharacterDraftRes, error)
	// GetEntry implements getEntry operation.
	//
	// One entry rendered for reading, with the conditions its text mentions.
	//
	// GET /api/v1/compendium/entries/{kind}/{slug}
	GetEntry(ctx context.Context, params GetEntryParams) (GetEntryRes, error)
	// GetHealth implements getHealth operation.
	//
	// Returns ok while the process is serving requests.
	//
	// GET /healthz
	GetHealth(ctx context.Context) (GetHealthRes, error)
	// GetInventory implements getInventory operation.
	//
	// Equipment slots, the bag, weight against carrying capacity, and the Party Stash. Its player or a DM.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/inventory
	GetInventory(ctx context.Context, params GetInventoryParams) (GetInventoryRes, error)
	// GetLibraryEntry implements getLibraryEntry operation.
	//
	// One of the caller's entries with its Revisions and the Campaigns it is linked into.
	//
	// GET /api/v1/library/{entryId}
	GetLibraryEntry(ctx context.Context, params GetLibraryEntryParams) (GetLibraryEntryRes, error)
	// GetMap implements getMap operation.
	//
	// One Map with its calibration. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/maps/{mapId}
	GetMap(ctx context.Context, params GetMapParams) (GetMapRes, error)
	// GetMapImage implements getMapImage operation.
	//
	// The whole picture for a DM; for everyone else a PNG with every hex the party has never seen painted
	// black on the server.
	//
	// GET /api/v1/campaigns/{campaignId}/maps/{mapId}/image
	GetMapImage(ctx context.Context, params GetMapImageParams) (GetMapImageRes, error)
	// GetMe implements getMe operation.
	//
	// Returns the identity the platform authenticated for this request.
	//
	// GET /api/v1/me
	GetMe(ctx context.Context) (GetMeRes, error)
	// GetMyCharacter implements getMyCharacter operation.
	//
	// A Character the signed-in Account owns; anyone else's is not found.
	//
	// GET /api/v1/characters/{characterId}
	GetMyCharacter(ctx context.Context, params GetMyCharacterParams) (GetMyCharacterRes, error)
	// GetNotificationPreferences implements getNotificationPreferences operation.
	//
	// Which kinds reach the signed-in Account in app, on its devices and by email.
	//
	// GET /api/v1/notification-preferences
	GetNotificationPreferences(ctx context.Context) (GetNotificationPreferencesRes, error)
	// GetNpc implements getNpc operation.
	//
	// One NPC. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/npcs/{npcId}
	GetNpc(ctx context.Context, params GetNpcParams) (GetNpcRes, error)
	// GetPortrait implements getPortrait operation.
	//
	// The picture itself, served only to Members of the Campaign.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/portrait
	GetPortrait(ctx context.Context, params GetPortraitParams) (GetPortraitRes, error)
	// GetProposal implements getProposal operation.
	//
	// One Proposal with its history and, for a change, the entry as the Campaign sees it now. Its author
	// or a DM.
	//
	// GET /api/v1/campaigns/{campaignId}/proposals/{proposalId}
	GetProposal(ctx context.Context, params GetProposalParams) (GetProposalRes, error)
	// GetPushKey implements getPushKey operation.
	//
	// The server's VAPID public key, for a device to subscribe to notifications with. Not found when the
	// server sends none.
	//
	// GET /api/v1/push/key
	GetPushKey(ctx context.Context) (GetPushKeyRes, error)
	// GetReadiness implements getReadiness operation.
	//
	// Returns ok once the API can serve traffic.
	//
	// GET /readyz
	GetReadiness(ctx context.Context) (GetReadinessRes, error)
	// GetRoll implements getRoll operation.
	//
	// One Roll Request with every die. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}/rolls/{rollId}
	GetRoll(ctx context.Context, params GetRollParams) (GetRollRes, error)
	// GetSession implements getSession operation.
	//
	// One Session. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}/sessions/{sessionId}
	GetSession(ctx context.Context, params GetSessionParams) (GetSessionRes, error)
	// GetSessionLog implements getSessionLog operation.
	//
	// The Session's latest Actions, newest first, and whether each can still be undone. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/sessions/{sessionId}/log
	GetSessionLog(ctx context.Context, params GetSessionLogParams) (GetSessionLogRes, error)
	// GetSessionView implements getSessionView operation.
	//
	// What the caller may see of a live Session now; the DM sees everything. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}/sessions/{sessionId}/view
	GetSessionView(ctx context.Context, params GetSessionViewParams) (GetSessionViewRes, error)
	// GetSignInMethods implements getSignInMethods operation.
	//
	// Which external sign-in, if any, the sign-in page offers beside a password.
	//
	// GET /api/v1/sign-in-methods
	GetSignInMethods(ctx context.Context) (GetSignInMethodsRes, error)
	// GetSpell implements getSpell operation.
	//
	// One spell with its rules text and the conditions it mentions.
	//
	// GET /api/v1/compendium/spells/{slug}
	GetSpell(ctx context.Context, params GetSpellParams) (GetSpellRes, error)
	// GetSpellcasting implements getSpellcasting operation.
	//
	// Cantrips, prepared and always-prepared spells per class, a wizard's spellbook, coins and the Game
	// Clock.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/spells
	GetSpellcasting(ctx context.Context, params GetSpellcastingParams) (GetSpellcastingRes, error)
	// GetStatus implements getStatus operation.
	//
	// Reports the running version and whether the database answers.
	//
	// GET /api/v1/status
	GetStatus(ctx context.Context) (GetStatusRes, error)
	// GetTokenIcon implements getTokenIcon operation.
	//
	// The picture itself, served only to Members of the Campaign.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/token
	GetTokenIcon(ctx context.Context, params GetTokenIconParams) (GetTokenIconRes, error)
	// GetUnseenReleaseNote implements getUnseenReleaseNote operation.
	//
	// The newest live Release Note the signed-in Account has not seen yet, for its Dashboard.
	//
	// GET /api/v1/release-notes/unseen
	GetUnseenReleaseNote(ctx context.Context) (GetUnseenReleaseNoteRes, error)
	// ListAccessTokens implements listAccessTokens operation.
	//
	// The signed-in Account's live Access Tokens, newest first, with when each was last used.
	//
	// GET /api/v1/account/access-tokens
	ListAccessTokens(ctx context.Context) (ListAccessTokensRes, error)
	// ListActivity implements listActivity operation.
	//
	// The latest prep changes made through MCP, newest first, and whether each can still be undone. DM
	// only.
	//
	// GET /api/v1/campaigns/{campaignId}/activity
	ListActivity(ctx context.Context, params ListActivityParams) (ListActivityRes, error)
	// ListAdminAccounts implements listAdminAccounts operation.
	//
	// Every Account with its status, and every Invite nobody has used yet. For Admins.
	//
	// GET /api/v1/admin/accounts
	ListAdminAccounts(ctx context.Context) (ListAdminAccountsRes, error)
	// ListCampaignCollections implements listCampaignCollections operation.
	//
	// The caller's Collections and any other switched on in the Campaign, each saying whether it is on
	// there. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/collections
	ListCampaignCollections(ctx context.Context, params ListCampaignCollectionsParams) (ListCampaignCollectionsRes, error)
	// ListCampaigns implements listCampaigns operation.
	//
	// The Campaigns the caller is a Member of, newest first.
	//
	// GET /api/v1/campaigns
	ListCampaigns(ctx context.Context, params ListCampaignsParams) (ListCampaignsRes, error)
	// ListCharacterRevisions implements listCharacterRevisions operation.
	//
	// The builds approved retrains replaced, newest first. Its owner or a DM.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/revisions
	ListCharacterRevisions(ctx context.Context, params ListCharacterRevisionsParams) (ListCharacterRevisionsRes, error)
	// ListCharacters implements listCharacters operation.
	//
	// The party's Characters. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}/characters
	ListCharacters(ctx context.Context, params ListCharactersParams) (ListCharactersRes, error)
	// ListConversations implements listConversations operation.
	//
	// The signed-in Account's Conversations, newest first, with how many messages each has unread.
	//
	// GET /api/v1/conversations
	ListConversations(ctx context.Context) (ListConversationsRes, error)
	// ListDeletedNpcs implements listDeletedNpcs operation.
	//
	// NPCs that were deleted and can still be restored from their Revisions. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/npcs/deleted
	ListDeletedNpcs(ctx context.Context, params ListDeletedNpcsParams) (ListDeletedNpcsRes, error)
	// ListEncounterChecks implements listEncounterChecks operation.
	//
	// The Campaign's latest 100 Encounter Checks with their seeds and what they produced. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/encounter-checks
	ListEncounterChecks(ctx context.Context, params ListEncounterChecksParams) (ListEncounterChecksRes, error)
	// ListEncounterPoolRevisions implements listEncounterPoolRevisions operation.
	//
	// Every Revision of the Encounter Pool, newest first. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/encounter-pools/{poolId}/revisions
	ListEncounterPoolRevisions(ctx context.Context, params ListEncounterPoolRevisionsParams) (ListEncounterPoolRevisionsRes, error)
	// ListEncounterPools implements listEncounterPools operation.
	//
	// The Campaign's Encounter Pools. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/encounter-pools
	ListEncounterPools(ctx context.Context, params ListEncounterPoolsParams) (ListEncounterPoolsRes, error)
	// ListEncounterTableRevisions implements listEncounterTableRevisions operation.
	//
	// Every Revision of the Encounter Table, newest first. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/encounter-tables/{tableId}/revisions
	ListEncounterTableRevisions(ctx context.Context, params ListEncounterTableRevisionsParams) (ListEncounterTableRevisionsRes, error)
	// ListEncounterTables implements listEncounterTables operation.
	//
	// The Campaign's Encounter Tables. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/encounter-tables
	ListEncounterTables(ctx context.Context, params ListEncounterTablesParams) (ListEncounterTablesRes, error)
	// ListEntries implements listEntries operation.
	//
	// Entries of one kind in name order, one page at a time. Without a ruleset the 2024 rules lead the
	// blend.
	//
	// GET /api/v1/compendium/entries
	ListEntries(ctx context.Context, params ListEntriesParams) (ListEntriesRes, error)
	// ListFriends implements listFriends operation.
	//
	// The signed-in Account's Friends, Friend requests both ways, and the Accounts it blocked.
	//
	// GET /api/v1/friends
	ListFriends(ctx context.Context) (ListFriendsRes, error)
	// ListInvites implements listInvites operation.
	//
	// Invite links that still work. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/invites
	ListInvites(ctx context.Context, params ListInvitesParams) (ListInvitesRes, error)
	// ListLibraryCollections implements listLibraryCollections operation.
	//
	// The caller's Collections.
	//
	// GET /api/v1/library/collections
	ListLibraryCollections(ctx context.Context) (ListLibraryCollectionsRes, error)
	// ListLibraryEntries implements listLibraryEntries operation.
	//
	// The caller's Library entries in kind and name order.
	//
	// GET /api/v1/library
	ListLibraryEntries(ctx context.Context, params ListLibraryEntriesParams) (ListLibraryEntriesRes, error)
	// ListLinkedEntries implements listLinkedEntries operation.
	//
	// The Library entries linked into the Campaign, each with its Campaign Override and pinned Revision
	// resolved. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/library
	ListLinkedEntries(ctx context.Context, params ListLinkedEntriesParams) (ListLinkedEntriesRes, error)
	// ListLocations implements listLocations operation.
	//
	// The places on the Campaign's world maps an Encounter Table can belong to. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/locations
	ListLocations(ctx context.Context, params ListLocationsParams) (ListLocationsRes, error)
	// ListLootTableRevisions implements listLootTableRevisions operation.
	//
	// Every Revision of the Loot Table, newest first. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/loot-tables/{lootTableId}/revisions
	ListLootTableRevisions(ctx context.Context, params ListLootTableRevisionsParams) (ListLootTableRevisionsRes, error)
	// ListLootTables implements listLootTables operation.
	//
	// The Campaign's Loot Tables. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/loot-tables
	ListLootTables(ctx context.Context, params ListLootTablesParams) (ListLootTablesRes, error)
	// ListMaps implements listMaps operation.
	//
	// The Campaign's local and world Maps. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/maps
	ListMaps(ctx context.Context, params ListMapsParams) (ListMapsRes, error)
	// ListMentionables implements listMentionables operation.
	//
	// Characters in the caller's Campaigns and Locations in Campaigns they run, matching a few letters.
	//
	// GET /api/v1/mentionables
	ListMentionables(ctx context.Context, params ListMentionablesParams) (ListMentionablesRes, error)
	// ListMessages implements listMessages operation.
	//
	// A page of messages, newest first; reading the newest page marks the Conversation read. Only members
	// read it.
	//
	// GET /api/v1/conversations/{conversationId}/messages
	ListMessages(ctx context.Context, params ListMessagesParams) (ListMessagesRes, error)
	// ListMyCharacters implements listMyCharacters operation.
	//
	// The Characters the signed-in Account owns, each with its progress in every Campaign it plays in.
	//
	// GET /api/v1/characters
	ListMyCharacters(ctx context.Context) (ListMyCharactersRes, error)
	// ListNotifications implements listNotifications operation.
	//
	// The latest Notifications in the signed-in Account's bell, newest first, and how many are unread.
	//
	// GET /api/v1/notifications
	ListNotifications(ctx context.Context) (ListNotificationsRes, error)
	// ListNpcRevisions implements listNpcRevisions operation.
	//
	// Every Revision of the NPC, newest first, with its author and origin. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/npcs/{npcId}/revisions
	ListNpcRevisions(ctx context.Context, params ListNpcRevisionsParams) (ListNpcRevisionsRes, error)
	// ListNpcs implements listNpcs operation.
	//
	// The Campaign's NPCs. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/npcs
	ListNpcs(ctx context.Context, params ListNpcsParams) (ListNpcsRes, error)
	// ListProposals implements listProposals operation.
	//
	// The Campaign's Proposals, newest first: every one for a DM, a Player's own otherwise.
	//
	// GET /api/v1/campaigns/{campaignId}/proposals
	ListProposals(ctx context.Context, params ListProposalsParams) (ListProposalsRes, error)
	// ListReleaseNotes implements listReleaseNotes operation.
	//
	// Every Release Note, drafts and scheduled ones too, newest first. For Admins.
	//
	// GET /api/v1/admin/release-notes
	ListReleaseNotes(ctx context.Context) (ListReleaseNotesRes, error)
	// ListRetrainChoices implements listRetrainChoices operation.
	//
	// Each pick the Character made on a level, with the options it could take instead. The owner only.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/retrains/choices
	ListRetrainChoices(ctx context.Context, params ListRetrainChoicesParams) (ListRetrainChoicesRes, error)
	// ListRetrains implements listRetrains operation.
	//
	// A Character's retrain requests, newest first. Its owner or a DM.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/retrains
	ListRetrains(ctx context.Context, params ListRetrainsParams) (ListRetrainsRes, error)
	// ListRolls implements listRolls operation.
	//
	// Recent Roll Requests in the Campaign. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}/rolls
	ListRolls(ctx context.Context, params ListRollsParams) (ListRollsRes, error)
	// ListSessions implements listSessions operation.
	//
	// The Campaign's Sessions, newest first. Members only.
	//
	// GET /api/v1/campaigns/{campaignId}/sessions
	ListSessions(ctx context.Context, params ListSessionsParams) (ListSessionsRes, error)
	// ListSettlementRevisions implements listSettlementRevisions operation.
	//
	// Every Revision of the Settlement, newest first. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/settlements/{settlementId}/revisions
	ListSettlementRevisions(ctx context.Context, params ListSettlementRevisionsParams) (ListSettlementRevisionsRes, error)
	// ListSettlements implements listSettlements operation.
	//
	// The Campaign's Settlements. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/settlements
	ListSettlements(ctx context.Context, params ListSettlementsParams) (ListSettlementsRes, error)
	// ListShopRevisions implements listShopRevisions operation.
	//
	// Every Revision of the Shop, newest first. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/shops/{shopId}/revisions
	ListShopRevisions(ctx context.Context, params ListShopRevisionsParams) (ListShopRevisionsRes, error)
	// ListShops implements listShops operation.
	//
	// The Campaign's Shops. DM only.
	//
	// GET /api/v1/campaigns/{campaignId}/shops
	ListShops(ctx context.Context, params ListShopsParams) (ListShopsRes, error)
	// ListSources implements listSources operation.
	//
	// The documents the compendium draws from, with the attribution each license requires.
	//
	// GET /api/v1/compendium/sources
	ListSources(ctx context.Context) (ListSourcesRes, error)
	// ListSpells implements listSpells operation.
	//
	// Spells in name order, one page at a time. Without a ruleset the 2024 rules lead the blend.
	//
	// GET /api/v1/compendium/spells
	ListSpells(ctx context.Context, params ListSpellsParams) (ListSpellsRes, error)
	// PlanLevelUp implements planLevelUp operation.
	//
	// The classes the next level can go to and, for one of them, its hit points, choices and spells. The
	// owner or a DM, out of combat.
	//
	// GET /api/v1/campaigns/{campaignId}/characters/{characterId}/level-up
	PlanLevelUp(ctx context.Context, params PlanLevelUpParams) (PlanLevelUpRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}

// WebhookHandler handles webhooks described by OpenAPI v3 specification.
type WebhookHandler interface {
	// LiveCommand implements liveCommand operation.
	//
	// Not an HTTP call. The shape of every WebSocket frame a client sends on
	// /api/v1/campaigns/{campaignId}/sessions/{sessionId}/live.
	//
	LiveCommand(ctx context.Context, req *LiveCommand) error
	// LiveUpdate implements liveUpdate operation.
	//
	// Not an HTTP call. The shape of every WebSocket frame the server sends on the live Session socket.
	//
	LiveUpdate(ctx context.Context, req *LiveUpdate) error
}

// WebhookServer implements http server based on OpenAPI v3 specification and
// calls WebhookHandler to handle requests.
type WebhookServer struct {
	h WebhookHandler
	baseServer
}

// NewWebhookServer creates new WebhookServer.
func NewWebhookServer(h WebhookHandler, opts ...ServerOption) (*WebhookServer, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &WebhookServer{
		h:          h,
		baseServer: s,
	}, nil
}
