// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleForwardAuth handles forwardAuth security.
	// Identity injected by the platform's forward-auth; never sent by clients directly.
	HandleForwardAuth(ctx context.Context, operationName OperationName, t ForwardAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesForwardAuth is a private map storing roles per operation.
var operationRolesForwardAuth = map[string][]string{
	AcceptFriendRequestOperation:           []string{},
	AcceptInviteOperation:                  []string{},
	BeginTwoStepOperation:                  []string{},
	CancelFriendRequestOperation:           []string{},
	CastRitualOperation:                    []string{},
	ClearTokenIconOperation:                []string{},
	ConfirmTwoStepOperation:                []string{},
	CopySpellOperation:                     []string{},
	CreateAccessTokenOperation:             []string{},
	CreateAccountInviteOperation:           []string{},
	CreateCampaignOperation:                []string{},
	CreateCharacterOperation:               []string{},
	CreateEncounterPoolOperation:           []string{},
	CreateEncounterTableOperation:          []string{},
	CreateInviteOperation:                  []string{},
	CreateLootTableOperation:               []string{},
	CreateNpcOperation:                     []string{},
	CreatePushSubscriptionOperation:        []string{},
	CreateRollOperation:                    []string{},
	CreateSettlementOperation:              []string{},
	CreateShopOperation:                    []string{},
	DeclineFriendRequestOperation:          []string{},
	DeleteCharacterOperation:               []string{},
	DeleteEncounterPoolOperation:           []string{},
	DeleteEncounterTableOperation:          []string{},
	DeleteLootTableOperation:               []string{},
	DeleteNpcOperation:                     []string{},
	DeletePushSubscriptionOperation:        []string{},
	DeleteSettlementOperation:              []string{},
	DeleteShopOperation:                    []string{},
	DiffNpcRevisionsOperation:              []string{},
	DisableTwoStepOperation:                []string{},
	DiscardCharacterDraftOperation:         []string{},
	DraftReleaseNoteOperation:              []string{},
	EditReleaseNoteOperation:               []string{},
	EndSessionOperation:                    []string{},
	GetAccountOperation:                    []string{},
	GetAccountHistoryOperation:             []string{},
	GetActionLogOperation:                  []string{},
	GetAdminAccountOperation:               []string{},
	GetAutomationCoverageOperation:         []string{},
	GetBuilderOptionsOperation:             []string{},
	GetCampaignOperation:                   []string{},
	GetCharacterOperation:                  []string{},
	GetCharacterDraftOperation:             []string{},
	GetEntryOperation:                      []string{},
	GetMapOperation:                        []string{},
	GetMapImageOperation:                   []string{},
	GetMeOperation:                         []string{},
	GetMyCharacterOperation:                []string{},
	GetNotificationPreferencesOperation:    []string{},
	GetNpcOperation:                        []string{},
	GetPortraitOperation:                   []string{},
	GetPushKeyOperation:                    []string{},
	GetRollOperation:                       []string{},
	GetSessionOperation:                    []string{},
	GetSessionLogOperation:                 []string{},
	GetSessionViewOperation:                []string{},
	GetSpellOperation:                      []string{},
	GetSpellcastingOperation:               []string{},
	GetStatusOperation:                     []string{},
	GetTokenIconOperation:                  []string{},
	GetUnseenReleaseNoteOperation:          []string{},
	JoinCampaignOperation:                  []string{},
	LevelUpOperation:                       []string{},
	ListAccessTokensOperation:              []string{},
	ListActivityOperation:                  []string{},
	ListAdminAccountsOperation:             []string{},
	ListCampaignsOperation:                 []string{},
	ListCharactersOperation:                []string{},
	ListConversationsOperation:             []string{},
	ListDeletedNpcsOperation:               []string{},
	ListEncounterChecksOperation:           []string{},
	ListEncounterPoolRevisionsOperation:    []string{},
	ListEncounterPoolsOperation:            []string{},
	ListEncounterTableRevisionsOperation:   []string{},
	ListEncounterTablesOperation:           []string{},
	ListEntriesOperation:                   []string{},
	ListFriendsOperation:                   []string{},
	ListInvitesOperation:                   []string{},
	ListLocationsOperation:                 []string{},
	ListLootTableRevisionsOperation:        []string{},
	ListLootTablesOperation:                []string{},
	ListMapsOperation:                      []string{},
	ListMentionablesOperation:              []string{},
	ListMessagesOperation:                  []string{},
	ListMyCharactersOperation:              []string{},
	ListNotificationsOperation:             []string{},
	ListNpcRevisionsOperation:              []string{},
	ListNpcsOperation:                      []string{},
	ListReleaseNotesOperation:              []string{},
	ListRollsOperation:                     []string{},
	ListSessionsOperation:                  []string{},
	ListSettlementRevisionsOperation:       []string{},
	ListSettlementsOperation:               []string{},
	ListShopRevisionsOperation:             []string{},
	ListShopsOperation:                     []string{},
	ListSourcesOperation:                   []string{},
	ListSpellsOperation:                    []string{},
	PlanLevelUpOperation:                   []string{},
	PrepareSpellsOperation:                 []string{},
	PreviewCharacterOperation:              []string{},
	PreviewInviteOperation:                 []string{},
	PreviewReachOperation:                  []string{},
	PreviewSightOperation:                  []string{},
	PublishReleaseNoteOperation:            []string{},
	ReadAllNotificationsOperation:          []string{},
	ReadNotificationOperation:              []string{},
	RemoveMemberOperation:                  []string{},
	RerollStockOperation:                   []string{},
	ResetAccountTwoStepOperation:           []string{},
	ResetRecoveryCodesOperation:            []string{},
	RestoreEncounterPoolRevisionOperation:  []string{},
	RestoreEncounterTableRevisionOperation: []string{},
	RestoreLootTableRevisionOperation:      []string{},
	RestoreNpcRevisionOperation:            []string{},
	RestoreSettlementRevisionOperation:     []string{},
	RestoreShopRevisionOperation:           []string{},
	RevokeAccessTokenOperation:             []string{},
	RevokeInviteOperation:                  []string{},
	RollCharacterScoresOperation:           []string{},
	RollRestOperation:                      []string{},
	SaveCharacterDraftOperation:            []string{},
	SeeReleaseNoteOperation:                []string{},
	SendAdminSignInLinkOperation:           []string{},
	SendFriendRequestOperation:             []string{},
	SendLiveCommandOperation:               []string{},
	SendMessageOperation:                   []string{},
	SetAccountDisabledOperation:            []string{},
	SetAccountPasswordOperation:            []string{},
	SetAdminRoleOperation:                  []string{},
	SetDieOperation:                        []string{},
	SetNotificationPreferencesOperation:    []string{},
	SetPortraitOperation:                   []string{},
	SetTokenIconOperation:                  []string{},
	StartConversationOperation:             []string{},
	StartOidcLinkOperation:                 []string{},
	StartSessionOperation:                  []string{},
	UnblockOperation:                       []string{},
	UndoChangeOperation:                    []string{},
	UnfriendOperation:                      []string{},
	UnlinkOidcOperation:                    []string{},
	UpdateAccountOperation:                 []string{},
	UpdateCampaignOperation:                []string{},
	UpdateCharacterOperation:               []string{},
	UpdateEncounterPoolOperation:           []string{},
	UpdateEncounterTableOperation:          []string{},
	UpdateLootTableOperation:               []string{},
	UpdateMapOperation:                     []string{},
	UpdateMemberOperation:                  []string{},
	UpdateMyCharacterOperation:             []string{},
	UpdateNpcOperation:                     []string{},
	UpdateSettlementOperation:              []string{},
	UpdateShopOperation:                    []string{},
	UploadMapOperation:                     []string{},
}

// GetRolesForForwardAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForForwardAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForForwardAuth(operation string) []string {
	roles, ok := operationRolesForwardAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityForwardAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ForwardAuth
	const parameterName = "X-User-Id"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesForwardAuth[operationName]
	rctx, err := s.sec.HandleForwardAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ForwardAuth provides forwardAuth security value.
	// Identity injected by the platform's forward-auth; never sent by clients directly.
	ForwardAuth(ctx context.Context, operationName OperationName) (ForwardAuth, error)
}

func (s *Client) securityForwardAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ForwardAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ForwardAuth\"")
	}
	req.Header.Set("X-User-Id", t.APIKey)
	return nil
}
