// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAutomationCoverageData, GetAutomationCoverageErrors, GetAutomationCoverageResponses, GetEntryData, GetEntryErrors, GetEntryResponses, GetHealthData, GetHealthErrors, GetHealthResponses, GetMeData, GetMeErrors, GetMeResponses, GetReadinessData, GetReadinessErrors, GetReadinessResponses, GetSpellData, GetSpellErrors, GetSpellResponses, GetStatusData, GetStatusErrors, GetStatusResponses, ListEntriesData, ListEntriesErrors, ListEntriesResponses, ListSourcesData, ListSourcesErrors, ListSourcesResponses, ListSpellsData, ListSpellsErrors, ListSpellsResponses } from './types.gen';
import { zGetAutomationCoverageHeaders, zGetAutomationCoverageResponse, zGetEntryHeaders, zGetEntryPath, zGetEntryQuery, zGetEntryResponse, zGetHealthResponse, zGetMeResponse, zGetReadinessResponse, zGetSpellHeaders, zGetSpellPath, zGetSpellQuery, zGetSpellResponse, zGetStatusResponse, zListEntriesHeaders, zListEntriesQuery, zListEntriesResponse, zListSourcesResponse, zListSpellsHeaders, zListSpellsQuery, zListSpellsResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List spells
 *
 * Spells in name order, one page at a time. Without a ruleset the 2024 rules lead the blend.
 */
export const listSpells = <ThrowOnError extends boolean = false>(options?: Options<ListSpellsData, ThrowOnError>): RequestResult<ListSpellsResponses, ListSpellsErrors, ThrowOnError> => (options?.client ?? client).get<ListSpellsResponses, ListSpellsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        headers: zListSpellsHeaders.optional(),
        path: z.never().optional(),
        query: zListSpellsQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListSpellsResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/compendium/spells',
    ...options
});

/**
 * Get a spell
 *
 * One spell with its rules text and the conditions it mentions.
 */
export const getSpell = <ThrowOnError extends boolean = false>(options: Options<GetSpellData, ThrowOnError>): RequestResult<GetSpellResponses, GetSpellErrors, ThrowOnError> => (options.client ?? client).get<GetSpellResponses, GetSpellErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        headers: zGetSpellHeaders.optional(),
        path: zGetSpellPath,
        query: zGetSpellQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetSpellResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/compendium/spells/{slug}',
    ...options
});

/**
 * List compendium entries
 *
 * Entries of one kind in name order, one page at a time. Without a ruleset the 2024 rules lead the blend.
 */
export const listEntries = <ThrowOnError extends boolean = false>(options: Options<ListEntriesData, ThrowOnError>): RequestResult<ListEntriesResponses, ListEntriesErrors, ThrowOnError> => (options.client ?? client).get<ListEntriesResponses, ListEntriesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        headers: zListEntriesHeaders.optional(),
        path: z.never().optional(),
        query: zListEntriesQuery
    }).parseAsync(data),
    responseValidator: async (data) => await zListEntriesResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/compendium/entries',
    ...options
});

/**
 * Get a compendium entry
 *
 * One entry rendered for reading, with the conditions its text mentions.
 */
export const getEntry = <ThrowOnError extends boolean = false>(options: Options<GetEntryData, ThrowOnError>): RequestResult<GetEntryResponses, GetEntryErrors, ThrowOnError> => (options.client ?? client).get<GetEntryResponses, GetEntryErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        headers: zGetEntryHeaders.optional(),
        path: zGetEntryPath,
        query: zGetEntryQuery.optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetEntryResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/compendium/entries/{kind}/{slug}',
    ...options
});

/**
 * Get automation coverage
 *
 * How many entries of each kind the rules engine computes fully, partly, or leaves to the DM.
 */
export const getAutomationCoverage = <ThrowOnError extends boolean = false>(options?: Options<GetAutomationCoverageData, ThrowOnError>): RequestResult<GetAutomationCoverageResponses, GetAutomationCoverageErrors, ThrowOnError> => (options?.client ?? client).get<GetAutomationCoverageResponses, GetAutomationCoverageErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        headers: zGetAutomationCoverageHeaders.optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetAutomationCoverageResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/compendium/automation',
    ...options
});

/**
 * List compendium sources
 *
 * The documents the compendium draws from, with the attribution each license requires.
 */
export const listSources = <ThrowOnError extends boolean = false>(options?: Options<ListSourcesData, ThrowOnError>): RequestResult<ListSourcesResponses, ListSourcesErrors, ThrowOnError> => (options?.client ?? client).get<ListSourcesResponses, ListSourcesErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zListSourcesResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/compendium/sources',
    ...options
});

/**
 * Who am I
 *
 * Returns the identity the platform authenticated for this request.
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetMeResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/me',
    ...options
});

/**
 * Service status
 *
 * Reports the running version and whether the database answers.
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>): RequestResult<GetStatusResponses, GetStatusErrors, ThrowOnError> => (options?.client ?? client).get<GetStatusResponses, GetStatusErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetStatusResponse.parseAsync(data),
    security: [{ name: 'X-User-Id', type: 'apiKey' }],
    url: '/api/v1/status',
    ...options
});

/**
 * Liveness probe
 *
 * Returns ok while the process is serving requests.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetHealthResponse.parseAsync(data),
    url: '/healthz',
    ...options
});

/**
 * Readiness probe
 *
 * Returns ok once the API can serve traffic.
 */
export const getReadiness = <ThrowOnError extends boolean = false>(options?: Options<GetReadinessData, ThrowOnError>): RequestResult<GetReadinessResponses, GetReadinessErrors, ThrowOnError> => (options?.client ?? client).get<GetReadinessResponses, GetReadinessErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    responseValidator: async (data) => await zGetReadinessResponse.parseAsync(data),
    url: '/readyz',
    ...options
});
