import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test('a Companion joins the party, fights under a Player\'s hand, and is handed back to the DM', async ({ page, browser }, info) => {
  test.skip(info.project.name !== 'desktop', 'one multi-client run is enough')
  test.slow()
  const stamp = String(Date.now())
  await page.goto('/campaigns')
  await page.getByTestId('campaign-name').fill(`Allies ${stamp}`)
  await page.getByTestId('campaign-display-name').fill('DM')
  await page.getByRole('button', { name: 'Start as DM' }).click()
  await page.getByTestId('create-invite').click()
  const link = new URL(await page.getByTestId('invite-link').inputValue())
  const player = await (await browser.newContext({ extraHTTPHeaders: { 'X-User-Id': `e2e-ally-${stamp}` } })).newPage()
  await player.goto(link.pathname + link.hash)
  await player.getByTestId('join-display-name').fill('Aria')
  await player.getByRole('button', { name: 'Join as Player' }).click()
  await expect(player.getByTestId('member-list')).toContainText('Aria (you)')
  await page.reload()

  // The DM adds Fang, a goblin of a companion, for Aria to run, with a share of the XP.
  const section = page.getByTestId('companions')
  await section.getByTestId('companion-name').fill('Fang')
  await section.getByTestId('companion-creature').fill('no-such-beast')
  await section.getByTestId('companion-save').click()
  await expect(section.getByTestId('companion-problem')).toContainText('no such creature')
  await section.getByTestId('companion-creature').fill('goblin-warrior')
  await section.getByTestId('companion-controller').selectOption({ label: 'Aria' })
  await section.getByTestId('companion-shares').check()
  await section.getByTestId('companion-save').click()
  await expect(section.getByTestId('companion-Fang')).toContainText('Run by Aria')
  await expect(section.getByTestId('companion-Fang')).toContainText('takes a share of the XP')
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await player.reload()
  await expect(player.getByTestId('companion-Fang')).toContainText('Run by you')
  await expect(player.getByTestId('companion-form')).toHaveCount(0)

  // In play Fang stands with the party, marked in the roster, and is Aria's to move.
  await page.getByTestId('start-session').click()
  await expect(page.getByTestId('connection')).toHaveText('Live')
  await player.goto(new URL(page.url()).pathname)
  await page.getByTestId('token-companion').selectOption({ label: 'Fang' })
  await page.locator('[data-hex="0,0"]').click()
  await expect(page.locator('[data-hex="0,0"]')).toHaveAttribute('aria-label', /Fang/)
  await expect(page.getByTestId('token-companion').getByRole('option')).toHaveText(['None'])
  for (const screen of [page, player]) await expect(screen.getByTestId('companion-Fang')).toHaveText('Companion')
  await player.locator('[data-hex="0,0"]').click()
  await player.locator('[data-hex="1,0"]').click()
  await player.getByTestId('confirm-walk').click()
  await expect(page.locator('[data-hex="1,0"]')).toHaveAttribute('aria-label', /Fang/)

  // The DM takes Fang over: it is Aria's to move no longer.
  await page.locator('[data-hex="1,0"]').click()
  await page.getByTestId('token-hand').selectOption({ label: 'The DM' })
  await expect(page.getByTestId('token-hand')).toHaveValue('')
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.goto(new URL(page.url()).pathname.replace(/\/sessions\/.*$/, ''))
  await expect(page.getByTestId('companion-Fang')).toContainText('Run by the DM')
  await player.context().close()
})
