import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test('the DM prepares random encounters, and rests and checks roll them secretly or on the table', async ({ page, browser }, info) => {
  test.skip(info.project.name !== 'desktop', 'one multi-client run is enough')
  const stamp = String(Date.now())
  await page.goto('/campaigns')
  await page.getByTestId('campaign-name').fill(`Wilds ${stamp}`)
  await page.getByTestId('campaign-display-name').fill('DM')
  await page.getByRole('button', { name: 'Start as DM' }).click()
  await page.getByTestId('create-invite').click()
  const link = new URL(await page.getByTestId('invite-link').inputValue())

  await page.getByTestId('encounters-link').click()
  await page.getByTestId('new-pool').click()
  await page.getByTestId('pool-name').fill('Goblin band')
  await page.getByTestId('pool-difficulty').selectOption('low')
  await page.getByTestId('member-slug-0').fill('goblin')
  await page.getByTestId('member-min-0').fill('2')
  await page.getByTestId('save-pool').click()
  await expect(page.getByTestId('pool-Goblin band')).toContainText('levels 1–4 · low · goblin 2–4')
  await page.getByTestId('new-table').click()
  await page.getByTestId('table-name').fill('Anywhere')
  await page.getByTestId('table-chance').fill('100')
  await page.getByTestId('entry-kind-0').selectOption('pool')
  await page.getByTestId('entry-pool-0').selectOption({ label: 'Goblin band' })
  await page.getByTestId('save-table').click()
  await expect(page.getByTestId('table-Anywhere')).toContainText('Everywhere · 100% · secret')
  await page.getByTestId('new-table').click()
  await page.getByTestId('table-name').fill('Road')
  await page.getByTestId('table-chance').fill('50')
  await page.getByTestId('table-visibility').selectOption('open')
  await page.getByTestId('entry-kind-0').selectOption('encounter')
  await page.getByTestId('entry-label-0').fill('Ambush')
  await page.getByTestId('entry-monsters-0').fill('goblin x3')
  await page.getByTestId('save-table').click()
  await expect(page.getByTestId('table-Road')).toContainText('1× Ambush (goblin x3)')
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByRole('link', { name: '← Campaign' }).click()

  const context = await browser.newContext({ extraHTTPHeaders: { 'X-User-Id': `e2e-wilds-${stamp}` } })
  const player = await context.newPage()
  const frames: string[] = []
  player.on('websocket', (ws) => {
    ws.on('framereceived', (f) => frames.push(String(f.payload)))
  })
  await player.goto(link.pathname + link.hash)
  await player.getByTestId('join-display-name').fill('Aria')
  await player.getByRole('button', { name: 'Join as Player' }).click()
  await expect(player.getByTestId('member-list')).toContainText('Aria (you)')

  await page.getByTestId('start-session').click()
  await expect(page.getByTestId('connection')).toHaveText('Live')
  const sessionUrl = new URL(page.url()).pathname
  await player.goto(sessionUrl)
  await expect(player.getByTestId('connection')).toHaveText('Live')
  const table = await (await browser.newContext({ extraHTTPHeaders: { 'X-User-Id': `e2e-wilds-${stamp}` } })).newPage()
  await table.goto(`${sessionUrl}/table`)

  await page.getByTestId('rest-long').click()
  const checks = page.getByTestId('encounter-checks')
  await expect(checks.getByRole('listitem').first()).toContainText(/Long rest on Anywhere · rolled \d+ against 100% · encounter: Goblin band · goblin x[234]/)
  await expect(player.getByTestId('encounter-checks').getByRole('listitem').first()).toHaveText('Long rest · something approaches!')
  await expect(table.getByTestId('table-check')).toHaveText('Long rest · something approaches!')

  await page.getByTestId('check-table').selectOption({ label: 'Road' })
  await page.getByTestId('run-check').click()
  await expect(table.getByTestId('table-check').getByTestId('roll-card')).toContainText('Encounter check')
  await expect(player.getByTestId('encounter-checks').getByRole('listitem').first()).toHaveText('The DM checks · rolling…')
  const card = page.getByTestId('roll-card')
  await card.getByTestId('manual-0').click()
  await card.getByTestId('pad-0').getByRole('button', { name: '99', exact: true }).click()
  await expect(table.getByTestId('table-check')).toHaveText('The DM checks · rolled 99 against 50% · all quiet')
  await expect(checks.getByRole('listitem').first()).toContainText('The DM checks on Road · rolled 99 against 50% · all quiet')

  await page.getByTestId('check-mode').selectOption('force_encounter')
  await page.getByTestId('run-check').click()
  await expect(checks.getByRole('listitem').first()).toContainText('encounter: Ambush · goblin x3')
  expect(frames.join('\n')).not.toContain('Anywhere')
  expect(frames.join('\n')).not.toContain('Ambush')

  await page.goto(`/campaigns/${new URL(page.url()).pathname.split('/')[2] ?? ''}/encounters`)
  await expect(page.getByTestId('check-log')).toContainText('Long rest on Anywhere')
  await expect(page.getByTestId('check-log').getByRole('listitem')).toHaveCount(3)
})
