import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test('the DM moves the Game Clock and every screen reads the new time', async ({ page, browser }, info) => {
  test.skip(info.project.name !== 'desktop', 'one multi-client run is enough')
  const stamp = String(Date.now())
  await page.goto('/campaigns')
  await page.getByTestId('campaign-name').fill(`Clock ${stamp}`)
  await page.getByTestId('campaign-display-name').fill('DM')
  await page.getByRole('button', { name: 'Start as DM' }).click()
  await page.getByTestId('create-invite').click()
  const link = new URL(await page.getByTestId('invite-link').inputValue())
  const player = await (await browser.newContext({ extraHTTPHeaders: { 'X-User-Id': `e2e-clock-${stamp}` } })).newPage()
  await player.goto(link.pathname + link.hash)
  await player.getByTestId('join-display-name').fill('Aria')
  await player.getByRole('button', { name: 'Join as Player' }).click()
  await expect(player.getByTestId('member-list')).toContainText('Aria (you)')

  await page.getByTestId('start-session').click()
  await expect(page.getByTestId('connection')).toHaveText('Live')
  await page.getByTestId('scope-world').check()
  await player.goto(new URL(page.url()).pathname)
  await expect(player.getByTestId('connection')).toHaveText('Live')
  await player.getByTestId('scope-world').check()
  await expect(player.getByTestId('game-clock')).toHaveText('Day 0, 00:00')
  await expect(player.getByTestId('clock-tools')).toHaveCount(0)
  await expect(player.getByTestId('marching-order')).toContainText('No Characters in this Campaign yet.')

  await page.getByTestId('clock-dawn').click()
  await expect(player.getByTestId('game-clock')).toHaveText('Day 0, 06:00')
  await page.getByTestId('clock-hour').click()
  await expect(player.getByTestId('game-clock')).toHaveText('Day 0, 07:00')
  await page.getByTestId('clock-day').fill('12')
  await page.getByTestId('clock-time').fill('21:30')
  await page.getByTestId('clock-set').click()
  await expect(player.getByTestId('game-clock')).toHaveText('Day 12, 21:30')
  await expect(page.getByTestId('game-clock')).toHaveText('Day 12, 21:30')
  // It is the Campaign's clock: a screen that joins later reads the same time.
  await player.reload()
  await player.getByTestId('scope-world').check()
  await expect(player.getByTestId('game-clock')).toHaveText('Day 12, 21:30')
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  expect((await new AxeBuilder({ page: player }).analyze()).violations).toEqual([])
})
