import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import { buildFighter } from './wizard'

test('loot drops into the session and the party carries it off by dragging or choosing', async ({ page, browser }, info) => {
  test.skip(info.project.name !== 'desktop', 'one multi-client run is enough')
  const stamp = String(Date.now())
  await page.goto('/campaigns')
  await page.getByTestId('campaign-name').fill(`Hoard ${stamp}`)
  await page.getByTestId('campaign-display-name').fill('DM')
  await page.getByRole('button', { name: 'Start as DM' }).click()
  await page.getByTestId('create-invite').click()
  const link = new URL(await page.getByTestId('invite-link').inputValue())

  await page.getByTestId('loot-link').click()
  for (const [name, kind, amount] of [['Ropes', 'item', '3'], ['Purse', 'currency', '50']] as const) {
    await page.getByTestId('new-loot').click()
    await page.getByTestId('loot-name').fill(name)
    await page.getByTestId('loot-kind-0').selectOption(kind)
    if (kind === 'item') await page.getByTestId('loot-item-0').fill('rope')
    await page.getByTestId('loot-amount-0').fill(amount)
    await page.getByTestId('save-loot').click()
  }
  await expect(page.getByTestId('loot-Ropes')).toContainText('rolled 1× · 1× 3 rope')
  await expect(page.getByTestId('loot-Purse')).toContainText('1× 50 gp')
  await page.getByTestId('new-loot').click()
  await page.getByTestId('loot-name').fill('Bad')
  await page.getByTestId('loot-amount-0').fill('lots')
  await page.getByTestId('save-loot').click()
  await expect(page.getByTestId('loot-error')).toContainText('write amounts as')
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByTestId('to-campaign').click()

  const context = await browser.newContext({ extraHTTPHeaders: { 'X-User-Id': `e2e-hoard-${stamp}` } })
  const player = await context.newPage()
  await player.goto(link.pathname + link.hash)
  await player.getByTestId('join-display-name').fill('Aria')
  await player.getByRole('button', { name: 'Join as Player' }).click()
  await expect(player.getByTestId('member-list')).toContainText('Aria (you)')
  await player.getByTestId('build-character').click()
  await buildFighter(player, 'Mira')
  await player.getByTestId('create-character').click()
  await expect(player.getByRole('heading', { name: 'Mira' })).toBeVisible()

  await page.reload()
  await page.getByTestId('start-session').click()
  await expect(page.getByTestId('connection')).toHaveText('Live')
  await player.goto(new URL(page.url()).pathname)
  await expect(player.getByTestId('connection')).toHaveText('Live')
  const mira = player.getByTestId('container-Mira')
  await expect(mira.getByTestId('load')).toHaveText(/^0 \/ \d+ lb$/)

  for (const table of ['Ropes', 'Purse']) {
    await page.getByTestId('roll-loot-table').selectOption({ label: table })
    await page.getByTestId('roll-loot').click()
    await expect(player.getByTestId(`container-Loot: ${table}`)).toBeVisible()
  }
  const ropes = player.getByTestId('container-Loot: Ropes')
  await expect(ropes).toContainText('Rope ×3')
  await ropes.getByRole('combobox', { name: 'Where Rope goes' }).selectOption({ label: 'Mira' })
  await ropes.getByRole('spinbutton', { name: 'How many Rope' }).fill('2')
  await ropes.getByRole('button', { name: 'Move Rope from Loot: Ropes' }).click()
  await expect(mira).toContainText('Rope ×2')
  await expect(ropes).toContainText('Rope ×1')
  await ropes.getByRole('listitem').dragTo(player.getByTestId('container-Party Stash'), { sourcePosition: { x: 8, y: 8 } })
  await expect(player.getByTestId('container-Party Stash')).toContainText('Rope ×1')
  await expect(page.getByTestId('container-Party Stash')).toContainText('Rope ×1')
  await expect(ropes).toHaveCount(0)
  await player.getByTestId('container-Loot: Purse').getByRole('listitem').dragTo(mira, { sourcePosition: { x: 8, y: 8 } })
  await expect(mira).toContainText('50 gp')
  await expect(player.getByTestId('container-Loot: Purse')).toHaveCount(0)
  expect((await new AxeBuilder({ page: player }).analyze()).violations).toEqual([])
})
