import AxeBuilder from '@axe-core/playwright'
import { expect, type Page, test } from '@playwright/test'
import { buildFighter } from './wizard'

async function enter(page: Page, faces: string[]) {
  const card = page.getByTestId('roll-card')
  for (const [i, face] of faces.entries()) {
    await card.getByTestId(`manual-${String(i)}`).click()
    await card.getByTestId(`pad-${String(i)}`).getByRole('button', { name: face, exact: true }).click()
  }
}

test('the DM opens a shop stocked from a loot table, and a player haggles, buys and sells', async ({ page, browser }, info) => {
  test.skip(info.project.name !== 'desktop', 'one multi-client run is enough')
  const stamp = String(Date.now())
  await page.goto('/campaigns')
  await page.getByTestId('campaign-name').fill(`Market ${stamp}`)
  await page.getByTestId('campaign-display-name').fill('DM')
  await page.getByRole('button', { name: 'Start as DM' }).click()
  await page.getByTestId('create-invite').click()
  const link = new URL(await page.getByTestId('invite-link').inputValue())

  await page.getByTestId('loot-link').click()
  for (const [name, kind, amount] of [['Ropes', 'item', '3'], ['Purse', 'currency', '50']] as const) {
    await page.getByTestId('new-loot').click()
    await page.getByTestId('loot-name').fill(name)
    await page.getByTestId('loot-kind-0').selectOption(kind)
    if (kind === 'item') await page.getByTestId('loot-item-0').fill('rope')
    await page.getByTestId('loot-amount-0').fill(amount)
    await page.getByTestId('save-loot').click()
  }
  await expect(page.getByTestId('loot-Purse')).toBeVisible()
  await page.getByRole('link', { name: '← Campaign' }).click()

  await page.getByTestId('shops-link').click()
  await page.getByTestId('new-settlement').click()
  await page.getByTestId('settlement-name').fill('Oakford')
  await page.getByTestId('save-settlement').click()
  await expect(page.getByTestId('settlement-Oakford')).toContainText('modest village')
  await page.getByTestId('new-shop').click()
  await page.getByTestId('shop-name').fill('Store')
  await page.getByTestId('shop-haggle-dc').fill('10')
  await page.getByTestId('shop-loot').selectOption({ label: 'Ropes' })
  await page.getByTestId('save-shop').click()
  const store = page.getByTestId('shop-Store')
  await expect(store).toContainText('Nothing in stock.')
  await store.getByRole('button', { name: 'Reroll stock of Store' }).click()
  await expect(store.getByTestId('stock-Store-rope')).toHaveText('6× rope · 1 gp')
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
  await page.getByRole('link', { name: '← Campaign' }).click()

  const context = await browser.newContext({ extraHTTPHeaders: { 'X-User-Id': `e2e-market-${stamp}` } })
  const player = await context.newPage()
  await player.goto(link.pathname + link.hash)
  await player.getByTestId('join-display-name').fill('Aria')
  await player.getByRole('button', { name: 'Join as Player' }).click()
  await expect(player.getByTestId('member-list')).toContainText('Aria (you)')
  await player.getByTestId('build-character').click()
  await buildFighter(player, 'Mira')
  await player.getByTestId('create-character').click()
  await expect(player.getByRole('heading', { name: 'Mira' })).toBeVisible()

  await page.reload()
  await page.getByTestId('start-session').click()
  await expect(page.getByTestId('connection')).toHaveText('Live')
  await player.goto(new URL(page.url()).pathname)
  await expect(player.getByTestId('connection')).toHaveText('Live')
  const mira = player.getByTestId('container-Mira')
  await page.getByTestId('roll-loot-table').selectOption({ label: 'Purse' })
  await page.getByTestId('roll-loot').click()
  await player.getByTestId('container-Loot: Purse').getByRole('listitem').dragTo(mira)
  await expect(mira).toContainText('50 gp')
  await expect(player.getByTestId('shop-panel')).toHaveCount(0)

  await expect(page.getByTestId('game-day')).toHaveText('Day 0')
  await page.getByTestId('shop-choice').selectOption({ label: 'Store' })
  await page.getByTestId('open-shop').click()
  const shop = player.getByTestId('shop-panel')
  await expect(shop.getByTestId('shop-open')).toHaveText('Store · general in Oakford')
  await expect(shop.getByTestId('stock-rope').getByTestId('price')).toHaveText('1 gp')
  await shop.getByTestId('haggle').click()
  await expect(shop.getByTestId('haggle-pending')).toBeVisible()
  await expect(shop.getByTestId('roll-card')).toContainText('Haggle at Store')
  expect((await new AxeBuilder({ page: player }).analyze()).violations).toEqual([])
  await enter(player, ['20'])
  await expect(shop.getByTestId('haggle-result')).toHaveText('Haggled: 10% off')
  await expect(shop.getByTestId('stock-rope').getByTestId('price')).toHaveText('9 sp')

  await shop.getByTestId('buy-rope').click()
  await expect(mira).toContainText('Rope ×1')
  await expect(shop.getByTestId('stock-rope')).toContainText('Rope ×5')
  await expect(page.getByTestId('shop-panel').getByTestId('stock-rope')).toContainText('Rope ×5')
  await shop.getByTestId('sell-item').selectOption('rope')
  await shop.getByTestId('sell').click()
  await expect(mira).not.toContainText('Rope')
  await expect(shop.getByTestId('stock-rope')).toContainText('Rope ×6')

  await page.getByTestId('rest-long').click()
  await expect(page.getByTestId('game-day')).toHaveText('Day 1')
  await expect(shop.getByTestId('game-day')).toHaveText('Day 1')
  await page.getByTestId('close-shop').click()
  await expect(player.getByTestId('shop-panel')).toHaveCount(0)
})
